/*
 * Generated spell scripts for Hunter
 * Auto-generated by generate_spell_fixes.py on 2026-03-07
 * Based on spell audit classification of YELLOW/RED spells
 *
 * These scripts handle passive DUMMY aura value consumption,
 * PERIODIC_DUMMY tick behavior, proc handlers, and active DUMMY effects.
 */

#include "Player.h"
#include "ScriptMgr.h"
#include "Spell.h"
#include "SpellAuraEffects.h"
#include "SpellAuras.h"
#include "SpellInfo.h"
#include "SpellScript.h"
#include "Unit.h"

// =====================================================================
// Spell ID Constants — Hunter
// =====================================================================

enum HunterSpellIds
{
    SPELL_HUNTER_EAGLE_EYE                                            = 6197,
    SPELL_HUNTER_BESTIAL_WRATH                                        = 19574,
    SPELL_HUNTER_ROAR_OF_SACRIFICE                                    = 53480,
    SPELL_HUNTER_MASTERY_MASTER_OF_BEASTS                             = 76657,
    SPELL_HUNTER_A_MURDER_OF_CROWS                                    = 131894,
    SPELL_HUNTER_CAMOUFLAGE                                           = 199483,
    SPELL_HUNTER_KILLER_COBRA                                         = 199532,
    SPELL_HUNTER_TRAILBLAZER                                          = 199921,
    SPELL_HUNTER_EXPLOSIVE_SHOT                                       = 212431,
    SPELL_HUNTER_SPITTING_COBRA                                       = 257891,
    SPELL_HUNTER_CHAKRAMS                                             = 259391,
    SPELL_HUNTER_CAREFUL_AIM                                          = 260228,
    SPELL_HUNTER_HYDRAS_BITE                                          = 260241,
    SPELL_HUNTER_VOLLEY                                               = 260243,
    SPELL_HUNTER_BLOODSEEKER                                          = 260248,
    SPELL_HUNTER_MASTER_MARKSMAN                                      = 260309,
    SPELL_HUNTER_BIRDS_OF_PREY                                        = 260331,
    SPELL_HUNTER_LETHAL_SHOTS                                         = 260393,
    SPELL_HUNTER_MASTERY_SPIRIT_BOND                                  = 263135,
    SPELL_HUNTER_TERMS_OF_ENGAGEMENT                                  = 265896,
    SPELL_HUNTER_VIPERS_VENOM                                         = 268501,
    SPELL_HUNTER_TRUESHOT                                             = 288613,
    SPELL_HUNTER_EYES_OF_THE_BEAST                                    = 321297,
    SPELL_HUNTER_BINDING_SHACKLES                                     = 321468,
    SPELL_HUNTER_DISRUPTIVE_ROUNDS                                    = 343244,
    SPELL_HUNTER_DEATHBLOW                                            = 343248,
    SPELL_HUNTER_KILL_CLEAVE                                          = 378207,
    SPELL_HUNTER_WILD_INSTINCTS                                       = 378442,
    SPELL_HUNTER_DIRE_COMMAND                                         = 378743,
    SPELL_HUNTER_FOCUSED_AIM                                          = 378767,
    SPELL_HUNTER_EXPLOSIVES_EXPERT                                    = 378937,
    SPELL_HUNTER_REJUVENATING_WIND                                    = 385539,
    SPELL_HUNTER_DIRE_FRENZY                                          = 385810,
    SPELL_HUNTER_BRUTAL_COMPANION                                     = 386870,
    SPELL_HUNTER_BULLETSTORM                                          = 389019,
    SPELL_HUNTER_SURGING_SHOTS                                        = 391559,
    SPELL_HUNTER_PIERCING_FANGS                                       = 392053,
    SPELL_HUNTER_WAR_ORDERS                                           = 393933,
    SPELL_HUNTER_SALVO                                                = 400456,
    SPELL_HUNTER_IN_THE_RHYTHM                                        = 407404,
    SPELL_HUNTER_MASTER_HANDLER                                       = 424558,
    SPELL_HUNTER_SMOKE_SCREEN                                         = 430709,
    SPELL_HUNTER_DARK_CHAINS                                          = 430712,
    SPELL_HUNTER_DONT_LOOK_BACK                                       = 450373,
    SPELL_HUNTER_MOMENT_OF_OPPORTUNITY                                = 459488,
    SPELL_HUNTER_KINDLING_FLARE                                       = 459506,
    SPELL_HUNTER_UNNATURAL_CAUSES                                     = 459527,
    SPELL_HUNTER_GO_FOR_THE_THROAT                                    = 459550,
    SPELL_HUNTER_LACERATION                                           = 459552,
    SPELL_HUNTER_THUNDERING_HOOVES                                    = 459693,
    SPELL_HUNTER_HUNTMASTERS_CALL                                     = 459730,
    SPELL_HUNTER_PENETRATING_SHOTS                                    = 459783,
    SPELL_HUNTER_GRENADE_JUGGLER                                      = 459843,
    SPELL_HUNTER_OUTLAND_VENOM                                        = 459939,
    SPELL_HUNTER_KODO_TRANQUILIZER                                    = 459983,
    SPELL_HUNTER_DEVILSAUR_TRANQUILIZER                               = 459991,
    SPELL_HUNTER_WILDFIRE_INFUSION                                    = 460198,
    SPELL_HUNTER_WITHERING_FIRE                                       = 466990,
    SPELL_HUNTER_BLEAK_ARROWS                                         = 467749,
    SPELL_HUNTER_EBON_BOWSTRING                                       = 467897,
    SPELL_HUNTER_BLEAK_POWDER                                         = 467911,
    SPELL_HUNTER_SNAKESKIN_QUIVER                                     = 468695,
    SPELL_HUNTER_SOUL_DRINKER                                         = 469638,
    SPELL_HUNTER_BARBED_SCALES                                        = 469880,
    SPELL_HUNTER_FEATHERED_FRENZY                                     = 470943,
    SPELL_HUNTER_ASPECT_OF_THE_HYDRA                                  = 470945,
    SPELL_HUNTER_HEADSHOT                                             = 471363,
    SPELL_HUNTER_TENSILE_BOWSTRING                                    = 471366,
    SPELL_HUNTER_DIRE_SUMMONS                                         = 472352,
    SPELL_HUNTER_PACK_MENTALITY                                       = 472358,
    SPELL_HUNTER_URSINE_FURY                                          = 472476,
    SPELL_HUNTER_FURY_OF_THE_WYVERN                                   = 472550,
    SPELL_HUNTER_HOGSTRIDER                                           = 472639,
    SPELL_HUNTER_SLICKED_SHOES                                        = 472719,
    SPELL_HUNTER_HORSEHAIR_TETHER                                     = 472729,
    SPELL_HUNTER_STAMPEDE                                             = 472741,
    SPELL_HUNTER_DOUBLE_TAP                                           = 473370,
    SPELL_HUNTER_TARGET_ACQUISITION                                   = 473379,
    SPELL_HUNTER_NO_SCOPE                                             = 473385,
    SPELL_HUNTER_SHRAPNEL_SHOT                                        = 473520,
    SPELL_HUNTER_WINDRUNNER_QUIVER                                    = 473523,
    SPELL_HUNTER_SOLITARY_COMPANION                                   = 474746,
    SPELL_HUNTER_DIRE_CLEAVE                                          = 1217524,
    SPELL_HUNTER_MANHUNTER                                            = 1217788,
    SPELL_HUNTER_SPOTTERS_MARK                                        = 1219616,
    SPELL_HUNTER_WILDSPEAKER                                          = 1232739,
    SPELL_HUNTER_UMBRAL_REACH                                         = 1235397,
    SPELL_HUNTER_TRACK_PETS                                           = 1244920,
    SPELL_HUNTER_TAKEDOWN                                             = 1250646,
    SPELL_HUNTER_FLAMEFANG_PITCH                                      = 1251592,
    SPELL_HUNTER_STRIKE_AS_ONE                                        = 1251717,
    SPELL_HUNTER_TWO_AGAINST_MANY                                     = 1251718,
    SPELL_HUNTER_MONGOOSE_FURY                                        = 1252708,
    SPELL_HUNTER_WALLOP                                               = 1252738,
    SPELL_HUNTER_SHELLSHOCK                                           = 1252931,
    SPELL_HUNTER_WILDFIRE_IMBUEMENT                                   = 1252943,
    SPELL_HUNTER_SIC_EM                                               = 1253137,
    SPELL_HUNTER_SHRAPNEL_BOMB                                        = 1253172,
    SPELL_HUNTER_SENTINEL                                             = 1253599,
    SPELL_HUNTER_LUNAR_STORM                                          = 1253732,
    SPELL_HUNTER_STARGAZER                                            = 1253751,
    SPELL_HUNTER_MOONS_BLESSING                                       = 1253825,
    SPELL_HUNTER_SANCTIFIED_ARMAMENTS                                 = 1253831,
    SPELL_HUNTER_LUNAR_CALLING                                        = 1253852,
    SPELL_HUNTER_SCOUTS_VIGIL                                         = 1253892,
    SPELL_HUNTER_MONGOOSE_ROUNDS                                      = 1253945,
    SPELL_HUNTER_GUTTURAL_ROAR                                        = 1258509,
    SPELL_HUNTER_RAPTOR_SWIPE                                         = 1259003,
    SPELL_HUNTER_RAPTOR_SWIPE_1259017                                 = 1259017,
    SPELL_HUNTER_RAPTOR_SWIPE_1259019                                 = 1259019,
    SPELL_HUNTER_BOOMSTICK                                            = 1261193,
    SPELL_HUNTER_WILDFIRE_SHELLS                                      = 1261229,
    SPELL_HUNTER_LETHAL_CALIBRATION                                   = 1262409,
    SPELL_HUNTER_CORPSECALLER                                         = 1264289,
    SPELL_HUNTER_PACT_OF_THE_HOLLOW                                   = 1264690,
    SPELL_HUNTER_RADIANT_EDGE                                         = 1264903,
    SPELL_HUNTER_TWILIGHT_REQUIEM                                     = 1264904,
    SPELL_HUNTER_HEART_OF_THE_PACK                                    = 1265052,
    SPELL_HUNTER_STALK_AND_STRIKE                                     = 1266069,
    SPELL_HUNTER_COLD_FEET                                            = 1268671,
    SPELL_HUNTER_GUARDIANS_HIDE                                       = 1272094,
    SPELL_HUNTER_BLOODSHED                                            = 1272099,
    SPELL_HUNTER_TWIN_FANGS                                           = 1272139,
    SPELL_HUNTER_PRIMAL_SURGE                                         = 1272154,
    SPELL_HUNTER_NATURES_ALLY                                         = 1273043,
    SPELL_HUNTER_NATURES_ALLY_1273126                                 = 1273126,
    SPELL_HUNTER_TAKE_AIM                                             = 1273128,
    SPELL_HUNTER_TAKE_AIM_1273129                                     = 1273129,
    SPELL_HUNTER_TAKE_AIM_1273132                                     = 1273132,
    SPELL_HUNTER_FOCUS_FIRE                                           = 1277546,
    SPELL_HUNTER_UNLOAD                                               = 1277548,
};

// =====================================================================
// Passive DUMMY — Modifier Buffs (19 spells)
// These passives store modifier values in DUMMY aura effects.
// The values need to be applied to affected spells via HandleProc
// or by modifying spell amounts in CalcAmount handlers.
// =====================================================================

// 76657 - Mastery: Master of Beasts
// Tooltip: "Increases the damage done by your pets by ${$s1}.1% and the damage of your shots and traps by ${$s5}.1%."
class spell_hunter_mastery_master_of_beasts : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff1=190.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_mastery_master_of_beasts::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_mastery_master_of_beasts::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 199921 - Trailblazer
// Tooltip: "Your movement speed is increased by $s2% anytime you have not attacked for ${$s1/1000} sec."
class spell_hunter_trailblazer : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=3000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_trailblazer::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_trailblazer::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 263135 - Mastery: Spirit Bond
// Tooltip: "You and your pet deal $s8% increased damage and take $s6% reduced damage. This bonus is increased by $459722s1% when you"
class spell_hunter_mastery_spirit_bond : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff5=3.0, eff6=25.0, eff7=0.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_mastery_spirit_bond::HandleApply, EFFECT_5, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_mastery_spirit_bond::HandleRemove, EFFECT_5, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_mastery_spirit_bond::HandleApply, EFFECT_6, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_mastery_spirit_bond::HandleRemove, EFFECT_6, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_mastery_spirit_bond::HandleApply, EFFECT_7, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_mastery_spirit_bond::HandleRemove, EFFECT_7, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 378767 - Focused Aim
// Tooltip: "Consuming Precise Shots reduces the cooldown of Aimed Shot by ${$s1/1000}.2 sec."
// SimC: Spell initialization/registration only
class spell_hunter_focused_aim : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=2000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_focused_aim::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_focused_aim::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 378937 - Explosives Expert
// Tooltip: "Wildfire Bomb, Boomstick, and Flamefang Pitch damage increased by $s1%."
class spell_hunter_explosives_expert : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff2=250.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_explosives_expert::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_explosives_expert::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 393933 - War Orders
// Tooltip: "Barbed Shot deals $s2% increased damage, and applying Barbed Shot reduces the cooldown of Kill Command by ${$s3/1000}.1 "
class spell_hunter_war_orders : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff2=3000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_war_orders::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_war_orders::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 424558 - Master Handler
// Tooltip: "Each time Barbed Shot deals damage, the cooldown of Kill Command is reduced by ${$m1/1000}.2 sec."
// SimC: Spell initialization/registration only
class spell_hunter_master_handler : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=500.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_master_handler::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_master_handler::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 459488 - Moment of Opportunity
// Tooltip: "When a trap triggers, gain $1267208s1% increased movement speed for $1267208d."
class spell_hunter_moment_of_opportunity : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff1=3000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_moment_of_opportunity::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_moment_of_opportunity::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 459693 - Thundering Hooves
// Tooltip: "Bestial Wrath causes all active pets to Stomp at $s1% effectiveness. Stomp damage increased by $s2%."
class spell_hunter_thundering_hooves : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=200.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_thundering_hooves::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_thundering_hooves::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 466990 - Withering Fire
// Tooltip: "$?c1[Bestial Wrath][Trueshot] causes you to surrender to darkness, granting you Withering Fire for $?c1[$466991d][the du"
// SimC: Has proc/trigger behavior; Uses effect(s) 2, 3; Buff interaction: bestial_wrath, bulletstorm, double
class spell_hunter_withering_fire : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=0.0, eff1=200.0, eff2=2.0, eff3=50.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_withering_fire::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_withering_fire::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_withering_fire::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_withering_fire::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_withering_fire::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_withering_fire::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_withering_fire::HandleApply, EFFECT_3, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_withering_fire::HandleRemove, EFFECT_3, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 469880 - Barbed Scales
// Tooltip: "Casting Cobra Shot reduces the cooldown of Barbed Shot by ${$s1/1000} sec."
// SimC: Involves resource gain/cost
class spell_hunter_barbed_scales : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=2000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_barbed_scales::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_barbed_scales::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 472358 - Pack Mentality
// Tooltip: "Howl of the Pack Leader increases the damage of your Kill Command by $s1%. Summoning a Beast reduces the cooldown of $?c"
// SimC: Spell initialization/registration only
class spell_hunter_pack_mentality : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=50.0, eff1=4000.0, eff2=6000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_pack_mentality::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_pack_mentality::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_pack_mentality::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_pack_mentality::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_pack_mentality::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_pack_mentality::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 472550 - Fury of the Wyvern
// Tooltip: "Your pet's attacks increase your Wyvern's damage bonus by $471881s1%, up to $s1%. Casting $?c1[Kill Command][Wildfire Bo"
// SimC: Spell initialization/registration only
class spell_hunter_fury_of_the_wyvern : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=10.0, eff1=500.0, eff2=5000.0, eff3=5.0, eff4=10.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_fury_of_the_wyvern::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_fury_of_the_wyvern::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_fury_of_the_wyvern::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_fury_of_the_wyvern::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_fury_of_the_wyvern::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_fury_of_the_wyvern::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_fury_of_the_wyvern::HandleApply, EFFECT_3, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_fury_of_the_wyvern::HandleRemove, EFFECT_3, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_fury_of_the_wyvern::HandleApply, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_fury_of_the_wyvern::HandleRemove, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 472719 - Slicked Shoes
// Tooltip: "When Disengage removes a movement impairing effect, its cooldown is reduced by ${$s1/1000} sec."
class spell_hunter_slicked_shoes : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=4000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_slicked_shoes::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_slicked_shoes::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 473379 - Target Acquisition
// Tooltip: "Consuming Spotter's Mark reduces the cooldown of Aimed Shot by ${$s1/1000}.1 sec."
// SimC: Affects cooldown/recharge timing; Has duration or tick-time behavior
class spell_hunter_target_acquisition : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=1000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_target_acquisition::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_target_acquisition::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1253825 - Moon's Blessing
// Tooltip: "$?c2[Consuming Precise Shots][Consuming Tip of the Spear] has a $s1% increased chance to summon your Sentinel Owl. When "
class spell_hunter_moons_blessing : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff1=2000.0, eff2=4000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_moons_blessing::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_moons_blessing::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_moons_blessing::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_moons_blessing::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1261229 - Wildfire Shells
// Tooltip: "Damaging one or more enemies with your Boomstick reduces the cooldown of Wildfire Bomb by ${$s1/1000}.1 sec."
// SimC: Buff interaction: sentinels_mark, tip_of_the_spear; Debuff interaction: sentinels_mark; Affects cool
class spell_hunter_wildfire_shells : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=2000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_wildfire_shells::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_wildfire_shells::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1268671 - Cold Feet
// Tooltip: "When your Freezing Trap breaks, the victim's movement speed is reduced by $1268673s1% for $1268673d."
class spell_hunter_cold_feet : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=-20.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_cold_feet::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_cold_feet::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1273132 - Take Aim
// Tooltip: "Rapid Fire damage increased by $s1%. Each shot fired from Rapid Fire reduces the cooldown of Aimed Shot by ${$s2/1000}.2"
class spell_hunter_take_aim_1273132 : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff1=500.0, eff2=50.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_take_aim_1273132::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_take_aim_1273132::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_take_aim_1273132::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_take_aim_1273132::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// =====================================================================
// Passive DUMMY — Proc Handlers (10 spells)
// These passives proc on combat events and apply effects.
// =====================================================================

// 260228 - Careful Aim
// Tooltip: "Aimed Shot deals $s3% bonus damage to targets who are above $s1% health."
// ProcMask: 0
class spell_hunter_careful_aim : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=70.0, eff1=0.0, eff3=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_careful_aim::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_careful_aim::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_careful_aim::HandleProc, EFFECT_3, SPELL_AURA_DUMMY);
    }
};

// 460198 - Wildfire Infusion
// Tooltip: "Kill Command damage increased by $s2%. Kill Command reduces the cooldown of Wildfire Bomb by ${$s1/1000}.1 sec."
// ProcMask: 0
class spell_hunter_wildfire_infusion : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=1000.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_wildfire_infusion::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// 470943 - Feathered Frenzy
// Tooltip: "Trueshot sends your Spotting Eagle into a frenzy, instantly applying Spotter's Mark to your target.  During Trueshot, yo"
// ProcMask: 0
// SimC: Spell initialization/registration only
class spell_hunter_feathered_frenzy : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_feathered_frenzy::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// 473520 - Shrapnel Shot
// Tooltip: "Casting Volley has a $s1% chance to grant Lock and Load."
// ProcMask: 0
// SimC: Spell initialization/registration only
class spell_hunter_shrapnel_shot : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_shrapnel_shot::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// 473523 - Windrunner Quiver
// Tooltip: "Precise Shots can now stack up to ${1+$s1} times, but its damage bonus is reduced by ${-$s3}%. Casting Aimed Shot has a "
// ProcMask: 0
class spell_hunter_windrunner_quiver : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff1=90.0, eff4=0.0, eff5=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_windrunner_quiver::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_windrunner_quiver::HandleProc, EFFECT_4, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_windrunner_quiver::HandleProc, EFFECT_5, SPELL_AURA_DUMMY);
    }
};

// 1217524 - Dire Cleave
// Tooltip: "When summoned, Dire Beasts gain Beast Cleave at $s1% effectiveness for ${$s2/1000}.1 sec."
// ProcMask: 0
// SimC: Spell initialization/registration only
class spell_hunter_dire_cleave : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0, eff1=8000.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_dire_cleave::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_dire_cleave::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 1259019 - Raptor Swipe
// Tooltip: "Raptor Strike now has a $s1% chance to upgrade itself to a Raptor Swipe. Raptor Swipes that benefit from Tip of the Spea"
// ProcMask: 0
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 2; Buff interaction: raptor_swipe,
class spell_hunter_raptor_swipe_1259019 : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0, eff1=300.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_raptor_swipe_1259019::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_raptor_swipe_1259019::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 1266069 - Stalk and Strike
// Tooltip: "Throwing your Moonlight Chakram $?c2[grants you Lock and Load][reduces the cooldown of Wildfire Bomb by ${$s1/1000} sec]"
// ProcMask: 0
// SimC: Spell initialization/registration only
class spell_hunter_stalk_and_strike : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=10000.0, eff1=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_stalk_and_strike::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_stalk_and_strike::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 1272094 - Guardian's Hide
// Tooltip: "Your pet protects you at all times, reducing the damage you take by $s1%. Your pet receives $s2% of the damage it mitiga"
// ProcMask: 664232
class spell_hunter_guardians_hide : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff1=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_guardians_hide::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 1277548 - Unload
// Tooltip: "When Rapid Fire begins and finishes channeling, it releases an Arcane Shot at $s1% effectiveness. If your target is $?a4"
// ProcMask: 0
// SimC: Buff interaction: bulletstorm, double_tap, precise_shots, withering_fire; AoE or multi-target behavi
class spell_hunter_unload : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_unload::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// =====================================================================
// Passive DUMMY — Trigger Effects (5 spells)
// =====================================================================

// 459527 - Unnatural Causes
// Tooltip: "Your damage over time effects deal $s1% increased damage. This effect is increased by $s2% on targets below $s3% health."
class spell_hunter_unnatural_causes : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Trigger spell on proc event
        // bp=eff0=10.0, eff1=50.0, eff2=20.0
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_unnatural_causes::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_unnatural_causes::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_unnatural_causes::HandleProc, EFFECT_2, SPELL_AURA_DUMMY);
    }
};

// 459730 - Huntmaster's Call
// Tooltip: "Summoning a Dire Beast $459731u times sounds the Horn of Valor, summoning either Hati or Fenryr to battle. |cFFFFFFFFHat"
class spell_hunter_huntmasters_call : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Trigger spell on proc event
        // bp=eff0=0.0
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_huntmasters_call::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// 472352 - Dire Summons
// Tooltip: "Kill Command reduces the cooldown of Howl of the Pack Leader by $?c1[${$s1/1000}.1][${$s2/1000}.1] sec. $?s259387[Mongoo"
class spell_hunter_dire_summons : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Trigger spell on proc event
        // bp=eff0=1000.0, eff1=1500.0, eff2=1000.0, eff3=1000.0
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_dire_summons::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_dire_summons::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_dire_summons::HandleProc, EFFECT_2, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_dire_summons::HandleProc, EFFECT_3, SPELL_AURA_DUMMY);
    }
};

// 1253852 - Lunar Calling
// Tooltip: "$?c2[Feathered Frenzy further increases your chance to summon your Sentinel Owl during Trueshot by $s1%][Takedown summon"
class spell_hunter_lunar_calling : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Trigger spell on proc event
        // bp=eff0=10.0, eff1=10.0
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_lunar_calling::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_hunter_lunar_calling::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 1264289 - Corpsecaller
// Tooltip: "$?c1[When summoning a Dire Beast, you have a $s1% chance to instead summon a Dark Hound that deals significantly increas"
class spell_hunter_corpsecaller : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Trigger spell on proc event
        // bp=eff0=10.0
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_hunter_corpsecaller::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// =====================================================================
// Passive DUMMY — Other (78 spells)
// These need individual research to determine handler type.
// =====================================================================

// 257891 - Spitting Cobra — bp=eff0=10.0
// "When Bestial Wrath ends, summon a Spitting Cobra to aid you in combat for $19440"
class spell_hunter_spitting_cobra : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 260241 - Hydra's Bite — bp=eff0=0.0, eff2=2.0
// "When Aimed Shot strikes an enemy affected with your Serpent Sting, it spreads Se"
class spell_hunter_hydras_bite : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 260248 - Bloodseeker — bp=eff0=10.0
// "You and your pet gain $260249s1% attack speed for every bleeding enemy within $s"
class spell_hunter_bloodseeker : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 260309 - Master Marksman — bp=eff0=10.0
// "Your ranged ability critical strikes cause the target to bleed for an additional"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Reads percentage value from effect;
class spell_hunter_master_marksman : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 260331 - Birds of Prey — bp=eff0=3.0
// "Kill Shot strikes up to $s1 additional targets while Coordinated Assault is acti"
class spell_hunter_birds_of_prey : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 260393 - Lethal Shots — bp=eff0=50.0
// "$?s342049[Chimaera Shot][Arcane Shot] and Multi-Shot have a $h% chance to reduce"
class spell_hunter_lethal_shots : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 268501 - Viper's Venom — bp=eff0=15.0
// "Raptor Strike and Mongoose Bite damage increased by $s2%. Raptor Strike and Mong"
class spell_hunter_vipers_venom : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 321468 - Binding Shackles — bp=eff0=10.0
// "Targets stunned by Binding Shot, knocked back by High Explosive Trap, knocked up"
class spell_hunter_binding_shackles : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 343244 - Disruptive Rounds — bp=eff0=0.0
// "When $?c3[Muzzle][Counter Shot] interrupts a cast, gain $459976s1 Focus."
class spell_hunter_disruptive_rounds : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 343248 - Deathblow — bp=eff0=10.0, eff1=0.0
// "$?c2[Aimed Shot][Kill Command] has a $?c1[$s2]?c2[$s1][$s3]% chance to grant Dea"
// SimC: Has proc/trigger behavior; Buff interaction: ok; Affects cooldown/recharge timin
class spell_hunter_deathblow : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 378207 - Kill Cleave — bp=eff0=40.0
// "While Beast Cleave is active, Kill Command now also strikes nearby enemies for $"
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1; Reads perce
class spell_hunter_kill_cleave : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 378442 - Wild Instincts — bp=eff0=2.0
// "When your primary pet uses Stomp, apply Barbed Shot to a target hit by that Stom"
// SimC: Pet/guardian interaction; Referenced in SimC (context needs manual review)
class spell_hunter_wild_instincts : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 378743 - Dire Command — bp=eff0=20.0
// "Kill Command has a $s1% chance to also summon a Dire Beast to attack your target"
// SimC: Involves resource gain/cost; Referenced in SimC (context needs manual review)
class spell_hunter_dire_command : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 385539 - Rejuvenating Wind — bp=eff0=12.0
// "Exhilaration now also heals you for an additional ${$s1}.1% of your maximum heal"
class spell_hunter_rejuvenating_wind : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 385810 - Dire Frenzy — bp=eff1=10.0
// "Dire Beast lasts an additional ${$m1/1000} sec and deals $s2% increased damage."
class spell_hunter_dire_frenzy : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 386870 - Brutal Companion — bp=eff0=25.0, eff1=50.0
// "Barbed Shot has a $s1% chance to cause your pet to use its special attack and de"
// SimC: Has proc/trigger behavior; Uses effect(s) 2; Reads percentage value from effect
class spell_hunter_brutal_companion : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 389019 - Bulletstorm — bp=eff0=2.0
// "Damage from Rapid Fire increases the damage of Aimed Shot by $389020s1% for $389"
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 2, 4; Reads pe
class spell_hunter_bulletstorm : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 391559 - Surging Shots — bp=eff2=15.0
// "Rapid Fire deals $s1% additional damage, and Aimed Shot has a $s3% chance to res"
class spell_hunter_surging_shots : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 392053 - Piercing Fangs — bp=eff0=30.0
// "While Bestial Wrath is active, your pet's critical damage dealt is increased by "
// SimC: Modifies damage output; Referenced in SimC (context needs manual review)
class spell_hunter_piercing_fangs : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 400456 - Salvo — bp=eff0=2.0
// "Volley now also applies Explosive Shot to up to $s1 $Ltarget:targets; hit. $@spe"
// SimC: Affects cooldown/recharge timing; Has duration or tick-time behavior; Aura overr
class spell_hunter_salvo : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 407404 - In the Rhythm — bp=eff0=25.0
// "When Rapid Fire finishes channeling, the time between your Auto Shots is reduced"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Referenced in SimC (context needs m
class spell_hunter_in_the_rhythm : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 430709 - Smoke Screen — bp=eff0=3.0, eff1=50.0
// "Exhilaration grants you $s1 sec of Survival of the Fittest. Survival of the Fitt"
class spell_hunter_smoke_screen : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 430712 - Dark Chains — bp=eff0=8.0
// "While in combat, Disengage will chain the closest target to the ground, causing "
class spell_hunter_dark_chains : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 450373 - Don't Look Back — bp=eff0=10.0, eff1=10.0
// "Consuming Sentinel's Mark grants you an absorb shield equal to ${$s1}.1% of your"
// SimC: Spell initialization/registration only
class spell_hunter_dont_look_back : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 459506 - Kindling Flare — bp=eff0=50.0
// "Flare's radius is increased by $s1%."
class spell_hunter_kindling_flare : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 459552 - Laceration — bp=eff0=0.0
// "When your pet attacks critically strike, they cause their target to bleed for $4"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Reads percentage value from effect;
class spell_hunter_laceration : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 459843 - Grenade Juggler — bp=eff0=1.0
// "Flamefang Pitch gains $s2 additional $Lcharge:charges;.  Throwing your Flamefang"
class spell_hunter_grenade_juggler : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 459939 - Outland Venom — bp=eff0=0.0
// "Each damage over time effect on a target increases the critical strike damage th"
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1; Reads perce
class spell_hunter_outland_venom : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 459983 - Kodo Tranquilizer — bp=eff0=1.0, eff1=0.0, eff2=2.0, eff3=0.0
// "Tranquilizing Shot removes $s1 additional Magic effect from up to $s3 nearby tar"
class spell_hunter_kodo_tranquilizer : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
        // TODO: Determine handler type for DUMMY effect 3
    }
};

// 459991 - Devilsaur Tranquilizer — bp=eff0=5.0
// "If Tranquilizing Shot removes only an Enrage effect, its cooldown is reduced by "
class spell_hunter_devilsaur_tranquilizer : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 467749 - Bleak Arrows — bp=eff0=20.0, eff1=8.0
// "Your auto shot now deals Shadow damage, allowing it to bypass armor. Auto shot d"
class spell_hunter_bleak_arrows : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 467897 - Ebon Bowstring — bp=eff0=15.0
// "Casting Black Arrow has a $s1% chance to grant Deathblow. $@spellicon378770 $@sp"
// SimC: Spell initialization/registration only
class spell_hunter_ebon_bowstring : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 467911 - Bleak Powder — bp=eff0=0.0, eff1=8.0
// "Black Arrow now explodes in a cloud of shadow and sulfur on impact, dealing $?c1"
// SimC: Affects cooldown/recharge timing; Has duration or tick-time behavior; Aura overr
class spell_hunter_bleak_powder : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 468695 - Snakeskin Quiver — bp=eff0=15.0
// "Your auto shot has a $s1% chance to also fire a Cobra Shot at your target."
// SimC: Involves resource gain/cost; Referenced in SimC (context needs manual review)
class spell_hunter_snakeskin_quiver : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 469638 - Soul Drinker — bp=eff0=20.0, eff1=50.0
// "$?c1[Kill Command has a $s1% chance and Barbed Shot has a $s2% chance to grant D"
class spell_hunter_soul_drinker : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 470945 - Aspect of the Hydra — bp=eff0=65.0, eff1=1.0
// "Aimed Shot, Rapid Fire, and Arcane Shot now hit $s2 additional $Ltarget:targets;"
// SimC: Spell initialization/registration only
class spell_hunter_aspect_of_the_hydra : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 471363 - Headshot — bp=eff0=2.0
// "Damage from $?a466932[Black Arrow][Kill Shot] increases the damage your target r"
// SimC: Has proc/trigger behavior; Buff interaction: bullseye; Affects cooldown/recharge
class spell_hunter_headshot : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 471366 - Tensile Bowstring — bp=eff0=40.0, eff1=60.0
// "Trueshot now also reduces the cast time of Aimed Shot by $s1% and reduces the Fo"
// SimC: Spell initialization/registration only
class spell_hunter_tensile_bowstring : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 472476 - Ursine Fury — bp=eff0=2.0
// "When your Bear is summoned, it is joined by $s1 Dire $LBeast:Beasts;."
// SimC: Spell initialization/registration only
class spell_hunter_ursine_fury : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 472639 - Hogstrider — bp=eff0=25.0
// "When your Boar deals damage, the damage of your next $?c1[Cobra Shot][Hatchet To"
// SimC: Modifies damage output; Uses effect(s) 1, 2, 3; Reads percentage value from effe
class spell_hunter_hogstrider : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 472729 - Horsehair Tether — bp=eff0=0.0
// "When an enemy is stunned by Binding Shot, it is dragged to Binding Shot's center"
class spell_hunter_horsehair_tether : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 472741 - Stampede! — bp=eff0=9.0, eff1=8.0
// "Casting $?c1[Bestial Wrath][Takedown] grants Howl of the Pack Leader and causes "
// SimC: Has proc/trigger behavior; Referenced in SimC (context needs manual review)
class spell_hunter_stampede : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 473370 - Double Tap — bp=eff0=5.0, eff1=80.0, eff2=80.0
// "Casting Trueshot or Volley grants Double Tap, causing your next Aimed Shot to fi"
// SimC: Has proc/trigger behavior; Uses effect(s) 1, 3; Reads percentage value from effe
class spell_hunter_double_tap : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 473385 - No Scope — bp=eff0=15.0
// "Rapid Fire grants Precise Shots."
// SimC: Spell initialization/registration only
class spell_hunter_no_scope : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 474746 - Solitary Companion — bp=eff0=35.0
// "Your pet damage is increased by $s1% and your pet is $474751s1% larger."
// SimC: Has proc/trigger behavior; Modifies damage output
class spell_hunter_solitary_companion : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1217788 - Manhunter — bp=eff0=0.0
// "Damaging a player with Aimed Shot applies Mortal Wounds, reducing the healing th"
class spell_hunter_manhunter : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1219616 - Spotter's Mark — bp=eff0=30.0
// "|cFFFFFFFFReplaces Call Pet|r Gain the aid of a Spotting Eagle.  Damaging an ene"
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1, 2, 3; Reads
class spell_hunter_spotters_mark : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1232739 - Wildspeaker — bp=eff0=30.0, eff1=15.0
// "Dire Beasts will now obey your Kill Command, dealing its damage at $s1% effectiv"
// SimC: Spell initialization/registration only
class spell_hunter_wildspeaker : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1235397 - Umbral Reach — bp=eff0=0.0, eff1=2.0
// "Bleak Powder now applies Black Arrow's periodic effect to all enemies it damages"
// SimC: Spell initialization/registration only
class spell_hunter_umbral_reach : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1244920 - Track Pets — bp=eff0=0.0
// "Shows the location of all nearby wild pets on the minimap."
class spell_hunter_track_pets : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1251717 - Strike as One — bp=eff0=15.0
// "Consuming Tip of the Spear provokes your pet to attack your target, dealing $125"
class spell_hunter_strike_as_one : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1251718 - Two Against Many — bp=eff1=10.0
// "Strike as One damages $s1 additional enemies and its damage is increased by $s2%"
class spell_hunter_two_against_many : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1252708 - Mongoose Fury — bp=eff0=0.0
// "Raptor Strike increases the damage of Raptor Strike by $259388s1% for $259388d. "
// SimC: Has proc/trigger behavior; Uses effect(s) 1, 2; Reads percentage value from effe
class spell_hunter_mongoose_fury : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1252738 - Wallop — bp=eff0=20.0
// "Gaining a stack of Mongoose Fury has a $s1% chance to increase the damage of you"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Reads percentage value from effect;
class spell_hunter_wallop : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1252931 - Shellshock — bp=eff0=40.0, eff1=5.0
// "Your Boomstick's damage is increased by $s1% when striking a single target. Each"
// SimC: Spell initialization/registration only
class spell_hunter_shellshock : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1252943 - Wildfire Imbuement — bp=eff0=15.0
// "Throwing your Flamefang Pitch imbues your weapon with flame, causing you and you"
// SimC: Has proc/trigger behavior; Participates in stat scaling; AoE or multi-target beh
class spell_hunter_wildfire_imbuement : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1253137 - Sic 'Em — bp=eff0=5.0
// "When Kill Command critically strikes, it bleeds its target for an additional $12"
// SimC: Uses effect(s) 2; Reads percentage value from effect; Aura override or transform
class spell_hunter_sic_em : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1253172 - Shrapnel Bomb — bp=eff0=5.0
// "Wildfire Bomb's periodic effect is now a Bleed."
// SimC: Spell initialization/registration only
class spell_hunter_shrapnel_bomb : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1253599 - Sentinel — bp=eff0=10.0
// "$?c3[Consuming Tip of the Spear has a $s2% chance to summon the aid of a Sentine"
// SimC: Spell initialization/registration only
class spell_hunter_sentinel : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1253732 - Lunar Storm — bp=eff0=4.0, eff1=10.0
// "When Sentinel's Mark is consumed, it summons a barrage of $s1 lunar missiles, ea"
// SimC: Uses effect(s) 1; AoE or multi-target behavior; Referenced in SimC (context need
class spell_hunter_lunar_storm : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1253751 - Stargazer — bp=eff0=3.0, eff1=20.0
// "$?c2[Consuming Precise Shots][Consuming Tip of the Spear] grants $1253750s1% inc"
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1, 4; Reads pe
class spell_hunter_stargazer : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1253831 - Sanctified Armaments — bp=eff0=25.0, eff1=15.0
// "An additional $?c2[$s1][$s2]% of $?c2[Rapid Fire][Raptor Strike]'s damage is dea"
// SimC: Uses effect(s) 1; Involves resource gain/cost; Aura override or transformation b
class spell_hunter_sanctified_armaments : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1253892 - Scout's Vigil — bp=eff1=25.0
// "Enemy detection radius reduced by $s1 yds. While in Camouflage, your stealth det"
class spell_hunter_scouts_vigil : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1253945 - Mongoose Rounds — bp=eff0=1.0
// "Damaging one or more enemies with your Boomstick grants you $s1 $Lstack:stacks; "
// SimC: Spell initialization/registration only
class spell_hunter_mongoose_rounds : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1258509 - Guttural Roar — bp=eff0=4.0
// "Intimidation now also stuns nearby enemies for ${$1258508d}.1 sec."
class spell_hunter_guttural_roar : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1259003 - Raptor Swipe — bp=eff0=25.0, eff1=5.0, eff2=15.0
// "Raptor Strike has a $s1% chance to upgrade itself to a Raptor Swipe, dealing $12"
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 2; Buff intera
class spell_hunter_raptor_swipe_1259003 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 1259017 - Raptor Swipe — bp=eff1=25.0
// "Raptor Strike, Wildfire Bomb, and Raptor Swipe damage increased by $s1%. Raptor "
class spell_hunter_raptor_swipe_1259017 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1264690 - Pact of the Hollow — bp=eff0=8.0, eff1=8.0
// "$?c1[Kill Command causes your Dark Hound to Shadow Thrash, dealing $1264485s1 Sh"
// SimC: Spell initialization/registration only
class spell_hunter_pact_of_the_hollow : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1264903 - Radiant Edge — bp=eff0=15.0
// "Your Moonlight Chakram deals $1264949s3% increased damage each time it bounces."
// SimC: Spell initialization/registration only
class spell_hunter_radiant_edge : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1264904 - Twilight Requiem — bp=eff0=8.0
// "When your Moonlight Chakram expires, it summons an explosion of moonlight, deali"
// SimC: AoE or multi-target behavior; Referenced in SimC (context needs manual review)
class spell_hunter_twilight_requiem : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1265052 - Heart of the Pack — bp=eff0=5.0
// "Summoning a Dire Beast grants ${$s1/10}.2% haste for $1282747d."
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Reads percentage value from effect
class spell_hunter_heart_of_the_pack : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1272099 - Bloodshed — bp=eff0=10.0
// "Bestial Wrath provokes your pets to tear into your target, causing your target t"
// SimC: Pet/guardian interaction; Referenced in SimC (context needs manual review)
class spell_hunter_bloodshed : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1272139 - Twin Fangs — bp=eff0=3.0
// "Takedown grants $s1 stacks of Tip of the Spear."
// SimC: Buff interaction: howl_of_the_pack_leader_bear, howl_of_the_pack_leader_boar, ho
class spell_hunter_twin_fangs : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1272154 - Primal Surge — bp=eff0=1.0
// "Kill Command grants $s1 additional $Lstack:stacks; of Tip of the Spear. Tip of t"
class spell_hunter_primal_surge : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1273043 - Nature's Ally — bp=eff0=25.0
// "Bestial Wrath summons an Animal Companion from your Stable to fight alongside yo"
// SimC: Uses effect(s) 1; Reads percentage value from effect; Buff interaction: bestial_
class spell_hunter_natures_ally_1273043 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1273126 - Nature's Ally — bp=eff1=20.0
// "Barbed Shot and Cobra Shot damage increased by $s1%. Barbed Shot, Cobra Shot, an"
class spell_hunter_natures_ally_1273126 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1273128 - Take Aim — bp=eff1=5.0
// "Aimed Shot always critically strikes."
class spell_hunter_take_aim_1273128 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1277546 - Focus Fire — bp=eff0=20.0
// "When Surging Shots resets the cooldown of Rapid Fire, the damage of your next Ra"
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1; Reads perce
class spell_hunter_focus_fire : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// =====================================================================
// PERIODIC_DUMMY — Tick Handlers (7 spells)
// =====================================================================

// 19574 - Bestial Wrath
// "Sends you and your pet into a rage, instantly dealing $344572s1 Physical damage to its target, and increasing all damage"
class spell_hunter_bestial_wrath : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_hunter_bestial_wrath::HandlePeriodic, EFFECT_2, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 131894 - A Murder of Crows
// "Summons a flock of crows to attack your target, dealing ${$131900s1*$d} Physical damage over $d."
class spell_hunter_a_murder_of_crows : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_hunter_a_murder_of_crows::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 212431 - Explosive Shot
// "Fires an explosive shot at your target. After $t1 sec, the shot will explode, dealing $212680s1 Fire damage to all enemi"
class spell_hunter_explosive_shot : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_hunter_explosive_shot::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 260243 - Volley
// "Rain a volley of arrows down over $d, dealing up to ${$260247s1*12} Physical damage to any enemy in the area, and gain t"
class spell_hunter_volley : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_hunter_volley::HandlePeriodic, EFFECT_1, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 459550 - Go for the Throat
// "Kill Command deals increased critical strike damage equal to $s2% of your critical strike chance."
class spell_hunter_go_for_the_throat : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_hunter_go_for_the_throat::HandlePeriodic, EFFECT_1, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 459783 - Penetrating Shots
// "Gain critical strike damage equal to $s2% of your critical strike chance."
class spell_hunter_penetrating_shots : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_hunter_penetrating_shots::HandlePeriodic, EFFECT_1, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 1273129 - Take Aim
// "Aimed Shot's critical strike damage is increased by $s4% of your critical strike chance. The damage of your other ranged"
class spell_hunter_take_aim_1273129 : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_hunter_take_aim_1273129::HandlePeriodic, EFFECT_3, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// =====================================================================
// Active DUMMY — HandleDummy (8 spells)
// =====================================================================

// 6197 - Eagle Eye
// "Changes your viewpoint to the targeted location for $d. Only usable outdoors."
class spell_hunter_eagle_eye : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_eagle_eye::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_eagle_eye::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 53480 - Roar of Sacrifice
// "Instructs your pet to protect a friendly target, reducing their damage taken by $s1%, but $s2% of all damage taken by th"
class spell_hunter_roar_of_sacrifice : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_roar_of_sacrifice::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_roar_of_sacrifice::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_roar_of_sacrifice::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_roar_of_sacrifice::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 199483 - Camouflage
// "You and your pet blend into the surroundings and gain stealth for $d. While camouflaged, you will heal for $s4% of maxim"
class spell_hunter_camouflage : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_camouflage::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_camouflage::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_camouflage::HandleApply, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_camouflage::HandleRemove, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 265896 - Terms of Engagement
// "$@spelldesc265895"
class spell_hunter_terms_of_engagement : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_terms_of_engagement::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_terms_of_engagement::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 288613 - Trueshot
// "Increases your critical strike chance by $s3% and critical strike damage by $s4% for $d. $@spellicon19434 $@spellname194"
class spell_hunter_trueshot : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_trueshot::HandleApply, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_trueshot::HandleRemove, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 321297 - Eyes of the Beast
// "Take direct control of your pet and see through its eyes for $d."
class spell_hunter_eyes_of_the_beast : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_eyes_of_the_beast::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_eyes_of_the_beast::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1250646 - Takedown
// "You and your pet leap to your target and strike as one, dealing ${$1253862s1+$1253859s1} Physical damage$?a1256938[ to y"
class spell_hunter_takedown : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_takedown::HandleApply, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_takedown::HandleRemove, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1261193 - Boomstick
// "Unload a series of ${($d/$t1)+1} shotgun blasts $s3 yds in front of you, dealing ${$1261215s1*4} Physical damage over $d"
class spell_hunter_boomstick : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_boomstick::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_boomstick::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_hunter_boomstick::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_hunter_boomstick::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// =====================================================================
// Proc Trigger Spells — Primarily need spell_proc SQL (2 spells)
// Some may also need C++ CheckProc/OnProc handlers
// =====================================================================

// 199532 - Killer Cobra — needs spell_proc SQL entry + possibly C++ proc filter
class spell_hunter_killer_cobra : public AuraScript
{
    bool CheckProc(ProcEventInfo& eventInfo)
    {
        // TODO: Validate proc conditions
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
    }

    void Register() override
    {
        DoCheckProc += AuraCheckProcFn(spell_hunter_killer_cobra::CheckProc);
        OnEffectProc += AuraEffectProcFn(spell_hunter_killer_cobra::HandleProc, EFFECT_0, SPELL_AURA_PROC_TRIGGER_SPELL);
    }
};

// 1262409 - Lethal Calibration — needs spell_proc SQL entry + possibly C++ proc filter
class spell_hunter_lethal_calibration : public AuraScript
{
    bool CheckProc(ProcEventInfo& eventInfo)
    {
        // TODO: Validate proc conditions
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
    }

    void Register() override
    {
        DoCheckProc += AuraCheckProcFn(spell_hunter_lethal_calibration::CheckProc);
        OnEffectProc += AuraEffectProcFn(spell_hunter_lethal_calibration::HandleProc, EFFECT_0, SPELL_AURA_PROC_TRIGGER_SPELL);
    }
};

// =====================================================================
// Script Registration
// =====================================================================

void AddSC_hunter_spell_audit()
{
    RegisterSpellScript(spell_hunter_mastery_master_of_beasts);
    RegisterSpellScript(spell_hunter_trailblazer);
    RegisterSpellScript(spell_hunter_mastery_spirit_bond);
    RegisterSpellScript(spell_hunter_focused_aim);
    RegisterSpellScript(spell_hunter_explosives_expert);
    RegisterSpellScript(spell_hunter_war_orders);
    RegisterSpellScript(spell_hunter_master_handler);
    RegisterSpellScript(spell_hunter_moment_of_opportunity);
    RegisterSpellScript(spell_hunter_thundering_hooves);
    RegisterSpellScript(spell_hunter_withering_fire);
    RegisterSpellScript(spell_hunter_barbed_scales);
    RegisterSpellScript(spell_hunter_pack_mentality);
    RegisterSpellScript(spell_hunter_fury_of_the_wyvern);
    RegisterSpellScript(spell_hunter_slicked_shoes);
    RegisterSpellScript(spell_hunter_target_acquisition);
    RegisterSpellScript(spell_hunter_moons_blessing);
    RegisterSpellScript(spell_hunter_wildfire_shells);
    RegisterSpellScript(spell_hunter_cold_feet);
    RegisterSpellScript(spell_hunter_take_aim_1273132);
    RegisterSpellScript(spell_hunter_careful_aim);
    RegisterSpellScript(spell_hunter_wildfire_infusion);
    RegisterSpellScript(spell_hunter_feathered_frenzy);
    RegisterSpellScript(spell_hunter_shrapnel_shot);
    RegisterSpellScript(spell_hunter_windrunner_quiver);
    RegisterSpellScript(spell_hunter_dire_cleave);
    RegisterSpellScript(spell_hunter_raptor_swipe_1259019);
    RegisterSpellScript(spell_hunter_stalk_and_strike);
    RegisterSpellScript(spell_hunter_guardians_hide);
    RegisterSpellScript(spell_hunter_unload);
    RegisterSpellScript(spell_hunter_unnatural_causes);
    RegisterSpellScript(spell_hunter_huntmasters_call);
    RegisterSpellScript(spell_hunter_dire_summons);
    RegisterSpellScript(spell_hunter_lunar_calling);
    RegisterSpellScript(spell_hunter_corpsecaller);
    RegisterSpellScript(spell_hunter_spitting_cobra);
    RegisterSpellScript(spell_hunter_hydras_bite);
    RegisterSpellScript(spell_hunter_bloodseeker);
    RegisterSpellScript(spell_hunter_master_marksman);
    RegisterSpellScript(spell_hunter_birds_of_prey);
    RegisterSpellScript(spell_hunter_lethal_shots);
    RegisterSpellScript(spell_hunter_vipers_venom);
    RegisterSpellScript(spell_hunter_binding_shackles);
    RegisterSpellScript(spell_hunter_disruptive_rounds);
    RegisterSpellScript(spell_hunter_deathblow);
    RegisterSpellScript(spell_hunter_kill_cleave);
    RegisterSpellScript(spell_hunter_wild_instincts);
    RegisterSpellScript(spell_hunter_dire_command);
    RegisterSpellScript(spell_hunter_rejuvenating_wind);
    RegisterSpellScript(spell_hunter_dire_frenzy);
    RegisterSpellScript(spell_hunter_brutal_companion);
    RegisterSpellScript(spell_hunter_bulletstorm);
    RegisterSpellScript(spell_hunter_surging_shots);
    RegisterSpellScript(spell_hunter_piercing_fangs);
    RegisterSpellScript(spell_hunter_salvo);
    RegisterSpellScript(spell_hunter_in_the_rhythm);
    RegisterSpellScript(spell_hunter_smoke_screen);
    RegisterSpellScript(spell_hunter_dark_chains);
    RegisterSpellScript(spell_hunter_dont_look_back);
    RegisterSpellScript(spell_hunter_kindling_flare);
    RegisterSpellScript(spell_hunter_laceration);
    RegisterSpellScript(spell_hunter_grenade_juggler);
    RegisterSpellScript(spell_hunter_outland_venom);
    RegisterSpellScript(spell_hunter_kodo_tranquilizer);
    RegisterSpellScript(spell_hunter_devilsaur_tranquilizer);
    RegisterSpellScript(spell_hunter_bleak_arrows);
    RegisterSpellScript(spell_hunter_ebon_bowstring);
    RegisterSpellScript(spell_hunter_bleak_powder);
    RegisterSpellScript(spell_hunter_snakeskin_quiver);
    RegisterSpellScript(spell_hunter_soul_drinker);
    RegisterSpellScript(spell_hunter_aspect_of_the_hydra);
    RegisterSpellScript(spell_hunter_headshot);
    RegisterSpellScript(spell_hunter_tensile_bowstring);
    RegisterSpellScript(spell_hunter_ursine_fury);
    RegisterSpellScript(spell_hunter_hogstrider);
    RegisterSpellScript(spell_hunter_horsehair_tether);
    RegisterSpellScript(spell_hunter_stampede);
    RegisterSpellScript(spell_hunter_double_tap);
    RegisterSpellScript(spell_hunter_no_scope);
    RegisterSpellScript(spell_hunter_solitary_companion);
    RegisterSpellScript(spell_hunter_manhunter);
    RegisterSpellScript(spell_hunter_spotters_mark);
    RegisterSpellScript(spell_hunter_wildspeaker);
    RegisterSpellScript(spell_hunter_umbral_reach);
    RegisterSpellScript(spell_hunter_track_pets);
    RegisterSpellScript(spell_hunter_strike_as_one);
    RegisterSpellScript(spell_hunter_two_against_many);
    RegisterSpellScript(spell_hunter_mongoose_fury);
    RegisterSpellScript(spell_hunter_wallop);
    RegisterSpellScript(spell_hunter_shellshock);
    RegisterSpellScript(spell_hunter_wildfire_imbuement);
    RegisterSpellScript(spell_hunter_sic_em);
    RegisterSpellScript(spell_hunter_shrapnel_bomb);
    RegisterSpellScript(spell_hunter_sentinel);
    RegisterSpellScript(spell_hunter_lunar_storm);
    RegisterSpellScript(spell_hunter_stargazer);
    RegisterSpellScript(spell_hunter_sanctified_armaments);
    RegisterSpellScript(spell_hunter_scouts_vigil);
    RegisterSpellScript(spell_hunter_mongoose_rounds);
    RegisterSpellScript(spell_hunter_guttural_roar);
    RegisterSpellScript(spell_hunter_raptor_swipe_1259003);
    RegisterSpellScript(spell_hunter_raptor_swipe_1259017);
    RegisterSpellScript(spell_hunter_pact_of_the_hollow);
    RegisterSpellScript(spell_hunter_radiant_edge);
    RegisterSpellScript(spell_hunter_twilight_requiem);
    RegisterSpellScript(spell_hunter_heart_of_the_pack);
    RegisterSpellScript(spell_hunter_bloodshed);
    RegisterSpellScript(spell_hunter_twin_fangs);
    RegisterSpellScript(spell_hunter_primal_surge);
    RegisterSpellScript(spell_hunter_natures_ally_1273043);
    RegisterSpellScript(spell_hunter_natures_ally_1273126);
    RegisterSpellScript(spell_hunter_take_aim_1273128);
    RegisterSpellScript(spell_hunter_focus_fire);
    RegisterSpellScript(spell_hunter_bestial_wrath);
    RegisterSpellScript(spell_hunter_a_murder_of_crows);
    RegisterSpellScript(spell_hunter_explosive_shot);
    RegisterSpellScript(spell_hunter_volley);
    RegisterSpellScript(spell_hunter_go_for_the_throat);
    RegisterSpellScript(spell_hunter_penetrating_shots);
    RegisterSpellScript(spell_hunter_take_aim_1273129);
    RegisterSpellScript(spell_hunter_eagle_eye);
    RegisterSpellScript(spell_hunter_roar_of_sacrifice);
    RegisterSpellScript(spell_hunter_camouflage);
    RegisterSpellScript(spell_hunter_terms_of_engagement);
    RegisterSpellScript(spell_hunter_trueshot);
    RegisterSpellScript(spell_hunter_eyes_of_the_beast);
    RegisterSpellScript(spell_hunter_takedown);
    RegisterSpellScript(spell_hunter_boomstick);
    RegisterSpellScript(spell_hunter_killer_cobra);
    RegisterSpellScript(spell_hunter_lethal_calibration);
}
