/*
 * Generated spell scripts for Mage
 * Auto-generated by generate_spell_fixes.py on 2026-03-07
 * Based on spell audit classification of YELLOW/RED spells
 *
 * These scripts handle passive DUMMY aura value consumption,
 * PERIODIC_DUMMY tick behavior, proc handlers, and active DUMMY effects.
 */

#include "Player.h"
#include "ScriptMgr.h"
#include "Spell.h"
#include "SpellAuraEffects.h"
#include "SpellAuras.h"
#include "SpellInfo.h"
#include "SpellScript.h"
#include "Unit.h"

// =====================================================================
// Spell ID Constants — Mage
// =====================================================================

enum MageSpellIds
{
    SPELL_MAGE_INVISIBILITY                                           = 66,
    SPELL_MAGE_INCANTERS_FLOW                                         = 1463,
    SPELL_MAGE_ARCANE_MISSILES                                        = 5143,
    SPELL_MAGE_EVOCATION                                              = 12051,
    SPELL_MAGE_ICE_LANCE                                              = 30455,
    SPELL_MAGE_SUMMON_WATER_ELEMENTAL                                 = 31687,
    SPELL_MAGE_PYROBLAST_CLEARCASTING_DRIVER                          = 44448,
    SPELL_MAGE_FLURRY                                                 = 44614,
    SPELL_MAGE_CAUTERIZE                                              = 86949,
    SPELL_MAGE_DUMMY_50_TALENT                                        = 102052,
    SPELL_MAGE_NETHER_TEMPEST                                         = 114923,
    SPELL_MAGE_KINDLING                                               = 155148,
    SPELL_MAGE_COMBUSTION                                             = 190319,
    SPELL_MAGE_ARCANE_FAMILIAR                                        = 205022,
    SPELL_MAGE_PRESENCE_OF_MIND                                       = 205025,
    SPELL_MAGE_RESONANCE                                              = 205028,
    SPELL_MAGE_TIME_ANOMALY                                           = 210805,
    SPELL_MAGE_TOUCH_OF_THE_MAGI                                      = 210824,
    SPELL_MAGE_ARCING_CLEAVE                                          = 231564,
    SPELL_MAGE_COLD_SNAP                                              = 235219,
    SPELL_MAGE_BLAZING_BARRIER                                        = 235313,
    SPELL_MAGE_BLAZING_SOUL                                           = 235365,
    SPELL_MAGE_PRISMATIC_BARRIER                                      = 235450,
    SPELL_MAGE_FRENETIC_SPEED                                         = 236058,
    SPELL_MAGE_RULE_OF_THREES                                         = 264354,
    SPELL_MAGE_SEARING_TOUCH                                          = 269644,
    SPELL_MAGE_PYROCLASM                                              = 269650,
    SPELL_MAGE_ENLIGHTENED                                            = 321387,
    SPELL_MAGE_IMPROVED_BLAZING_BARRIER                               = 321708,
    SPELL_MAGE_ARCANE_ECHO                                            = 342231,
    SPELL_MAGE_FROM_THE_ASHES                                         = 342344,
    SPELL_MAGE_WINTERTIDE                                             = 378406,
    SPELL_MAGE_FRACTURED_FROST                                        = 378448,
    SPELL_MAGE_GLACIAL_ASSAULT                                        = 378947,
    SPELL_MAGE_INCANTATION_OF_SWIFTNESS                               = 382293,
    SPELL_MAGE_CONTROLLED_DESTRUCTION                                 = 383669,
    SPELL_MAGE_FEVERED_INCANTATION                                    = 383810,
    SPELL_MAGE_MASTER_OF_FLAME                                        = 384174,
    SPELL_MAGE_ARCANE_SALVO                                           = 384452,
    SPELL_MAGE_ORB_BARRAGE                                            = 384858,
    SPELL_MAGE_EVERLASTING_FROST                                      = 385167,
    SPELL_MAGE_FREEZING_COLD                                          = 386763,
    SPELL_MAGE_ENERGIZED_BARRIERS                                     = 386828,
    SPELL_MAGE_OVERFLOWING_ENERGY                                     = 390218,
    SPELL_MAGE_FUEL_THE_FIRE                                          = 416094,
    SPELL_MAGE_INTENSIFYING_FLAME                                     = 416714,
    SPELL_MAGE_INFLAME                                                = 417467,
    SPELL_MAGE_SPLINTERING_RAY                                        = 418733,
    SPELL_MAGE_IMBUED_WARDING                                         = 431066,
    SPELL_MAGE_ELEMENTAL_AFFINITY                                     = 431067,
    SPELL_MAGE_ISOTHERMIC_CORE                                        = 431095,
    SPELL_MAGE_FLAME_AND_FROST                                        = 431112,
    SPELL_MAGE_MELTDOWN                                               = 431131,
    SPELL_MAGE_FROSTFIRE_EMPOWERMENT                                  = 431176,
    SPELL_MAGE_FLASH_FREEZEBURN                                       = 431178,
    SPELL_MAGE_SEVERE_TEMPERATURES                                    = 431189,
    SPELL_MAGE_SPLINTERING_SORCERY                                    = 443739,
    SPELL_MAGE_SPLINTERSTORM                                          = 443783,
    SPELL_MAGE_SPLINTERING_ORBS                                       = 444256,
    SPELL_MAGE_CONTROLLED_INSTINCTS                                   = 444483,
    SPELL_MAGE_SHIFTING_SHARDS                                        = 444675,
    SPELL_MAGE_FORCE_OF_WILL                                          = 444719,
    SPELL_MAGE_SLIPPERY_SLINGING                                      = 444752,
    SPELL_MAGE_LOOK_AGAIN                                             = 444756,
    SPELL_MAGE_REACTIVE_BARRIER                                       = 444827,
    SPELL_MAGE_SPELLFROST_TEACHINGS                                   = 444986,
    SPELL_MAGE_SPELLFIRE_SPHERES                                      = 448601,
    SPELL_MAGE_INVOCATION_ARCANE_PHOENIX                              = 448658,
    SPELL_MAGE_MANA_CASCADE                                           = 449293,
    SPELL_MAGE_MERELY_A_SETBACK                                       = 449330,
    SPELL_MAGE_SUNFURY_EXECUTION                                      = 449349,
    SPELL_MAGE_CODEX_OF_THE_SUNSTRIDERS                               = 449382,
    SPELL_MAGE_GLORIOUS_INCANDESCENCE                                 = 449394,
    SPELL_MAGE_MEMORY_OF_ALAR                                         = 449619,
    SPELL_MAGE_LESSONS_IN_DEBILITATION                                = 449627,
    SPELL_MAGE_FIRES_IRE                                              = 450831,
    SPELL_MAGE_PYROMANIAC                                             = 451466,
    SPELL_MAGE_ENERGIZED_FAMILIAR                                     = 452997,
    SPELL_MAGE_BARRIER_DIFFUSION                                      = 455428,
    SPELL_MAGE_MANA_BOMB                                              = 457521,
    SPELL_MAGE_HEAT_SHIMMER                                           = 457735,
    SPELL_MAGE_MOLTEN_FURY                                            = 457803,
    SPELL_MAGE_INSPIRED_INTELLECT                                     = 458437,
    SPELL_MAGE_PERMAFROST_LANCES                                      = 460590,
    SPELL_MAGE_HIGH_VOLTAGE                                           = 461248,
    SPELL_MAGE_CHARGED_MISSILES                                       = 461251,
    SPELL_MAGE_FOCUSING_CRYSTAL                                       = 461257,
    SPELL_MAGE_BRAINSTORM                                             = 461261,
    SPELL_MAGE_SIGNATURE_SPELL                                        = 470021,
    SPELL_MAGE_FREEZING_WINDS                                         = 1216953,
    SPELL_MAGE_INTUITION                                              = 1223798,
    SPELL_MAGE_AETHER_ATTUNEMENT                                      = 1243307,
    SPELL_MAGE_ORB_MASTERY                                            = 1243435,
    SPELL_MAGE_AEGWYNNS_TECHNIQUE                                     = 1243507,
    SPELL_MAGE_EXPANDED_MIND                                          = 1243557,
    SPELL_MAGE_TIME_WALK                                              = 1244087,
    SPELL_MAGE_TEMPORAL_REALIGNMENT                                   = 1244090,
    SPELL_MAGE_OVERPOWERED_MISSILES                                   = 1244329,
    SPELL_MAGE_EXPLOSIVE_POTENTIAL                                    = 1246032,
    SPELL_MAGE_SHATTER                                                = 1246769,
    SPELL_MAGE_DEEP_SHATTER                                           = 1247025,
    SPELL_MAGE_CONE_OF_FROST                                          = 1247090,
    SPELL_MAGE_CRYSTALLINE_REFRACTION                                 = 1247544,
    SPELL_MAGE_THERMAL_VOID                                           = 1247729,
    SPELL_MAGE_THERMAL_VOID_1247730                                   = 1247730,
    SPELL_MAGE_WINTERS_END                                            = 1247775,
    SPELL_MAGE_GLACIATE                                               = 1247798,
    SPELL_MAGE_FROSTBITE                                              = 1248825,
    SPELL_MAGE_BURN_IT_ALL                                            = 1254512,
    SPELL_MAGE_DEEP_IMPACT                                            = 1254857,
    SPELL_MAGE_CINDERSTORM                                            = 1254865,
    SPELL_MAGE_FIRED_UP                                               = 1257343,
    SPELL_MAGE_FIRED_UP_1257348                                       = 1257348,
    SPELL_MAGE_TOUCH_OF_THE_ARCHMAGE                                  = 1257950,
    SPELL_MAGE_ASHES_OF_INSPIRATION                                   = 1260272,
    SPELL_MAGE_PYROCOSM                                               = 1260673,
    SPELL_MAGE_INFUSED_SPLINTERS                                      = 1261080,
    SPELL_MAGE_POLISHED_FOCUS                                         = 1261082,
    SPELL_MAGE_ATTUNED_FAMILIAR                                       = 1261106,
    SPELL_MAGE_DUALITY                                                = 1262843,
    SPELL_MAGE_MOLTEN_CHILL                                           = 1262844,
    SPELL_MAGE_ELEMENTAL_CONDUIT                                      = 1262845,
    SPELL_MAGE_HAND_OF_FROST                                          = 1262935,
    SPELL_MAGE_HAND_OF_FROST_1262981                                  = 1262981,
    SPELL_MAGE_HAND_OF_FROST_1263249                                  = 1263249,
    SPELL_MAGE_REFLECTION                                             = 1270829,
    SPELL_MAGE_BURNOUT                                                = 1271177,
    SPELL_MAGE_AUGURY_ABOUNDS                                         = 1280165,
    SPELL_MAGE_GLACIAL_SHATTER                                        = 1280780,
    SPELL_MAGE_WHITE_OUT                                              = 1281638,
};

// =====================================================================
// Passive DUMMY — Modifier Buffs (14 spells)
// These passives store modifier values in DUMMY aura effects.
// The values need to be applied to affected spells via HandleProc
// or by modifying spell amounts in CalcAmount handlers.
// =====================================================================

// 155148 - Kindling
// Tooltip: "Your Fireball, Pyroblast, Fire Blast, Scorch and Phoenix Flames critical strikes reduce the remaining cooldown on Combus"
// SimC: Spell initialization/registration only
class spell_mage_kindling : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=1000.0, eff1=5.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_kindling::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_kindling::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_kindling::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_kindling::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 269644 - Searing Touch
// Tooltip: "Scorch deals $s2% increased damage and is a guaranteed Critical Strike when the target is below $s1% health."
class spell_mage_searing_touch : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=30.0, eff1=175.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_searing_touch::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_searing_touch::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_searing_touch::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_searing_touch::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 321708 - Improved Blazing Barrier
// Tooltip: "Blazing Barrier's damage is increased by $s1% and it now cauterizes your wounds, healing you for $s2% of the damage it a"
class spell_mage_improved_blazing_barrier : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff1=15.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_improved_blazing_barrier::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_improved_blazing_barrier::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 342344 - From the Ashes
// Tooltip: "Fire Blast damage increased by $s2%.  Your direct damage spells reduce the cooldown of Fire Blast by ${$s1/-1000}.2 sec."
class spell_mage_from_the_ashes : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=-500.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_from_the_ashes::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_from_the_ashes::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 416714 - Intensifying Flame
// Tooltip: "While Ignite is on $s1 or fewer enemies it flares up dealing an additional $s2% of its damage to affected targets."
// SimC: Has proc/trigger behavior; Aura override or transformation behavior
class spell_mage_intensifying_flame : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=3.0, eff1=30.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_intensifying_flame::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_intensifying_flame::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_intensifying_flame::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_intensifying_flame::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 431095 - Isothermic Core
// Tooltip: "$?a137019[Meteor now also calls down a Comet Storm, dealing ${$438609s1*7} Frost damage to nearby enemies]?a137020[Comet"
// SimC: Spell initialization/registration only
class spell_mage_isothermic_core : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=150.0, eff1=300.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_isothermic_core::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_isothermic_core::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_isothermic_core::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_isothermic_core::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 444986 - Spellfrost Teachings
// Tooltip: "Direct damage from $?c1[Arcane][Frost] Splinters reduces the cooldown of $?c1[Arcane][Frozen] Orb by $?c1[${$s1/1000}.2]"
// SimC: Spell initialization/registration only
class spell_mage_spellfrost_teachings : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=250.0, eff1=250.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_spellfrost_teachings::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_spellfrost_teachings::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_spellfrost_teachings::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_spellfrost_teachings::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 449619 - Memory of Al'ar
// Tooltip: "During $?c1[Arcane Surge][Combustion], you gain twice as many stacks of Mana Cascade. When your Arcane Phoenix expires, "
// SimC: Spell initialization/registration only
class spell_mage_memory_of_alar : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=4000.0, eff1=4000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_memory_of_alar::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_memory_of_alar::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_memory_of_alar::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_memory_of_alar::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 450831 - Fire's Ire
// Tooltip: "Your spell critical strike chance is increased by ${$s3/1000}.1%. Combustion increases your critical strike damage by ${"
class spell_mage_fires_ire : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff2=2500.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_fires_ire::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_fires_ire::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 455428 - Barrier Diffusion
// Tooltip: "When your Barrier is removed, reduce its cooldown by ${$s1/1000} sec."
// SimC: Involves resource gain/cost
class spell_mage_barrier_diffusion : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=5000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_barrier_diffusion::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_barrier_diffusion::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1243507 - Aegwynn's Technique
// Tooltip: "Casting Touch of the Magi grants Clearcasting."
// SimC: Spell initialization/registration only
class spell_mage_aegwynns_technique : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=-5.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_aegwynns_technique::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_aegwynns_technique::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1244090 - Temporal Realignment
// Tooltip: "Upon dropping below $s1% health, your past self corrects your timeline, casting Alter Time and instantly returning $1244"
class spell_mage_temporal_realignment : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff1=50.0, eff2=60000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_temporal_realignment::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_temporal_realignment::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_temporal_realignment::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_temporal_realignment::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1254857 - Deep Impact
// Tooltip: "The enemy closest to the center of Meteor's impact takes $s3% increased damage."
// SimC: Spell initialization/registration only
class spell_mage_deep_impact : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=75.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_deep_impact::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_deep_impact::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1260673 - Pyrocosm
// Tooltip: "$?c1[Each wave of Arcane Missiles][Damage from Fireball] has a $?c1[$s1][$s2]% chance to summon a Meteorite. When a Mete"
// SimC: Spell initialization/registration only
class spell_mage_pyrocosm : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=10.0, eff1=20.0, eff2=2.0, eff3=500.0, eff4=5.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_pyrocosm::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_pyrocosm::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_pyrocosm::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_pyrocosm::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_pyrocosm::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_pyrocosm::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_pyrocosm::HandleApply, EFFECT_3, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_pyrocosm::HandleRemove, EFFECT_3, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_pyrocosm::HandleApply, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_pyrocosm::HandleRemove, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// =====================================================================
// Passive DUMMY — Proc Handlers (13 spells)
// These passives proc on combat events and apply effects.
// =====================================================================

// 44448 - Pyroblast Clearcasting Driver
// Tooltip: "No description"
// ProcMask: 65536
// SimC: Referenced in SimC (context needs manual review)
class spell_mage_pyroblast_clearcasting_driver : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_pyroblast_clearcasting_driver::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// 378406 - Wintertide
// Tooltip: "Frozen Orb has a $s1% chance to grant Brain Freeze."
// ProcMask: 0
// SimC: Spell initialization/registration only
class spell_mage_wintertide : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_wintertide::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// 378448 - Fractured Frost
// Tooltip: "Ice Lance strikes $s1 additional $Ltarget:targets; at $s2% effectiveness, preferring enemies with more stacks of Freezin"
// ProcMask: 0
// SimC: Spell initialization/registration only
class spell_mage_fractured_frost : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=1.0, eff1=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_fractured_frost::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_fractured_frost::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 384858 - Orb Barrage
// Tooltip: "Arcane Barrage has a $s1% chance per stack of Arcane Salvo to launch an Arcane Orb in front of you at $s2% effectiveness"
// ProcMask: 0
// SimC: Buff interaction: arcane_charge, arcane_salvo, arcane_surge, clearcasting, overpowered_missiles; Deb
class spell_mage_orb_barrage : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=4.0, eff1=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_orb_barrage::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_orb_barrage::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 416094 - Fuel the Fire
// Tooltip: "Flamestrike has a chance equal to $s1% of your spell critical strike chance to build up to a Hot Streak. Flamestrike dea"
// ProcMask: 0
// SimC: Has proc/trigger behavior; Buff interaction: bloodlust, combustion, frostfire_empowerment, heat_shim
class spell_mage_fuel_the_fire : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0, eff1=5.0, eff2=5.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_fuel_the_fire::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_fuel_the_fire::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_fuel_the_fire::HandleProc, EFFECT_2, SPELL_AURA_DUMMY);
    }
};

// 431176 - Frostfire Empowerment
// Tooltip: "Casting Frostfire spells has a $s3% chance to activate Frostfire Empowerment, causing your next Frostfire Bolt to be ins"
// ProcMask: 65536
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1, 2, 3; Reads percentage value fr
class spell_mage_frostfire_empowerment : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0, eff1=60.0, eff2=10.0, eff3=1.0, eff4=5.0, eff5=60.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_frostfire_empowerment::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_frostfire_empowerment::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_frostfire_empowerment::HandleProc, EFFECT_2, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_frostfire_empowerment::HandleProc, EFFECT_3, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_frostfire_empowerment::HandleProc, EFFECT_4, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_frostfire_empowerment::HandleProc, EFFECT_5, SPELL_AURA_DUMMY);
    }
};

// 431189 - Severe Temperatures
// Tooltip: "Frostfire Empowerment stacks $s1 additional $Ltime:times; and it causes Frostfire Bolt to explode for an additional $s2%"
// ProcMask: 0
class spell_mage_severe_temperatures : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff2=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_severe_temperatures::HandleProc, EFFECT_2, SPELL_AURA_DUMMY);
    }
};

// 1243435 - Orb Mastery
// Tooltip: "Casting Arcane Orb while you have Clearcasting causes you to fire $s1 additional Arcane $lOrb:Orbs; at $s2% effectivenes"
// ProcMask: 0
// SimC: Buff interaction: arcane_salvo, arcane_surge, clearcasting, overpowered_missiles, touch_of_the_magi;
class spell_mage_orb_mastery : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=2.0, eff1=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_orb_mastery::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_orb_mastery::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 1244329 - Overpowered Missiles
// Tooltip: "Gaining Clearcasting has a $s1% chance to cause your next Arcane Missiles to be Overpowered, causing it to deal $1277009"
// ProcMask: 0
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1, 2; Reads percentage value from 
class spell_mage_overpowered_missiles : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=25.0, eff1=2.0, eff2=2.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_overpowered_missiles::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_overpowered_missiles::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_overpowered_missiles::HandleProc, EFFECT_2, SPELL_AURA_DUMMY);
    }
};

// 1247729 - Thermal Void
// Tooltip: "Consuming Brain Freeze has a $s1% chance to cause your next Ice Lance to Shatter $1246769s4 additional stacks of Freezin"
// ProcMask: 0
// SimC: Has proc/trigger behavior; Uses effect(s) 1, 3; Reads percentage value from effect; Buff interaction
class spell_mage_thermal_void_1247729 : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0, eff1=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_thermal_void_1247729::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_thermal_void_1247729::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 1247798 - Glaciate
// Tooltip: "When Ice Lance Shatters a stack of Freezing, the cooldown of Ray of Frost is reduced by ${$s2/1000}.2 sec."
// ProcMask: 0
// SimC: Spell initialization/registration only
class spell_mage_glaciate : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=5.0, eff1=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_glaciate::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_glaciate::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 1254865 - Cinderstorm
// Tooltip: "Casting Pyroblast or Flamestrike has a $s1% chance to summon a storm of $s4 cinders that pursue your target. Upon reachi"
// ProcMask: 65536
// SimC: Has proc/trigger behavior; Uses effect(s) 1, 4; Reads percentage value from effect; Referenced in Si
class spell_mage_cinderstorm : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=8.0, eff1=50.0, eff2=1.0, eff3=5.0, eff4=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_cinderstorm::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_cinderstorm::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_cinderstorm::HandleProc, EFFECT_2, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_cinderstorm::HandleProc, EFFECT_3, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_cinderstorm::HandleProc, EFFECT_4, SPELL_AURA_DUMMY);
    }
};

// 1281638 - White Out
// Tooltip: "Ice Lance reduces the cooldown of Frozen Orb by ${$s1/1000}.1 sec, increased by ${$s2/1000}.1 sec for each stack of Free"
// ProcMask: 0
// SimC: Spell initialization/registration only
class spell_mage_white_out : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=500.0, eff1=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_mage_white_out::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_mage_white_out::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// =====================================================================
// Passive DUMMY — Other (81 spells)
// These need individual research to determine handler type.
// =====================================================================

// 86949 - Cauterize — bp=eff1=35.0
// "Fatal damage instead brings you to $86949s2% health and then burns you for $8702"
class spell_mage_cauterize : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 102052 - Dummy 5.0 Talent — bp=eff0=0.0
class spell_mage_dummy_50_talent : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 205022 - Arcane Familiar — bp=eff0=1.0
// "Casting Arcane Intellect summons a Familiar that attacks your enemies and increa"
class spell_mage_arcane_familiar : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 205028 - Resonance — bp=eff0=8.0
// "Arcane Barrage deals $s1% increased damage per target it hits beyond the first."
// SimC: Has proc/trigger behavior; Buff interaction: arcane_charge, arcane_salvo, arcane
class spell_mage_resonance : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 231564 - Arcing Cleave — bp=eff1=60.0
// "For each Arcane Charge, Arcane Barrage hits $s1 additional nearby $Ltarget:targe"
class spell_mage_arcing_cleave : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 235365 - Blazing Soul — bp=eff0=0.0
// "Casting Blink ignites a Blazing Barrier around you."
class spell_mage_blazing_soul : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 264354 - Rule of Threes — bp=eff0=0.0
// "When you gain your third Arcane Charge, the cost of your next Arcane Blast or Ar"
class spell_mage_rule_of_threes : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 269650 - Pyroclasm — bp=eff0=15.0
// "Consuming Hot Streak has a $s1% chance to make your next non-instant Pyroblast o"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Reads percentage value from effect;
class spell_mage_pyroclasm : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 321387 - Enlightened — bp=eff0=0.0
// "Arcane damage dealt is increased based on your current mana, up to $1217242s2% a"
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 2, 3, 4; Reads
class spell_mage_enlightened : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 342231 - Arcane Echo — bp=eff0=8.0, eff2=5.0
// "Direct damage you deal to enemies affected by $?s461264[Nether Flux][Touch of th"
class spell_mage_arcane_echo : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 378947 - Glacial Assault — bp=eff0=12.0, eff1=1.0
// "Flurry has a $s1% chance each hit to call down an icy comet, crashing into your "
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1; Reads perce
class spell_mage_glacial_assault : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 382293 - Incantation of Swiftness — bp=eff0=20.0
// "$?s110959[Greater ][]Invisibility increases your movement speed by $s1% for $337"
// SimC: Spell initialization/registration only
class spell_mage_incantation_of_swiftness : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 383669 - Controlled Destruction — bp=eff0=2.0, eff1=20.0
// "Damaging an enemy with Fireball, Pyroblast, or Flamestrike increases the damage "
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Reads percentage value from effect
class spell_mage_controlled_destruction : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 383810 - Fevered Incantation — bp=eff0=1.0
// "Each consecutive critical strike you deal increases critical strike damage you d"
class spell_mage_fevered_incantation : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 384174 - Master of Flame — bp=eff0=15.0
// "Ignite deals $s1% more damage when Combustion is not active. Fire Blast now spre"
class spell_mage_master_of_flame : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 384452 - Arcane Salvo — bp=eff0=7.0, eff1=1.0
// "Each wave of Arcane Missiles increases the damage of Arcane Barrage by $1242974s"
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1; Reads perce
class spell_mage_arcane_salvo : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 385167 - Everlasting Frost — bp=eff0=1.0, eff1=3.0
// "Casting Frozen Orb grants $s1 $Lstack:stacks; of Fingers of Frost. Damaging one "
// SimC: Spell initialization/registration only
class spell_mage_everlasting_frost : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 386763 - Freezing Cold — bp=eff0=0.0
// "Enemies hit by Cone of Cold are frozen in place for $386770d instead of snared. "
// SimC: Spell initialization/registration only
class spell_mage_freezing_cold : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 390218 - Overflowing Energy — bp=eff0=10.0, eff1=0.0
// "Each time your $?a137021[Arcane Barrage]?a137019[Fireball]?a137020[Frostbolt][Ar"
// SimC: Uses effect(s) 1; Reads percentage value from effect; Referenced in SimC (contex
class spell_mage_overflowing_energy : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 417467 - Inflame — bp=eff0=25.0
// "Hot Streak increases the amount of Ignite damage from Pyroblast or Flamestrike b"
// SimC: Spell initialization/registration only
class spell_mage_inflame : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 418733 - Splintering Ray — bp=eff0=30.0, eff1=5.0
// "Ray of Frost deals $s1% of its damage to $s2 nearby enemies."
// SimC: Has proc/trigger behavior; Referenced in SimC (context needs manual review)
class spell_mage_splintering_ray : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 431066 - Imbued Warding — bp=eff0=25.0, eff1=25.0
// "$?c2[Blazing Barrier also casts an Ice Barrier at $s1% effectiveness.]?c3[Ice Ba"
// SimC: Spell initialization/registration only
class spell_mage_imbued_warding : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 431067 - Elemental Affinity — bp=eff3=4.0
// "$?c2[The cooldown of Frost spells with a base cooldown shorter than $s4 minutes "
class spell_mage_elemental_affinity : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 3
    }
};

// 431112 - Flame and Frost — bp=eff0=4.0
// "$?a137020[Ice Block and Ice Cold reset the cooldowns of your Fire spells]?a13701"
// SimC: Spell initialization/registration only
class spell_mage_flame_and_frost : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 431178 - Flash Freezeburn — bp=eff1=25.0, eff2=5.0
// "$?a137020[Glacial Spike damage increased by $s1% and it now explodes on impact, "
class spell_mage_flash_freezeburn : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 443739 - Splintering Sorcery — bp=eff0=0.0, eff1=1.0, eff2=4.0
// "$?c1[Casting Arcane Blast or Arcane Pulse][Casting Frostbolt or Flurry] conjures"
// SimC: Buff interaction: arcane_salvo, arcane_surge, clearcasting, overpowered_missiles
class spell_mage_splintering_sorcery : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 443783 - Splinterstorm — bp=eff0=8.0, eff2=1.0
// "$?c1[Casting Arcane Surge generates $s1 Arcane Splinters][Each time Ray of Frost"
class spell_mage_splinterstorm : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 444256 - Splintering Orbs — bp=eff0=4.0, eff3=2.0, eff4=1.0, eff5=4.0
// "Enemies damaged by your $?c1[Arcane Orb][Frozen Orb] conjure $?c1[$s4 Arcane][$s"
class spell_mage_splintering_orbs : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 3
        // TODO: Determine handler type for DUMMY effect 4
        // TODO: Determine handler type for DUMMY effect 5
    }
};

// 444483 - Controlled Instincts — bp=eff0=60.0
// "$?c1[$s1%][$s4%] of the direct damage dealt by $?c1[an Arcane Splinter][a Frost "
class spell_mage_controlled_instincts : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 444675 - Shifting Shards — bp=eff0=2.0
// "Gaining $?c1[Clearcasting][Brain Freeze] conjures $s1 $?c1[Arcane][Frost] $lSpli"
// SimC: Spell initialization/registration only
class spell_mage_shifting_shards : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 444719 - Force of Will — bp=eff0=5.0, eff1=2.0, eff2=2.0
// "$?c1[Casting Arcane Barrage conjures an Arcane Splinter for every $s1 Arcane Sal"
// SimC: Spell initialization/registration only
class spell_mage_force_of_will : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 444752 - Slippery Slinging — bp=eff0=40.0
// "You have $s1% increased movement speed during Alter Time$?a236457[ and Evocation"
// SimC: Spell initialization/registration only
class spell_mage_slippery_slinging : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 444756 - Look Again — bp=eff0=0.0
// "While in combat, Blink summons a Mirror Image at your previous location."
// SimC: Spell initialization/registration only
class spell_mage_look_again : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 444827 - Reactive Barrier — bp=eff0=25.0
// "Your $?c1[Prismatic][Ice] Barrier can absorb up to $s1% more damage based on you"
// SimC: Spell initialization/registration only
class spell_mage_reactive_barrier : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 448601 - Spellfire Spheres — bp=eff0=12.0
// "$?c1[Casting a damaging spell][Consuming Hot Streak] has a $s1% chance to conjur"
// SimC: Buff interaction: arcane_salvo, arcane_surge, clearcasting, combustion, pyroclas
class spell_mage_spellfire_spheres : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 448658 - Invocation: Arcane Phoenix — bp=eff0=0.0
// "When you cast $?c1[Arcane Surge][Combustion], summon an Arcane Phoenix to aid yo"
// SimC: Spell initialization/registration only
class spell_mage_invocation_arcane_phoenix : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 449293 - Mana Cascade — bp=eff0=0.0
// "$?c1[Casting Arcane Blast or Arcane Barrage][Consuming Hot Streak] grants you $?"
// SimC: Has proc/trigger behavior
class spell_mage_mana_cascade : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 449330 - Merely a Setback — bp=eff0=5.0, eff1=90.0
// "The bonuses provided by your Barrier spells persist an additional $?c1[$449336d]"
// SimC: Spell initialization/registration only
class spell_mage_merely_a_setback : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 449349 - Sunfury Execution — bp=eff1=5.0
// "$?c2[Pyroclasm's damage bonus is increased by $s1% and Meteor grants Pyroclasm i"
class spell_mage_sunfury_execution : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 449382 - Codex of the Sunstriders — bp=eff0=1.0, eff1=2.0
// "When your Arcane Phoenix is summoned, it consumes all your Spellfire Spheres. Ea"
// SimC: Spell initialization/registration only
class spell_mage_codex_of_the_sunstriders : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 449394 - Glorious Incandescence — bp=eff0=4.0
// "$?c2[Generating a Spellfire Sphere causes your next cast of Fire Blast to call d"
class spell_mage_glorious_incandescence : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 449627 - Lessons in Debilitation — bp=eff0=0.0
// "Your Arcane Phoenix has picked up a few tricks, and will Spellsteal when it is s"
// SimC: Spell initialization/registration only
class spell_mage_lessons_in_debilitation : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 451466 - Pyromaniac — bp=eff0=6.0, eff1=50.0
// "Casting Pyroblast or Flamestrike while Hot Streak is active has a $s1% chance to"
// SimC: Has proc/trigger behavior; Affects cooldown/recharge timing; Referenced in SimC 
class spell_mage_pyromaniac : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 457521 - Mana Bomb — bp=eff0=50.0
// "Arcane Surge's damage is increased by an additional $s1% based on your mana spen"
// SimC: Spell initialization/registration only
class spell_mage_mana_bomb : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 457735 - Heat Shimmer — bp=eff0=5.0, eff1=30.0
// "While Combustion is not active, damage from Ignite has a small chance to make yo"
// SimC: Has proc/trigger behavior; Uses effect(s) 1, 2; Reads percentage value from effe
class spell_mage_heat_shimmer : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 457803 - Molten Fury — bp=eff0=30.0
// "Damage dealt to targets below $s1% health is increased by $458910s1%."
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Referenced in SimC (context needs m
class spell_mage_molten_fury : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 458437 - Inspired Intellect — bp=eff0=2.0
// "Arcane Intellect grants you an additional $s1% Intellect."
// SimC: Spell initialization/registration only
class spell_mage_inspired_intellect : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 460590 - Permafrost Lances — bp=eff0=1.0
// "Frozen Orb increases Shatter's damage by $455122s1% for its duration."
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1; Reads perce
class spell_mage_permafrost_lances : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 461248 - High Voltage — bp=eff0=50.0
// "Each wave of Arcane Missiles has a $s1% chance to grant you $461524s1 Arcane Cha"
class spell_mage_high_voltage : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 461251 - Charged Missiles — bp=eff0=40.0
// "Each wave of Arcane Missiles will consume an Arcane Charge to increase its damag"
// SimC: Spell initialization/registration only
class spell_mage_charged_missiles : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 461257 - Focusing Crystal — bp=eff0=50.0, eff1=1.0
// "Each wave of Arcane Missiles has a $s1% chance to grant $s2 additional $Lstack:s"
// SimC: Spell initialization/registration only
class spell_mage_focusing_crystal : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 461261 - Brainstorm — bp=eff0=1.0, eff1=8.0
// "Gaining $?a137021[Clearcasting]?a137020[Brain Freeze][Hot Streak] increases your"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Affects cooldown/recharge timing
class spell_mage_brainstorm : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 470021 - Signature Spell — bp=eff0=4.0, eff1=2.0
// "$?c1[Arcane Blast and Arcane Pulse damage increased by $s3%. Casting Touch of th"
class spell_mage_signature_spell : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1216953 - Freezing Winds — bp=eff0=15.0
// "Shattering enemies inside your Blizzard increases Shatter's area damage by $s1%."
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Reads percentage value from effect;
class spell_mage_freezing_winds : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1223798 - Intuition — bp=eff0=25.0
// "Upon reaching maximum stacks of Arcane Salvo, your next Arcane Barrage deals $s1"
// SimC: Has proc/trigger behavior; Resource: MANA; Affects cooldown/recharge timing; Ref
class spell_mage_intuition : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1243307 - Aether Attunement — bp=eff0=50.0, eff1=2.0
// "Arcane Missiles now damages ${$s2} additional targets at $s1% effectiveness."
// SimC: Spell initialization/registration only
class spell_mage_aether_attunement : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1243557 - Expanded Mind — bp=eff0=2.0, eff1=2.0
// "Casting Arcane Blast or Arcane Pulse grants $s1 $Lstack:stacks; of Arcane Salvo."
// SimC: Involves resource gain/cost
class spell_mage_expanded_mind : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1244087 - Time Walk — bp=eff0=1.0
// "Alter Time resets the cooldown of Blink and Shimmer when you return to your orig"
// SimC: Spell initialization/registration only
class spell_mage_time_walk : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1246769 - Shatter — bp=eff0=1.0, eff1=1.0, eff2=3.0, eff3=4.0, eff4=1.0
// "Damage from Frostbolt and Flurry applies Freezing to their targets. Stacks up to"
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1, 2, 3, 4, 5;
class spell_mage_shatter : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
        // TODO: Determine handler type for DUMMY effect 3
        // TODO: Determine handler type for DUMMY effect 4
    }
};

// 1247090 - Cone of Frost — bp=eff0=3.0, eff1=5.0
// "$?a157997[Ice Nova][Cone of Cold] now applies $s1 $Lstack:stacks; of Freezing to"
// SimC: Buff interaction: fingers_of_frost, freezing, freezing_rain; Debuff interaction:
class spell_mage_cone_of_frost : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1247544 - Crystalline Refraction — bp=eff0=2.0
// "Ray of Frost generates $s1 $Lstack:stacks; of Fingers of Frost over its duration"
// SimC: Spell initialization/registration only
class spell_mage_crystalline_refraction : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1247775 - Winter's End — bp=eff0=5.0
// "When an enemy affected by Freezing dies, it explodes, dealing $1280757s1 Frost d"
// SimC: Used in mastery calculation; Has proc/trigger behavior; Modifies damage output; 
class spell_mage_winters_end : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1248825 - Frostbite — bp=eff0=1.0, eff1=5.0
// "When $?s431044[Frostfire Bolt][Frostbolt] critically strikes, it applies $s1 add"
// SimC: Spell initialization/registration only
class spell_mage_frostbite : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1254512 - Burn It All — bp=eff0=20.0
// "Combustion grants you $s2% increased spell damage plus an additional $s1% of you"
class spell_mage_burn_it_all : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1257343 - Fired Up — bp=eff0=20.0, eff1=0.0, eff2=0.0
// "Consuming Hot Streak has a $s1% chance to grant you a stack of Fired Up, increas"
// SimC: Has proc/trigger behavior; Uses effect(s) 2, 3; Reads percentage value from effe
class spell_mage_fired_up_1257343 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 1257348 - Fired Up — bp=eff0=15.0
// "Combustion significantly increases your chance of gaining Fired Up, reducing eac"
class spell_mage_fired_up_1257348 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1257950 - Touch of the Archmage — bp=eff0=75.0, eff1=50.0
// "When Touch of the Magi explodes, it leaves behind a pulsing rune on its target, "
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Reads percentage value from effect;
class spell_mage_touch_of_the_archmage : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1260272 - Ashes of Inspiration — bp=eff0=0.0
// "When your Arcane Phoenix expires, it grants you Lesser Time Warp for $1260277d. "
// SimC: Spell initialization/registration only
class spell_mage_ashes_of_inspiration : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1261080 - Infused Splinters — bp=eff0=25.0, eff1=15.0, eff2=1.0, eff3=1.0
// "Direct damage from $?c1[Arcane][Frost] Splinters have a $?c1[$s1][$s2]% chance t"
// SimC: Spell initialization/registration only
class spell_mage_infused_splinters : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
        // TODO: Determine handler type for DUMMY effect 3
    }
};

// 1261082 - Polished Focus — bp=eff0=20.0, eff1=5.0
// "$?c1[Casting Arcane Barrage while at $s1 or more Arcane Salvo stacks refunds $s2"
class spell_mage_polished_focus : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1261106 - Attuned Familiar — bp=eff0=50.0, eff1=50.0
// "$?c1[Your Arcane Familiar has a $s1% chance to conjure a Splinter alongside its "
// SimC: Spell initialization/registration only
class spell_mage_attuned_familiar : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1262843 - Duality — bp=eff0=20.0
// "$?c2[Casting Pyroblast has a $s2% chance to also cast a Glacial Spike, dealing $"
// SimC: Spell initialization/registration only
class spell_mage_duality : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1262844 - Molten Chill — bp=eff0=30.0, eff1=10.0
// "$?c3[Your Frostfire spells apply Ignite, dealing an additional $s1% of their dam"
// SimC: Spell initialization/registration only
class spell_mage_molten_chill : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1262845 - Elemental Conduit — bp=eff0=15.0
// "$?c2[Comet Storm and Glacial Spike now apply Ignite][Meteor and Pyroblast now ap"
class spell_mage_elemental_conduit : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1262935 - Hand of Frost — bp=eff0=10.0, eff1=1.0
// "Shattering an enemy has a $s1% chance to summon a Hand of Frost to pursue your t"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Reads percentage value from effect;
class spell_mage_hand_of_frost_1262935 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1262981 - Hand of Frost — bp=eff0=10.0
// "Each stack of Freezing you Shatter increases your chance to summon a Hand of Fro"
class spell_mage_hand_of_frost_1262981 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1263249 - Hand of Frost — bp=eff0=4.0
// "Ray of Frost summons $s1 Hands of Frost over its duration. Ray of Frost gains an"
class spell_mage_hand_of_frost_1263249 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1270829 - Reflection — bp=eff0=0.0
// "After casting $?s212653[Shimmer][Blink], it is replaced with Reflection for $389"
// SimC: Spell initialization/registration only
class spell_mage_reflection : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1271177 - Burnout — bp=eff0=75.0, eff1=8.0
// "When Combustion expires, all of your active Ignites explode, dealing $s1% of the"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Reads percentage value from effect;
class spell_mage_burnout : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1280165 - Augury Abounds — bp=eff0=10.0, eff1=8.0
// "Conjuring one or more $?c1[Arcane][Frost] Splinters has a $s1% chance to conjure"
// SimC: Uses effect(s) 1, 2; Reads percentage value from effect; Affects cooldown/rechar
class spell_mage_augury_abounds : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1280780 - Glacial Shatter — bp=eff0=5.0
// "Glacial Spike no longer applies Freezing, and instead Shatters $s1 $Lstack:stack"
// SimC: Spell initialization/registration only
class spell_mage_glacial_shatter : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// =====================================================================
// PERIODIC_DUMMY — Tick Handlers (7 spells)
// =====================================================================

// 1463 - Incanter's Flow
// "Magical energy flows through you while in combat, building up to ${$116267m1*5}% increased damage and then diminishing d"
class spell_mage_incanters_flow : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_mage_incanters_flow::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 5143 - Arcane Missiles
// "|cFFFFFFFFRequires Clearcasting|r Launches ${($d/$t1)+1} waves of Arcane Missiles at the enemy over $5143d, causing a to"
class spell_mage_arcane_missiles : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_mage_arcane_missiles::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 12051 - Evocation
// "Increases your mana regeneration by $s1% for $d."
class spell_mage_evocation : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_mage_evocation::HandlePeriodic, EFFECT_1, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 190319 - Combustion
// "Engulfs you in flames for $d, increasing your spells' critical strike chance by $s1%.$?a383967[ Additionally, increases "
class spell_mage_combustion : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_mage_combustion::HandlePeriodic, EFFECT_4, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 210805 - Time Anomaly
// "At any moment, you have a chance to gain Arcane Power for $s1 sec, gain Evocation for $s2 sec, or gain Time Warp for $34"
class spell_mage_time_anomaly : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=eff1=1.0, eff2=4.0
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_mage_time_anomaly::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 431131 - Meltdown
// "You melt slightly out of your Ice Block and Ice Cold, allowing you to move slowly during Ice Block and increasing your m"
class spell_mage_meltdown : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=eff1=4.0
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_mage_meltdown::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 1247025 - Deep Shatter
// "Shatter's critical strike damage is increased by $s1% of your critical strike chance."
class spell_mage_deep_shatter : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=eff0=50.0
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_mage_deep_shatter::HandlePeriodic, EFFECT_2, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// =====================================================================
// Active DUMMY — HandleDummy (11 spells)
// =====================================================================

// 66 - Invisibility
// "Turns you invisible over $66d, reducing threat each second. While invisible, you are untargetable by enemies. Lasts $326"
class spell_mage_invisibility : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_invisibility::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_invisibility::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 30455 - Ice Lance
// "Quickly fling a shard of ice at the target, dealing $228598s1 Frost damage. |CFFffffffShatters $1246769s4 stacks of Free"
class spell_mage_ice_lance : public SpellScript
{
    void HandleDummy(SpellEffIndex /*effIndex*/)
    {
        // TODO: Implement active DUMMY effect behavior
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_mage_ice_lance::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
};

// 31687 - Summon Water Elemental
// "Summons a Water Elemental to follow and fight for you."
class spell_mage_summon_water_elemental : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_summon_water_elemental::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_summon_water_elemental::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 114923 - Nether Tempest
// "Places a Nether Tempest on the target which deals $114923o1 Arcane damage over $114923d to the target and nearby enemies"
class spell_mage_nether_tempest : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_nether_tempest::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_nether_tempest::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 205025 - Presence of Mind
// "Causes your next $n Arcane $LBlast:Blasts; to be instant cast$?a134735[ and deal $s2% of normal damage][]."
class spell_mage_presence_of_mind : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_presence_of_mind::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_presence_of_mind::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 210824 - Touch of the Magi
// "$@spelldesc210725"
class spell_mage_touch_of_the_magi : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_touch_of_the_magi::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_touch_of_the_magi::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_mage_touch_of_the_magi::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_touch_of_the_magi::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 235219 - Cold Snap
// "Resets the cooldown of your Ice Barrier, Frost Nova, $?a417493[][Cone of Cold, ]Ice Cold, and Ice Block."
class spell_mage_cold_snap : public SpellScript
{
    void HandleDummy(SpellEffIndex /*effIndex*/)
    {
        // TODO: Implement active DUMMY effect behavior
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_mage_cold_snap::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
};

// 235313 - Blazing Barrier
// "Shields you in flame, absorbing $<shield> damage$?s194315[ and reducing Physical damage taken by $s3%][] for $d. Melee a"
class spell_mage_blazing_barrier : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_blazing_barrier::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_blazing_barrier::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 235450 - Prismatic Barrier
// "Shields you with an arcane force, absorbing $<shield> damage and reducing magic damage taken by $s3% for $d. The duratio"
class spell_mage_prismatic_barrier : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_prismatic_barrier::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_prismatic_barrier::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1246032 - Explosive Potential
// "$@spelldesc1246030"
class spell_mage_explosive_potential : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_explosive_potential::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_explosive_potential::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1247730 - Thermal Void
// "$@spelldesc1247729"
class spell_mage_thermal_void_1247730 : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_mage_thermal_void_1247730::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_mage_thermal_void_1247730::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// =====================================================================
// Proc Trigger Spells — Primarily need spell_proc SQL (1 spells)
// Some may also need C++ CheckProc/OnProc handlers
// =====================================================================

// 236058 - Frenetic Speed — needs spell_proc SQL entry + possibly C++ proc filter
class spell_mage_frenetic_speed : public AuraScript
{
    bool CheckProc(ProcEventInfo& eventInfo)
    {
        // TODO: Validate proc conditions
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
    }

    void Register() override
    {
        DoCheckProc += AuraCheckProcFn(spell_mage_frenetic_speed::CheckProc);
        OnEffectProc += AuraEffectProcFn(spell_mage_frenetic_speed::HandleProc, EFFECT_0, SPELL_AURA_PROC_TRIGGER_SPELL);
    }
};

// =====================================================================
// Script Registration
// =====================================================================

void AddSC_mage_spell_audit()
{
    RegisterSpellScript(spell_mage_kindling);
    RegisterSpellScript(spell_mage_searing_touch);
    RegisterSpellScript(spell_mage_improved_blazing_barrier);
    RegisterSpellScript(spell_mage_from_the_ashes);
    RegisterSpellScript(spell_mage_intensifying_flame);
    RegisterSpellScript(spell_mage_isothermic_core);
    RegisterSpellScript(spell_mage_spellfrost_teachings);
    RegisterSpellScript(spell_mage_memory_of_alar);
    RegisterSpellScript(spell_mage_fires_ire);
    RegisterSpellScript(spell_mage_barrier_diffusion);
    RegisterSpellScript(spell_mage_aegwynns_technique);
    RegisterSpellScript(spell_mage_temporal_realignment);
    RegisterSpellScript(spell_mage_deep_impact);
    RegisterSpellScript(spell_mage_pyrocosm);
    RegisterSpellScript(spell_mage_pyroblast_clearcasting_driver);
    RegisterSpellScript(spell_mage_wintertide);
    RegisterSpellScript(spell_mage_fractured_frost);
    RegisterSpellScript(spell_mage_orb_barrage);
    RegisterSpellScript(spell_mage_fuel_the_fire);
    RegisterSpellScript(spell_mage_frostfire_empowerment);
    RegisterSpellScript(spell_mage_severe_temperatures);
    RegisterSpellScript(spell_mage_orb_mastery);
    RegisterSpellScript(spell_mage_overpowered_missiles);
    RegisterSpellScript(spell_mage_thermal_void_1247729);
    RegisterSpellScript(spell_mage_glaciate);
    RegisterSpellScript(spell_mage_cinderstorm);
    RegisterSpellScript(spell_mage_white_out);
    RegisterSpellScript(spell_mage_cauterize);
    RegisterSpellScript(spell_mage_dummy_50_talent);
    RegisterSpellScript(spell_mage_arcane_familiar);
    RegisterSpellScript(spell_mage_resonance);
    RegisterSpellScript(spell_mage_arcing_cleave);
    RegisterSpellScript(spell_mage_blazing_soul);
    RegisterSpellScript(spell_mage_rule_of_threes);
    RegisterSpellScript(spell_mage_pyroclasm);
    RegisterSpellScript(spell_mage_enlightened);
    RegisterSpellScript(spell_mage_arcane_echo);
    RegisterSpellScript(spell_mage_glacial_assault);
    RegisterSpellScript(spell_mage_incantation_of_swiftness);
    RegisterSpellScript(spell_mage_controlled_destruction);
    RegisterSpellScript(spell_mage_fevered_incantation);
    RegisterSpellScript(spell_mage_master_of_flame);
    RegisterSpellScript(spell_mage_arcane_salvo);
    RegisterSpellScript(spell_mage_everlasting_frost);
    RegisterSpellScript(spell_mage_freezing_cold);
    RegisterSpellScript(spell_mage_overflowing_energy);
    RegisterSpellScript(spell_mage_inflame);
    RegisterSpellScript(spell_mage_splintering_ray);
    RegisterSpellScript(spell_mage_imbued_warding);
    RegisterSpellScript(spell_mage_elemental_affinity);
    RegisterSpellScript(spell_mage_flame_and_frost);
    RegisterSpellScript(spell_mage_flash_freezeburn);
    RegisterSpellScript(spell_mage_splintering_sorcery);
    RegisterSpellScript(spell_mage_splinterstorm);
    RegisterSpellScript(spell_mage_splintering_orbs);
    RegisterSpellScript(spell_mage_controlled_instincts);
    RegisterSpellScript(spell_mage_shifting_shards);
    RegisterSpellScript(spell_mage_force_of_will);
    RegisterSpellScript(spell_mage_slippery_slinging);
    RegisterSpellScript(spell_mage_look_again);
    RegisterSpellScript(spell_mage_reactive_barrier);
    RegisterSpellScript(spell_mage_spellfire_spheres);
    RegisterSpellScript(spell_mage_invocation_arcane_phoenix);
    RegisterSpellScript(spell_mage_mana_cascade);
    RegisterSpellScript(spell_mage_merely_a_setback);
    RegisterSpellScript(spell_mage_sunfury_execution);
    RegisterSpellScript(spell_mage_codex_of_the_sunstriders);
    RegisterSpellScript(spell_mage_glorious_incandescence);
    RegisterSpellScript(spell_mage_lessons_in_debilitation);
    RegisterSpellScript(spell_mage_pyromaniac);
    RegisterSpellScript(spell_mage_mana_bomb);
    RegisterSpellScript(spell_mage_heat_shimmer);
    RegisterSpellScript(spell_mage_molten_fury);
    RegisterSpellScript(spell_mage_inspired_intellect);
    RegisterSpellScript(spell_mage_permafrost_lances);
    RegisterSpellScript(spell_mage_high_voltage);
    RegisterSpellScript(spell_mage_charged_missiles);
    RegisterSpellScript(spell_mage_focusing_crystal);
    RegisterSpellScript(spell_mage_brainstorm);
    RegisterSpellScript(spell_mage_signature_spell);
    RegisterSpellScript(spell_mage_freezing_winds);
    RegisterSpellScript(spell_mage_intuition);
    RegisterSpellScript(spell_mage_aether_attunement);
    RegisterSpellScript(spell_mage_expanded_mind);
    RegisterSpellScript(spell_mage_time_walk);
    RegisterSpellScript(spell_mage_shatter);
    RegisterSpellScript(spell_mage_cone_of_frost);
    RegisterSpellScript(spell_mage_crystalline_refraction);
    RegisterSpellScript(spell_mage_winters_end);
    RegisterSpellScript(spell_mage_frostbite);
    RegisterSpellScript(spell_mage_burn_it_all);
    RegisterSpellScript(spell_mage_fired_up_1257343);
    RegisterSpellScript(spell_mage_fired_up_1257348);
    RegisterSpellScript(spell_mage_touch_of_the_archmage);
    RegisterSpellScript(spell_mage_ashes_of_inspiration);
    RegisterSpellScript(spell_mage_infused_splinters);
    RegisterSpellScript(spell_mage_polished_focus);
    RegisterSpellScript(spell_mage_attuned_familiar);
    RegisterSpellScript(spell_mage_duality);
    RegisterSpellScript(spell_mage_molten_chill);
    RegisterSpellScript(spell_mage_elemental_conduit);
    RegisterSpellScript(spell_mage_hand_of_frost_1262935);
    RegisterSpellScript(spell_mage_hand_of_frost_1262981);
    RegisterSpellScript(spell_mage_hand_of_frost_1263249);
    RegisterSpellScript(spell_mage_reflection);
    RegisterSpellScript(spell_mage_burnout);
    RegisterSpellScript(spell_mage_augury_abounds);
    RegisterSpellScript(spell_mage_glacial_shatter);
    RegisterSpellScript(spell_mage_incanters_flow);
    RegisterSpellScript(spell_mage_arcane_missiles);
    RegisterSpellScript(spell_mage_evocation);
    RegisterSpellScript(spell_mage_combustion);
    RegisterSpellScript(spell_mage_time_anomaly);
    RegisterSpellScript(spell_mage_meltdown);
    RegisterSpellScript(spell_mage_deep_shatter);
    RegisterSpellScript(spell_mage_invisibility);
    RegisterSpellScript(spell_mage_ice_lance);
    RegisterSpellScript(spell_mage_summon_water_elemental);
    RegisterSpellScript(spell_mage_nether_tempest);
    RegisterSpellScript(spell_mage_presence_of_mind);
    RegisterSpellScript(spell_mage_touch_of_the_magi);
    RegisterSpellScript(spell_mage_cold_snap);
    RegisterSpellScript(spell_mage_blazing_barrier);
    RegisterSpellScript(spell_mage_prismatic_barrier);
    RegisterSpellScript(spell_mage_explosive_potential);
    RegisterSpellScript(spell_mage_thermal_void_1247730);
    RegisterSpellScript(spell_mage_frenetic_speed);
}
