/*
 * Generated spell scripts for Warrior
 * Auto-generated by generate_spell_fixes.py on 2026-03-07
 * Based on spell audit classification of YELLOW/RED spells
 *
 * These scripts handle passive DUMMY aura value consumption,
 * PERIODIC_DUMMY tick behavior, proc handlers, and active DUMMY effects.
 */

#include "Player.h"
#include "ScriptMgr.h"
#include "Spell.h"
#include "SpellAuraEffects.h"
#include "SpellAuras.h"
#include "SpellInfo.h"
#include "SpellScript.h"
#include "Unit.h"

// =====================================================================
// Spell ID Constants — Warrior
// =====================================================================

enum WarriorSpellIds
{
    SPELL_WARRIOR_WHIRLWIND                                           = 1680,
    SPELL_WARRIOR_EXECUTE                                             = 5308,
    SPELL_WARRIOR_SECOND_WIND                                         = 29838,
    SPELL_WARRIOR_SHOCKWAVE                                           = 46968,
    SPELL_WARRIOR_SHATTERING_THROW                                    = 64382,
    SPELL_WARRIOR_MASTERY_CRITICAL_BLOCK                              = 76857,
    SPELL_WARRIOR_TITANS_GRIP_SINGLEMINDED_FURY                       = 81099,
    SPELL_WARRIOR_RAGING_BLOW                                         = 85288,
    SPELL_WARRIOR_ANGER_MANAGEMENT                                    = 152278,
    SPELL_WARRIOR_RAMPAGE                                             = 184367,
    SPELL_WARRIOR_TACTICIAN                                           = 184783,
    SPELL_WARRIOR_WHIRLWIND_190411                                    = 190411,
    SPELL_WARRIOR_INDOMITABLE                                         = 202095,
    SPELL_WARRIOR_FURIOUS_CHARGE                                      = 202224,
    SPELL_WARRIOR_FERVOR_OF_BATTLE                                    = 202316,
    SPELL_WARRIOR_BEST_SERVED_COLD                                    = 202560,
    SPELL_WARRIOR_NEVER_SURRENDER                                     = 202561,
    SPELL_WARRIOR_INTO_THE_FRAY                                       = 202603,
    SPELL_WARRIOR_HEAVY_REPERCUSSIONS                                 = 203177,
    SPELL_WARRIOR_MASSACRE                                            = 206315,
    SPELL_WARRIOR_DREADNAUGHT                                         = 262150,
    SPELL_WARRIOR_STORM_SURGE                                         = 275336,
    SPELL_WARRIOR_SEASONED_SOLDIER                                    = 279423,
    SPELL_WARRIOR_BOLSTER                                             = 280001,
    SPELL_WARRIOR_SUDDEN_DEATH                                        = 280721,
    SPELL_WARRIOR_MASSACRE_281001                                     = 281001,
    SPELL_WARRIOR_COLLATERAL_DAMAGE                                   = 334779,
    SPELL_WARRIOR_CRUELTY                                             = 335070,
    SPELL_WARRIOR_SEETHE                                              = 335091,
    SPELL_WARRIOR_CHAMPIONS_SPEAR                                     = 376079,
    SPELL_WARRIOR_CHAMPIONS_SPEAR_376080                              = 376080,
    SPELL_WARRIOR_INSPIRING_PRESENCE                                  = 382310,
    SPELL_WARRIOR_CACOPHONOUS_ROAR                                    = 382954,
    SPELL_WARRIOR_SEISMIC_REVERBERATION                               = 382956,
    SPELL_WARRIOR_FUELED_BY_VIOLENCE                                  = 383103,
    SPELL_WARRIOR_BLOODLETTING                                        = 383154,
    SPELL_WARRIOR_EXHILARATING_BLOWS                                  = 383226,
    SPELL_WARRIOR_JUGGERNAUT                                          = 383292,
    SPELL_WARRIOR_MERCILESS_BONEGRINDER                               = 383317,
    SPELL_WARRIOR_FOCUS_IN_CHAOS                                      = 383486,
    SPELL_WARRIOR_FATAL_MARK                                          = 383704,
    SPELL_WARRIOR_HACK_AND_SLASH                                      = 383873,
    SPELL_WARRIOR_BRUTAL_VITALITY                                     = 384036,
    SPELL_WARRIOR_IMPENETRABLE_WALL                                   = 384072,
    SPELL_WARRIOR_BERSERKER_SHOUT                                     = 384100,
    SPELL_WARRIOR_ARMORED_TO_THE_TEETH                                = 384124,
    SPELL_WARRIOR_BLOOD_AND_THUNDER                                   = 384277,
    SPELL_WARRIOR_BLOODSURGE                                          = 384361,
    SPELL_WARRIOR_TEST_OF_MIGHT                                       = 385009,
    SPELL_WARRIOR_ODYNS_FURY                                          = 385059,
    SPELL_WARRIOR_THUNDERLORD                                         = 385840,
    SPELL_WARRIOR_TOUGH_AS_NAILS                                      = 385888,
    SPELL_WARRIOR_DEFENSIVE_STANCE                                    = 386208,
    SPELL_WARRIOR_BATTLESCARRED_VETERAN                               = 386394,
    SPELL_WARRIOR_VIOLENT_OUTBURST                                    = 386477,
    SPELL_WARRIOR_UNHINGED                                            = 386628,
    SPELL_WARRIOR_BATTLELORD                                          = 386632,
    SPELL_WARRIOR_TENDERIZE                                           = 388933,
    SPELL_WARRIOR_CRITICAL_THINKING                                   = 389306,
    SPELL_WARRIOR_UNBRIDLED_FEROCITY                                  = 389603,
    SPELL_WARRIOR_BERSERKERS_TORMENT                                  = 390123,
    SPELL_WARRIOR_TITANS_TORMENT                                      = 390135,
    SPELL_WARRIOR_BLADEMASTERS_TORMENT                                = 390138,
    SPELL_WARRIOR_WARLORDS_TORMENT                                    = 390140,
    SPELL_WARRIOR_HURRICANE                                           = 390563,
    SPELL_WARRIOR_HURRICANE_390567                                    = 390567,
    SPELL_WARRIOR_DANCE_OF_DEATH                                      = 390713,
    SPELL_WARRIOR_FROTHING_BERSERKER                                  = 392792,
    SPELL_WARRIOR_IMMOVABLE_OBJECT                                    = 394307,
    SPELL_WARRIOR_BATTLEFIELD_COMMANDER                               = 424742,
    SPELL_WARRIOR_DOMINANCE_OF_THE_COLOSSUS                           = 429636,
    SPELL_WARRIOR_ONE_AGAINST_MANY                                    = 429637,
    SPELL_WARRIOR_TIDE_OF_BATTLE                                      = 429641,
    SPELL_WARRIOR_LIGHTNING_STRIKES                                   = 434969,
    SPELL_WARRIOR_THUNDER_BLAST                                       = 435607,
    SPELL_WARRIOR_GROUND_CURRENT                                      = 436148,
    SPELL_WARRIOR_DEMOLISH                                            = 436358,
    SPELL_WARRIOR_FLASHING_SKIES                                      = 437079,
    SPELL_WARRIOR_BURST_OF_POWER                                      = 437121,
    SPELL_WARRIOR_AVATAR_OF_THE_STORM                                 = 437134,
    SPELL_WARRIOR_STORM_SHIELD                                        = 438597,
    SPELL_WARRIOR_ARTERIAL_BLEED                                      = 440995,
    SPELL_WARRIOR_SLAYERS_DOMINANCE                                   = 444767,
    SPELL_WARRIOR_IMMINENT_DEMISE                                     = 444769,
    SPELL_WARRIOR_DEATH_DRIVE                                         = 444770,
    SPELL_WARRIOR_SHOW_NO_MERCY                                       = 444771,
    SPELL_WARRIOR_OVERWHELMING_BLADES                                 = 444772,
    SPELL_WARRIOR_OPPORTUNIST                                         = 444774,
    SPELL_WARRIOR_REAP_THE_STORM                                      = 444775,
    SPELL_WARRIOR_RELENTLESS_PURSUIT                                  = 444776,
    SPELL_WARRIOR_VICIOUS_AGILITY                                     = 444777,
    SPELL_WARRIOR_CULLING_CYCLONE                                     = 444778,
    SPELL_WARRIOR_UNRELENTING_ONSLAUGHT                               = 444780,
    SPELL_WARRIOR_BRUTAL_FINISH                                       = 446085,
    SPELL_WARRIOR_SPELLBREAKER                                        = 1235023,
    SPELL_WARRIOR_HEAVY_HANDED                                        = 1235088,
    SPELL_WARRIOR_WHIRLING_BLADE                                      = 1235113,
    SPELL_WARRIOR_INTERPOSE                                           = 1244091,
    SPELL_WARRIOR_PROTECTION_WARRIOR                                  = 1258163,
    SPELL_WARRIOR_BRUTE_FORCE                                         = 1261046,
    SPELL_WARRIOR_JUST_WARMING_UP                                     = 1261048,
    SPELL_WARRIOR_BROAD_STROKES                                       = 1261049,
    SPELL_WARRIOR_TACTICAL_EDGE                                       = 1261185,
    SPELL_WARRIOR_DEVASTATING_FOCUS                                   = 1264330,
    SPELL_WARRIOR_MASTER_OF_WARFARE                                   = 1269306,
    SPELL_WARRIOR_MASTER_OF_WARFARE_1269307                           = 1269307,
    SPELL_WARRIOR_RAMPAGING_BERSERKER                                 = 1269309,
    SPELL_WARRIOR_RAMPAGING_BERSERKER_1269310                         = 1269310,
    SPELL_WARRIOR_DECIMATOR                                           = 1270704,
    SPELL_WARRIOR_CELERITOUS_CONCLUSION                               = 1270710,
    SPELL_WARRIOR_VIOLENT_EUPHORIA                                    = 1270717,
    SPELL_WARRIOR_CAPACITANCE                                         = 1270724,
    SPELL_WARRIOR_MASS_EXECUTION                                      = 1273075,
    SPELL_WARRIOR_IGNORE_PAIN                                         = 1277297,
    SPELL_WARRIOR_PHALANX                                             = 1278009,
    SPELL_WARRIOR_STANCE_MASTERY                                      = 1280961,
};

// =====================================================================
// Passive DUMMY — Modifier Buffs (19 spells)
// These passives store modifier values in DUMMY aura effects.
// The values need to be applied to affected spells via HandleProc
// or by modifying spell amounts in CalcAmount handlers.
// =====================================================================

// 76857 - Mastery: Critical Block
// Tooltip: "Increases your chance to block by ${$s2}.1% and your chance to critically block (blocking twice the amount) by ${$s1}.1%"
class spell_warrior_mastery_critical_block : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff2=150.0, eff3=0.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_mastery_critical_block::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_mastery_critical_block::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_mastery_critical_block::HandleApply, EFFECT_3, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_mastery_critical_block::HandleRemove, EFFECT_3, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 202095 - Indomitable
// Tooltip: "Your maximum health is increased by $s3% and every ${$s2/10} Rage you spend heals you for ${$s1/10}% of your maximum hea"
class spell_warrior_indomitable : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=10.0, eff1=150.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_indomitable::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_indomitable::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_indomitable::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_indomitable::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 206315 - Massacre
// Tooltip: "$?a317320[Condemn][Execute] is usable on targets below $s2% health and its cooldown is reduced by ${$s3/1000}.1 sec."
class spell_warrior_massacre_206315 : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff1=35.0, eff2=1500.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_massacre_206315::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_massacre_206315::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_massacre_206315::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_massacre_206315::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 280001 - Bolster
// Tooltip: "Last Stand's cooldown is reduced by ${$s1/-1000} sec and when Last Stand is triggered, you gain Shield Wall for ${$s2/10"
class spell_warrior_bolster : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff1=4000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_bolster::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_bolster::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 382954 - Cacophonous Roar
// Tooltip: "Intimidating Shout can withstand $s1% more damage before breaking."
class spell_warrior_cacophonous_roar : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=200.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_cacophonous_roar::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_cacophonous_roar::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 385840 - Thunderlord
// Tooltip: "Increases the radius of Demoralizing Shout by $s3 yards. Each enemy hit by Thunder Clap reduces the remaining cooldown o"
class spell_warrior_thunderlord : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=1500.0, eff1=3.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_thunderlord::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_thunderlord::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_thunderlord::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_thunderlord::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 386477 - Violent Outburst
// Tooltip: "Every $s1 rage you spend triggers a Violent Outburst, causing your next Shield Slam to deal $386478s1% increased damage,"
// SimC: Has proc/trigger behavior; Uses effect(s) 1, 2; Reads percentage value from effect; Buff interaction
class spell_warrior_violent_outburst : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=250.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_violent_outburst::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_violent_outburst::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 389306 - Critical Thinking
// Tooltip: "Execute critical strike chance increased by $s1% and Execute immediately refunds an additional $s2% of the Rage spent."
class spell_warrior_critical_thinking : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff1=10.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_critical_thinking::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_critical_thinking::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 389603 - Unbridled Ferocity
// Tooltip: "Rampage has a $s1% chance to grant Recklessness for ${$s2/1000} sec."
class spell_warrior_unbridled_ferocity : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=6.0, eff1=4000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_unbridled_ferocity::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_unbridled_ferocity::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_unbridled_ferocity::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_unbridled_ferocity::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 390123 - Berserker's Torment
// Tooltip: "Activating Avatar or Recklessness grants ${$s1/1000} sec of the other."
class spell_warrior_berserkers_torment : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=8000.0, eff1=8000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_berserkers_torment::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_berserkers_torment::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_berserkers_torment::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_berserkers_torment::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 390138 - Blademaster's Torment
// Tooltip: "Activating Avatar grants ${$s1/1000} sec of Sweeping Strikes and while Avatar is active the cooldown of Cleave is reduce"
class spell_warrior_blademasters_torment : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=8000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_blademasters_torment::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_blademasters_torment::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 390140 - Warlord's Torment
// Tooltip: "Activating Avatar grants ${$s1/1000} sec of Recklessness. The additional Rage generation of this Recklessness is reduced"
class spell_warrior_warlords_torment : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=6000.0, eff1=25.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_warlords_torment::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_warlords_torment::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_warlords_torment::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_warlords_torment::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 390713 - Dance of Death
// Tooltip: "$?c1[When an enemy dies while affected by your Bladestorm, all damage you deal is increased by $459572s1% for the remain"
class spell_warrior_dance_of_death : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=2000.0, eff1=3.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_dance_of_death::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_dance_of_death::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_dance_of_death::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_dance_of_death::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 394307 - Immovable Object
// Tooltip: "Activating Avatar or Shield Wall grants ${$s1/1000} sec of the other."
class spell_warrior_immovable_object : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=4000.0, eff1=4000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_immovable_object::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_immovable_object::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_immovable_object::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_immovable_object::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1235113 - Whirling Blade
// Tooltip: "Your attacks have a chance to target a nearby enemy with Ravager for ${$s1/1000} sec."
// SimC: Has proc/trigger behavior; Uses effect(s) 3; Reads percentage value from effect
class spell_warrior_whirling_blade : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=4000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_whirling_blade::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_whirling_blade::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1261048 - Just Warming Up
// Tooltip: "Colossus Smash generates ${$s1/10} Rage."
// SimC: Referenced in SimC (context needs manual review)
class spell_warrior_just_warming_up : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=150.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_just_warming_up::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_just_warming_up::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1269307 - Master of Warfare
// Tooltip: "Heroic Strike reduces the cooldown of Colossus Smash by ${$s1/-1000}.1 sec."
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Buff interaction: battlelord, colossal_might, colossus_
class spell_warrior_master_of_warfare_1269307 : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=-2000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_master_of_warfare_1269307::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_master_of_warfare_1269307::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1269309 - Rampaging Berserker
// Tooltip: "Rampage's Rage cost is reduced by ${$s1/-10} and damage is increased by a further $s2% during Recklessness."
class spell_warrior_rampaging_berserker_1269309 : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=-150.0, eff1=5.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_rampaging_berserker_1269309::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_rampaging_berserker_1269309::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_rampaging_berserker_1269309::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_rampaging_berserker_1269309::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1270724 - Capacitance
// Tooltip: "During Avatar, Thunder Blast extends Avatar's duration by ${$s1/1000}.1 sec."
// SimC: Spell initialization/registration only
class spell_warrior_capacitance : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=2000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_capacitance::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_capacitance::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// =====================================================================
// Passive DUMMY — Proc Handlers (6 spells)
// These passives proc on combat events and apply effects.
// =====================================================================

// 202561 - Never Surrender
// Tooltip: "Ignore Pain prevents $s1% to $s2% more damage, based on your missing health."
// ProcMask: 0
class spell_warrior_never_surrender : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=40.0, eff1=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_warrior_never_surrender::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_warrior_never_surrender::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 203177 - Heavy Repercussions
// Tooltip: "Shield Slam generates ${$s2/10} more Rage and extends the duration of Shield Block by ${$m1/100}.1 sec."
// ProcMask: 0
class spell_warrior_heavy_repercussions : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_warrior_heavy_repercussions::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// 280721 - Sudden Death
// Tooltip: "Your attacks have a chance to reset the cooldown of $?a317320[Condemn][Execute] and make it usable on any target, regard"
// ProcMask: 16
// SimC: Has proc/trigger behavior; Uses effect(s) 3; Reads percentage value from effect; Buff interaction: a
class spell_warrior_sudden_death : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=0.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_warrior_sudden_death::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// 386628 - Unhinged
// Tooltip: "Every $s1 strikes of Bladestorm, you automatically cast a $?c1[Mortal Strike][Bloodthirst] at your target or random near"
// ProcMask: 0
// SimC: Spell initialization/registration only
class spell_warrior_unhinged : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=2.0, eff1=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_warrior_unhinged::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_warrior_unhinged::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 444769 - Imminent Demise
// Tooltip: "Every $s1 Slayer's Strikes you gain Sudden Death. Using Sudden Death accelerates your next Bladestorm, striking 1 additi"
// ProcMask: 0
// SimC: Has proc/trigger behavior; Buff interaction: bladestorm, brutal_finish, executioner, fierce_followth
class spell_warrior_imminent_demise : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=3.0, eff1=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_warrior_imminent_demise::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_warrior_imminent_demise::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
    }
};

// 1270704 - Decimator
// Tooltip: "Demolish's final strike applies Deep Wounds to all targets, at $s1% effectiveness."
// ProcMask: 0
// SimC: Spell initialization/registration only
class spell_warrior_decimator : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_warrior_decimator::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// =====================================================================
// Passive DUMMY — Trigger Effects (1 spells)
// =====================================================================

// 202224 - Furious Charge
// Tooltip: "Charge also increases the healing from your next Bloodthirst by $202225s1%."
class spell_warrior_furious_charge : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Trigger spell on proc event
        // bp=eff0=0.0
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_warrior_furious_charge::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// =====================================================================
// Passive DUMMY — Other (58 spells)
// These need individual research to determine handler type.
// =====================================================================

// 81099 - Titan's Grip: Single-Minded Fury — bp=eff0=0.0
// "You can transmogrify your two-handed weapons to use one-handed weapon appearance"
class spell_warrior_titans_grip_singleminded_fury : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 152278 - Anger Management — bp=eff0=20.0, eff1=20.0, eff2=20.0
// "Every $?c1[$s1]?c2[$s3][$s2] Rage you spend$?c3[][ on attacks] reduces the remai"
// SimC: Spell initialization/registration only
class spell_warrior_anger_management : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 202316 - Fervor of Battle — bp=eff0=3.0, eff1=50.0
// "If Cleave or Whirlwind hits $s1 or more targets you also Slam your primary targe"
// SimC: Buff interaction: collateral_damage, executioners_precision, sudden_death; AoE o
class spell_warrior_fervor_of_battle : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 202560 - Best Served Cold — bp=eff2=20.0
// "Your dodges and parries make your Revenge cost no Rage $s3% more frequently and "
class spell_warrior_best_served_cold : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 262150 - Dreadnaught — bp=eff0=0.0
// "Overpower causes a seismic wave, dealing $315961s1 damage to all enemies in a $3"
// SimC: Buff interaction: collateral_damage, executioners_precision, sudden_death; AoE o
class spell_warrior_dreadnaught : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 275336 - Storm Surge — bp=eff0=0.0
// "Avatar increases the damage of Thunder Clap by $107574s9% and reduces its cooldo"
// SimC: Spell initialization/registration only
class spell_warrior_storm_surge : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 279423 - Seasoned Soldier — bp=eff0=10.0
// "Your auto attack critical strikes generate $s1% more Rage and damage taken from "
class spell_warrior_seasoned_soldier : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 281001 - Massacre — bp=eff1=35.0
// "$?a317320[Condemn][Execute] is usable on targets below $s2% health."
class spell_warrior_massacre_281001 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 334779 - Collateral Damage — bp=eff0=0.0
// "When an ability used during Sweeping Strikes damages a second target, your next "
// SimC: Used in mastery calculation; Has proc/trigger behavior; Uses effect(s) 1; Buff i
class spell_warrior_collateral_damage : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 335070 - Cruelty — bp=eff1=30.0
// "While Enraged, Raging Blow deals $s1% more damage and has a $s2% chance to insta"
class spell_warrior_cruelty : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 335091 - Seethe — bp=eff1=40.0
// "Bloodthirst generates ${$s1/10} more Rage, or ${$s2/10} more Rage when it critic"
class spell_warrior_seethe : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 382310 - Inspiring Presence — bp=eff2=5.0
// "Rallying Cry's duration is increased by ${$s1/1000} sec and it grants an additio"
class spell_warrior_inspiring_presence : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 382956 - Seismic Reverberation — bp=eff0=3.0, eff1=1.0
// "If Whirlwind $?c1[or Cleave ][]$?s436707[or Thunder Clap ][]$?a137048[or Revenge"
class spell_warrior_seismic_reverberation : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 383154 - Bloodletting — bp=eff2=35.0
// "Rend and Deep Wounds' Bleed effects last $s1% longer and have a $s2% increased c"
class spell_warrior_bloodletting : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 383292 - Juggernaut — bp=eff1=3.0
// "Execute increases Execute's damage dealt by $383290s1% for $383290d, stacking up"
class spell_warrior_juggernaut : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 383317 - Merciless Bonegrinder — bp=eff0=0.0
// "Whirlwind and Cleave deal $383316s1% increased damage for $<bstorm> sec after Bl"
class spell_warrior_merciless_bonegrinder : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 383486 - Focus in Chaos — bp=eff0=1.0
// "While Enraged, your auto-attacks can no longer miss."
// SimC: Spell initialization/registration only
class spell_warrior_focus_in_chaos : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 384072 - Impenetrable Wall — bp=eff0=6.0
// "Shield Slam reduces the remaining cooldown of Shield Wall by $s1 sec."
// SimC: Spell initialization/registration only
class spell_warrior_impenetrable_wall : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 384277 - Blood and Thunder — bp=eff0=5.0
// "Thunder Clap affects $s3 nearby targets with Rend, causing them to Bleed for $38"
class spell_warrior_blood_and_thunder : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 385888 - Tough as Nails — bp=eff0=0.0
// "Blocking an attack deals $385890s1 Physical damage to the attacker. Critical blo"
// SimC: Affects cooldown/recharge timing; Has duration or tick-time behavior; Referenced
class spell_warrior_tough_as_nails : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 386394 - Battle-Scarred Veteran — bp=eff0=30.0
// "When your health is brought below $s1%, you take $386397s1% less damage for $386"
class spell_warrior_battlescarred_veteran : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 388933 - Tenderize — bp=eff0=3.0
// "Onslaught Enrages you. If you have Slaughtering Strikes, it also grants you $s1 "
class spell_warrior_tenderize : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 390135 - Titan's Torment — bp=eff0=0.0
// "While Avatar is active Rampage's Rage cost is reduced by ${$107574s10/-10} and B"
class spell_warrior_titans_torment : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 390563 - Hurricane — bp=eff1=5.0
// "While Bladestorming or Ravager is active, you gain $s2% movement speed and $s1% "
class spell_warrior_hurricane_390563 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 392792 - Frothing Berserker — bp=eff0=10.0, eff1=10.0, eff2=50.0
// "$?c1[Mortal Strike and Cleave have]?c2[Rampage has][Revenge has] a $h% chance to"
// SimC: Referenced in SimC (context needs manual review)
class spell_warrior_frothing_berserker : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 424742 - Battlefield Commander — bp=eff5=3.0
// "Your Shout abilities have additional effects. $@spellicon6673 $@spellname6673: G"
class spell_warrior_battlefield_commander : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 5
    }
};

// 429636 - Dominance of the Colossus — bp=eff1=2.0
// "Colossal Might stacks up to 10 times. If you would gain a stack of Colossal Migh"
class spell_warrior_dominance_of_the_colossus : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 429637 - One Against Many — bp=eff0=5.0, eff1=5.0
// "Shockwave$?c1[, Cleave,][] and $?c1[Whirlwind][Revenge] deal $s1% more damage pe"
// SimC: Spell initialization/registration only
class spell_warrior_one_against_many : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 429641 - Tide of Battle — bp=eff0=0.0
// "Colossal Might increases the damage of your $?c1[Overpower][Revenge] by $?c1[$44"
// SimC: Spell initialization/registration only
class spell_warrior_tide_of_battle : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 434969 - Lightning Strikes — bp=eff0=25.0, eff1=30.0
// "Damaging enemies with Thunder Clap, $?a137048[Revenge, ][Raging Blow, ]or Execut"
// SimC: Buff interaction: recklessness
class spell_warrior_lightning_strikes : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 435607 - Thunder Blast — bp=eff0=35.0
// "Shield Slam and Bloodthirst have a $s1% chance to grant you Thunder Blast, stack"
class spell_warrior_thunder_blast : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 436148 - Ground Current — bp=eff0=0.0
// "Lightning Strikes also deal $460670s1 Nature damage to enemies near their target"
// SimC: Referenced in SimC (context needs manual review)
class spell_warrior_ground_current : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 437079 - Flashing Skies — bp=eff0=0.0
// "Thunder Blast calls down a Lightning Strike on an enemy it hits."
// SimC: Spell initialization/registration only
class spell_warrior_flashing_skies : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 437134 - Avatar of the Storm — bp=eff0=2.0, eff1=10.0, eff2=4.0
// "Casting Avatar grants you $s1 charges of Thunder Blast and resets the cooldown o"
class spell_warrior_avatar_of_the_storm : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 438597 - Storm Shield — bp=eff0=3.0
// "Intervening a target grants them a shield for $438598d that absorbs magic damage"
// SimC: Spell initialization/registration only
class spell_warrior_storm_shield : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 440995 - Arterial Bleed — bp=eff0=0.0
// "Colossal Might increases the damage of your Rend and Deep Wounds by $440989s2% p"
// SimC: Spell initialization/registration only
class spell_warrior_arterial_bleed : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 444770 - Death Drive — bp=eff0=15.0
// "You heal for $s1% of damage dealt by Sudden Death."
// SimC: Spell initialization/registration only
class spell_warrior_death_drive : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 444771 - Show No Mercy — bp=eff0=0.0
// "Executioner also increases your Execute critical strike chance and critical stri"
// SimC: Spell initialization/registration only
class spell_warrior_show_no_mercy : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 444772 - Overwhelming Blades — bp=eff0=0.0
// "Each strike of Bladestorm applies Overwhelmed to all enemies affected, increasin"
// SimC: Spell initialization/registration only
class spell_warrior_overwhelming_blades : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 444774 - Opportunist — bp=eff0=0.0
// "$?c1[When Overpower has its cooldown reset by Tactician, your next Overpower dea"
// SimC: Has proc/trigger behavior; Buff interaction: battlelord, brutal_finish, enrage, 
class spell_warrior_opportunist : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 444775 - Reap the Storm — bp=eff0=8.0, eff1=3.0, eff2=20.0, eff3=30.0
// "$?c1[Mortal Strike and Cleave when it hits $s2 or more targets have][Bloodthirst"
// SimC: Affects cooldown/recharge timing; Has duration or tick-time behavior; AoE or mul
class spell_warrior_reap_the_storm : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
        // TODO: Determine handler type for DUMMY effect 3
    }
};

// 444776 - Relentless Pursuit — bp=eff0=0.0
// "Charge increases your movement speed by $446044s1% for $446044d. Charge removes "
// SimC: Spell initialization/registration only
class spell_warrior_relentless_pursuit : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 444777 - Vicious Agility — bp=eff0=5.0, eff1=2.0
// "Heroic Leap reduces the cooldown of Charge by $s1 sec and Charge reduces the coo"
// SimC: Spell initialization/registration only
class spell_warrior_vicious_agility : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 444778 - Culling Cyclone — bp=eff0=20.0
// "Each strike of Bladestorm deals an additional $s1% damage evenly split across al"
// SimC: Spell initialization/registration only
class spell_warrior_culling_cyclone : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 444780 - Unrelenting Onslaught — bp=eff0=5.0, eff1=1.0
// "Using Sudden Death causes you to both reduce the cooldown of Bladestorm by $s1 s"
class spell_warrior_unrelenting_onslaught : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 446085 - Brutal Finish — bp=eff0=0.0
// "Your next $?c1[Mortal Strike][Rampage] after Bladestorm ends deals $?c1[$446918s"
// SimC: Has proc/trigger behavior; Uses effect(s) 5, 9; Buff interaction: brutal_finish,
class spell_warrior_brutal_finish : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1235023 - Spellbreaker — bp=eff1=8.0, eff2=50.0
// "You have a $s2% chance to disrupt magic damage dealt to you, reducing the damage"
class spell_warrior_spellbreaker : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 1235088 - Heavy Handed — bp=eff1=70.0
// "Execute hits up to $s1 additional $Ltarget:targets; for $s2% damage."
class spell_warrior_heavy_handed : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1258163 - Protection Warrior — bp=eff10=10.0, eff13=0.0, eff14=-33.0
class spell_warrior_protection_warrior : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 10
        // TODO: Determine handler type for DUMMY effect 13
        // TODO: Determine handler type for DUMMY effect 14
    }
};

// 1261046 - Brute Force — bp=eff0=10.0
// "Slam has a 10% increased chance to trigger Tactician."
// SimC: Spell initialization/registration only
class spell_warrior_brute_force : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1261049 - Broad Strokes — bp=eff0=0.0
// "Colossus Smash grants you Sweeping Strikes."
// SimC: Buff interaction: avatar, bladestorm, colossus_smash, sweeping_strikes; Debuff i
class spell_warrior_broad_strokes : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1264330 - Devastating Focus — bp=eff0=0.0
// "You focus on the target struck by your Devastator, dealing $1277983s1% additiona"
// SimC: Referenced in SimC source
class spell_warrior_devastating_focus : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1269306 - Master of Warfare — bp=eff0=25.0, eff1=25.0
// "Each stack of Master of Warfare increases Mortal Strike, Cleave, and Overpower d"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Buff interaction: battlelord, colos
class spell_warrior_master_of_warfare_1269306 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1269310 - Rampaging Berserker — bp=eff1=3.0
// "Recklessness grants $s2 stacks of Berserk and duration of Recklessness increased"
class spell_warrior_rampaging_berserker_1269310 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1270710 - Celeritous Conclusion — bp=eff0=0.0
// "Demolish's final strike grants $1270843s1% Haste for $1270843d and increases the"
// SimC: Spell initialization/registration only
class spell_warrior_celeritous_conclusion : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1270717 - Violent Euphoria — bp=eff0=0.0
// "Bladestorm puts you into a battle trance, granting you 15% haste for 8 sec after"
// SimC: Has proc/trigger behavior; Buff interaction: brutal_finish, celeritous_conclusio
class spell_warrior_violent_euphoria : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1273075 - Mass Execution — bp=eff0=20.0, eff1=35.0
// "Cleave and Whirlwind deal $s1% additional damage to targets below $s2% health."
// SimC: Spell initialization/registration only
class spell_warrior_mass_execution : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1280961 - Stance Mastery — bp=eff0=0.0
// "Your stances have additional effects. $?c1|c3[$@spellicon386164 $@spellname38616"
// SimC: Spell initialization/registration only
class spell_warrior_stance_mastery : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// =====================================================================
// PERIODIC_DUMMY — Tick Handlers (7 spells)
// =====================================================================

// 29838 - Second Wind
// "Restores $202147s1% health every $202147t1 sec when you have not taken damage for ${$s1/1000} sec. Restores $458245s3% h"
class spell_warrior_second_wind : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_warrior_second_wind::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 202603 - Into the Fray
// "You gain $202602s1% Haste for each enemy or ally within $s1 yards, up to ${$202602s1*$202602u}% Haste."
class spell_warrior_into_the_fray : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_warrior_into_the_fray::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 383103 - Fueled by Violence
// "You are healed for $s1% of the Bleed damage dealt by Rend and Deep Wounds."
class spell_warrior_fueled_by_violence : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_warrior_fueled_by_violence::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 384036 - Brutal Vitality
// "$s1% of damage you deal adds to your active Ignore Pain or the next Ignore Pain you activate. Your next Ignore Pain can "
class spell_warrior_brutal_vitality : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=eff1=50.0
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_warrior_brutal_vitality::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 384124 - Armored to the Teeth
// "Gain Strength equal to $?c3[$s3][$s2]% of your Armor."
class spell_warrior_armored_to_the_teeth : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_warrior_armored_to_the_teeth::HandlePeriodic, EFFECT_1, SPELL_AURA_PERIODIC_DUMMY);
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_warrior_armored_to_the_teeth::HandlePeriodic, EFFECT_2, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 384361 - Bloodsurge
// "Damage from Rend has a chance to generate ${$384362s1/10} Rage."
class spell_warrior_bloodsurge : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_warrior_bloodsurge::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 436358 - Demolish
// "Unleash a series of precise and powerful strikes against your target, dealing ${$440884s1+$440886s1+$440888s1} damage to"
class spell_warrior_demolish : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_warrior_demolish::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// =====================================================================
// Active DUMMY — HandleDummy (14 spells)
// =====================================================================

// 46968 - Shockwave
// "Sends a wave of force in a frontal cone, causing $s1 damage and stunning all enemies within $a1 yards for $132168d."
class spell_warrior_shockwave : public SpellScript
{
    void HandleDummy(SpellEffIndex /*effIndex*/)
    {
        // TODO: Implement active DUMMY effect behavior
    }

    void Register() override
    {
        OnEffectHitTarget += SpellEffectFn(spell_warrior_shockwave::HandleDummy, EFFECT_0, SPELL_EFFECT_DUMMY);
    }
};

// 376080 - Champion's Spear
// "$@spelldesc376079"
class spell_warrior_champions_spear_376080 : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_champions_spear_376080::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_champions_spear_376080::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 383226 - Exhilarating Blows
// "Mortal Strike and Cleave have a $383219h% chance to instantly reset their own cooldowns."
class spell_warrior_exhilarating_blows : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_exhilarating_blows::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_exhilarating_blows::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 383704 - Fatal Mark
// "$@spelldesc383703"
class spell_warrior_fatal_mark : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_fatal_mark::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_fatal_mark::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 383873 - Hack and Slash
// "$@spelldesc383877"
class spell_warrior_hack_and_slash : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_hack_and_slash::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_hack_and_slash::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 385009 - Test of Might
// "$@spelldesc385008"
class spell_warrior_test_of_might : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_test_of_might::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_test_of_might::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 386208 - Defensive Stance
// "A defensive combat state that reduces all damage you take by $s1%$?a452494[ and all magic damage you take by an addition"
class spell_warrior_defensive_stance : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_defensive_stance::HandleApply, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_defensive_stance::HandleRemove, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_defensive_stance::HandleApply, EFFECT_5, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_defensive_stance::HandleRemove, EFFECT_5, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 386632 - Battlelord
// "$@spelldesc386630"
class spell_warrior_battlelord : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_battlelord::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_battlelord::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 390567 - Hurricane
// "@spelldesc390563"
class spell_warrior_hurricane_390567 : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_hurricane_390567::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_hurricane_390567::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 437121 - Burst of Power
// "$@spelldesc437118"
class spell_warrior_burst_of_power : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_burst_of_power::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_burst_of_power::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1244091 - Interpose
// "$@spelldesc1244088"
class spell_warrior_interpose : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_interpose::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_interpose::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1261185 - Tactical Edge
// "$@spelldesc1261051"
class spell_warrior_tactical_edge : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_tactical_edge::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_tactical_edge::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1277297 - Ignore Pain
// "Fight through the pain, ignoring $s2% of damage taken for $d sec or until ${($s1)*(1+$@versadmg)} damage has been preven"
class spell_warrior_ignore_pain : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_ignore_pain::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_ignore_pain::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_ignore_pain::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_ignore_pain::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1278009 - Phalanx
// "Your next Shield Slam will trigger Phalanx."
class spell_warrior_phalanx : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_warrior_phalanx::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_warrior_phalanx::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// =====================================================================
// Proc Trigger Spells — Primarily need spell_proc SQL (2 spells)
// Some may also need C++ CheckProc/OnProc handlers
// =====================================================================

// 184783 - Tactician — needs spell_proc SQL entry + possibly C++ proc filter
class spell_warrior_tactician : public AuraScript
{
    bool CheckProc(ProcEventInfo& eventInfo)
    {
        // TODO: Validate proc conditions
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
    }

    void Register() override
    {
        DoCheckProc += AuraCheckProcFn(spell_warrior_tactician::CheckProc);
        OnEffectProc += AuraEffectProcFn(spell_warrior_tactician::HandleProc, EFFECT_0, SPELL_AURA_PROC_TRIGGER_SPELL);
    }
};

// 444767 - Slayer's Dominance — needs spell_proc SQL entry + possibly C++ proc filter
class spell_warrior_slayers_dominance : public AuraScript
{
    bool CheckProc(ProcEventInfo& eventInfo)
    {
        // TODO: Validate proc conditions
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
    }

    void Register() override
    {
        DoCheckProc += AuraCheckProcFn(spell_warrior_slayers_dominance::CheckProc);
        OnEffectProc += AuraEffectProcFn(spell_warrior_slayers_dominance::HandleProc, EFFECT_0, SPELL_AURA_PROC_TRIGGER_SPELL);
    }
};

// =====================================================================
// Script Registration
// =====================================================================

void AddSC_warrior_spell_audit()
{
    RegisterSpellScript(spell_warrior_mastery_critical_block);
    RegisterSpellScript(spell_warrior_indomitable);
    RegisterSpellScript(spell_warrior_massacre_206315);
    RegisterSpellScript(spell_warrior_bolster);
    RegisterSpellScript(spell_warrior_cacophonous_roar);
    RegisterSpellScript(spell_warrior_thunderlord);
    RegisterSpellScript(spell_warrior_violent_outburst);
    RegisterSpellScript(spell_warrior_critical_thinking);
    RegisterSpellScript(spell_warrior_unbridled_ferocity);
    RegisterSpellScript(spell_warrior_berserkers_torment);
    RegisterSpellScript(spell_warrior_blademasters_torment);
    RegisterSpellScript(spell_warrior_warlords_torment);
    RegisterSpellScript(spell_warrior_dance_of_death);
    RegisterSpellScript(spell_warrior_immovable_object);
    RegisterSpellScript(spell_warrior_whirling_blade);
    RegisterSpellScript(spell_warrior_just_warming_up);
    RegisterSpellScript(spell_warrior_master_of_warfare_1269307);
    RegisterSpellScript(spell_warrior_rampaging_berserker_1269309);
    RegisterSpellScript(spell_warrior_capacitance);
    RegisterSpellScript(spell_warrior_never_surrender);
    RegisterSpellScript(spell_warrior_heavy_repercussions);
    RegisterSpellScript(spell_warrior_sudden_death);
    RegisterSpellScript(spell_warrior_unhinged);
    RegisterSpellScript(spell_warrior_imminent_demise);
    RegisterSpellScript(spell_warrior_decimator);
    RegisterSpellScript(spell_warrior_furious_charge);
    RegisterSpellScript(spell_warrior_titans_grip_singleminded_fury);
    RegisterSpellScript(spell_warrior_anger_management);
    RegisterSpellScript(spell_warrior_fervor_of_battle);
    RegisterSpellScript(spell_warrior_best_served_cold);
    RegisterSpellScript(spell_warrior_dreadnaught);
    RegisterSpellScript(spell_warrior_storm_surge);
    RegisterSpellScript(spell_warrior_seasoned_soldier);
    RegisterSpellScript(spell_warrior_massacre_281001);
    RegisterSpellScript(spell_warrior_collateral_damage);
    RegisterSpellScript(spell_warrior_cruelty);
    RegisterSpellScript(spell_warrior_seethe);
    RegisterSpellScript(spell_warrior_inspiring_presence);
    RegisterSpellScript(spell_warrior_seismic_reverberation);
    RegisterSpellScript(spell_warrior_bloodletting);
    RegisterSpellScript(spell_warrior_juggernaut);
    RegisterSpellScript(spell_warrior_merciless_bonegrinder);
    RegisterSpellScript(spell_warrior_focus_in_chaos);
    RegisterSpellScript(spell_warrior_impenetrable_wall);
    RegisterSpellScript(spell_warrior_blood_and_thunder);
    RegisterSpellScript(spell_warrior_tough_as_nails);
    RegisterSpellScript(spell_warrior_battlescarred_veteran);
    RegisterSpellScript(spell_warrior_tenderize);
    RegisterSpellScript(spell_warrior_titans_torment);
    RegisterSpellScript(spell_warrior_hurricane_390563);
    RegisterSpellScript(spell_warrior_frothing_berserker);
    RegisterSpellScript(spell_warrior_battlefield_commander);
    RegisterSpellScript(spell_warrior_dominance_of_the_colossus);
    RegisterSpellScript(spell_warrior_one_against_many);
    RegisterSpellScript(spell_warrior_tide_of_battle);
    RegisterSpellScript(spell_warrior_lightning_strikes);
    RegisterSpellScript(spell_warrior_thunder_blast);
    RegisterSpellScript(spell_warrior_ground_current);
    RegisterSpellScript(spell_warrior_flashing_skies);
    RegisterSpellScript(spell_warrior_avatar_of_the_storm);
    RegisterSpellScript(spell_warrior_storm_shield);
    RegisterSpellScript(spell_warrior_arterial_bleed);
    RegisterSpellScript(spell_warrior_death_drive);
    RegisterSpellScript(spell_warrior_show_no_mercy);
    RegisterSpellScript(spell_warrior_overwhelming_blades);
    RegisterSpellScript(spell_warrior_opportunist);
    RegisterSpellScript(spell_warrior_reap_the_storm);
    RegisterSpellScript(spell_warrior_relentless_pursuit);
    RegisterSpellScript(spell_warrior_vicious_agility);
    RegisterSpellScript(spell_warrior_culling_cyclone);
    RegisterSpellScript(spell_warrior_unrelenting_onslaught);
    RegisterSpellScript(spell_warrior_brutal_finish);
    RegisterSpellScript(spell_warrior_spellbreaker);
    RegisterSpellScript(spell_warrior_heavy_handed);
    RegisterSpellScript(spell_warrior_protection_warrior);
    RegisterSpellScript(spell_warrior_brute_force);
    RegisterSpellScript(spell_warrior_broad_strokes);
    RegisterSpellScript(spell_warrior_devastating_focus);
    RegisterSpellScript(spell_warrior_master_of_warfare_1269306);
    RegisterSpellScript(spell_warrior_rampaging_berserker_1269310);
    RegisterSpellScript(spell_warrior_celeritous_conclusion);
    RegisterSpellScript(spell_warrior_violent_euphoria);
    RegisterSpellScript(spell_warrior_mass_execution);
    RegisterSpellScript(spell_warrior_stance_mastery);
    RegisterSpellScript(spell_warrior_second_wind);
    RegisterSpellScript(spell_warrior_into_the_fray);
    RegisterSpellScript(spell_warrior_fueled_by_violence);
    RegisterSpellScript(spell_warrior_brutal_vitality);
    RegisterSpellScript(spell_warrior_armored_to_the_teeth);
    RegisterSpellScript(spell_warrior_bloodsurge);
    RegisterSpellScript(spell_warrior_demolish);
    RegisterSpellScript(spell_warrior_shockwave);
    RegisterSpellScript(spell_warrior_champions_spear_376080);
    RegisterSpellScript(spell_warrior_exhilarating_blows);
    RegisterSpellScript(spell_warrior_fatal_mark);
    RegisterSpellScript(spell_warrior_hack_and_slash);
    RegisterSpellScript(spell_warrior_test_of_might);
    RegisterSpellScript(spell_warrior_defensive_stance);
    RegisterSpellScript(spell_warrior_battlelord);
    RegisterSpellScript(spell_warrior_hurricane_390567);
    RegisterSpellScript(spell_warrior_burst_of_power);
    RegisterSpellScript(spell_warrior_interpose);
    RegisterSpellScript(spell_warrior_tactical_edge);
    RegisterSpellScript(spell_warrior_ignore_pain);
    RegisterSpellScript(spell_warrior_phalanx);
    RegisterSpellScript(spell_warrior_tactician);
    RegisterSpellScript(spell_warrior_slayers_dominance);
}
