/*
 * Generated spell scripts for Rogue
 * Auto-generated by generate_spell_fixes.py on 2026-03-07
 * Based on spell audit classification of YELLOW/RED spells
 *
 * These scripts handle passive DUMMY aura value consumption,
 * PERIODIC_DUMMY tick behavior, proc handlers, and active DUMMY effects.
 */

#include "Player.h"
#include "ScriptMgr.h"
#include "Spell.h"
#include "SpellAuraEffects.h"
#include "SpellAuras.h"
#include "SpellInfo.h"
#include "SpellScript.h"
#include "Unit.h"

// =====================================================================
// Spell ID Constants — Rogue
// =====================================================================

enum RogueSpellIds
{
    SPELL_ROGUE_GARROTE                                               = 703,
    SPELL_ROGUE_MUTILATE                                              = 1329,
    SPELL_ROGUE_RUPTURE                                               = 1943,
    SPELL_ROGUE_RUTHLESSNESS                                          = 14161,
    SPELL_ROGUE_SEAL_FATE                                             = 14190,
    SPELL_ROGUE_ENVENOM                                               = 32645,
    SPELL_ROGUE_CUT_TO_THE_CHASE                                      = 51667,
    SPELL_ROGUE_RELENTLESS_STRIKES                                    = 58423,
    SPELL_ROGUE_FIND_WEAKNESS                                         = 91023,
    SPELL_ROGUE_SUBTERFUGE                                            = 108208,
    SPELL_ROGUE_SHADOW_BLADES                                         = 121471,
    SPELL_ROGUE_MARKED_FOR_DEATH                                      = 140149,
    SPELL_ROGUE_VENOM_RUSH                                            = 152152,
    SPELL_ROGUE_DEEPER_STRATAGEM                                      = 193531,
    SPELL_ROGUE_WEAPONMASTER                                          = 193537,
    SPELL_ROGUE_ALACRITY                                              = 193539,
    SPELL_ROGUE_ELABORATE_PLANNING                                    = 193640,
    SPELL_ROGUE_HIT_AND_RUN                                           = 196922,
    SPELL_ROGUE_MASTER_OF_SHADOWS                                     = 196976,
    SPELL_ROGUE_ENVELOPING_SHADOWS                                    = 238104,
    SPELL_ROGUE_POISON_BOMB                                           = 255544,
    SPELL_ROGUE_MASTER_ASSASSIN                                       = 255989,
    SPELL_ROGUE_LOADED_DICE                                           = 256171,
    SPELL_ROGUE_HIDDEN_BLADES                                         = 270061,
    SPELL_ROGUE_DANCING_STEEL                                         = 272026,
    SPELL_ROGUE_OPPORTUNITY                                           = 279876,
    SPELL_ROGUE_MASTERY_POTENT_ASSASSIN                               = 319473,
    SPELL_ROGUE_IMPROVED_BACKSTAB                                     = 319949,
    SPELL_ROGUE_IMPROVED_SHURIKEN_STORM                               = 319951,
    SPELL_ROGUE_BLINDSIDE                                             = 328085,
    SPELL_ROGUE_DEATHMARK                                             = 360194,
    SPELL_ROGUE_INTERNAL_BLEEDING                                     = 381627,
    SPELL_ROGUE_INTENT_TO_KILL                                        = 381630,
    SPELL_ROGUE_FLYING_DAGGERS                                        = 381631,
    SPELL_ROGUE_LETHAL_DOSE                                           = 381640,
    SPELL_ROGUE_SYSTEMIC_FAILURE                                      = 381652,
    SPELL_ROGUE_DOOMBLADE                                             = 381673,
    SPELL_ROGUE_ZOLDYCK_RECIPE                                        = 381798,
    SPELL_ROGUE_SCENT_OF_BLOOD                                        = 381799,
    SPELL_ROGUE_DRAGONTEMPERED_BLADES                                 = 381801,
    SPELL_ROGUE_ACE_UP_YOUR_SLEEVE                                    = 381828,
    SPELL_ROGUE_SLEIGHT_OF_HAND                                       = 381839,
    SPELL_ROGUE_AUDACITY                                              = 381845,
    SPELL_ROGUE_FAN_THE_HAMMER                                        = 381846,
    SPELL_ROGUE_DEFT_MANEUVERS                                        = 381878,
    SPELL_ROGUE_SWIFT_SLASHER                                         = 381988,
    SPELL_ROGUE_SUMMARILY_DISPATCHED                                  = 381990,
    SPELL_ROGUE_THE_FIRST_DANCE                                       = 382505,
    SPELL_ROGUE_PLANNED_EXECUTION                                     = 382508,
    SPELL_ROGUE_SHADOWED_FINISHERS                                    = 382511,
    SPELL_ROGUE_FADE_TO_NOTHING                                       = 382514,
    SPELL_ROGUE_PERFORATED_VEINS                                      = 382518,
    SPELL_ROGUE_LINGERING_SHADOW                                      = 382524,
    SPELL_ROGUE_FINALITY                                              = 382525,
    SPELL_ROGUE_DANSE_MACABRE                                         = 382528,
    SPELL_ROGUE_HIDDEN_OPPORTUNITY                                    = 383281,
    SPELL_ROGUE_KINGSBANE                                             = 385627,
    SPELL_ROGUE_SILENT_STORM                                          = 385722,
    SPELL_ROGUE_SECRET_STRATAGEM                                      = 394320,
    SPELL_ROGUE_DEVIOUS_STRATAGEM                                     = 394321,
    SPELL_ROGUE_IMPROVED_ADRENALINE_RUSH                              = 395422,
    SPELL_ROGUE_SUDDEN_DEMISE                                         = 423136,
    SPELL_ROGUE_WARNING_SIGNS                                         = 426555,
    SPELL_ROGUE_GOREMAWS_BITE                                         = 426591,
    SPELL_ROGUE_SHADOWCRAFT                                           = 426594,
    SPELL_ROGUE_TERRIFYING_PACE                                       = 428387,
    SPELL_ROGUE_EXHILARATING_EXECUTION                                = 428486,
    SPELL_ROGUE_UNSEEN_BLADE                                          = 441146,
    SPELL_ROGUE_DEVIOUS_DISTRACTIONS                                  = 441263,
    SPELL_ROGUE_DISORIENTING_STRIKES                                  = 441274,
    SPELL_ROGUE_FLAWLESS_FORM                                         = 441321,
    SPELL_ROGUE_FLICKERSTRIKE                                         = 441359,
    SPELL_ROGUE_NIMBLE_FLURRY                                         = 441367,
    SPELL_ROGUE_SO_TRICKY                                             = 441403,
    SPELL_ROGUE_COUP_DE_GRACE                                         = 441423,
    SPELL_ROGUE_CLOUD_COVER                                           = 441429,
    SPELL_ROGUE_HAND_OF_FATE                                          = 452536,
    SPELL_ROGUE_MEAN_STREAK                                           = 453428,
    SPELL_ROGUE_EDGE_CASE                                             = 453457,
    SPELL_ROGUE_TEMPTED_FATE                                          = 454286,
    SPELL_ROGUE_DEAL_FATE                                             = 454419,
    SPELL_ROGUE_INEXORABLE_MARCH                                      = 454432,
    SPELL_ROGUE_DEATHS_ARRIVAL                                        = 454433,
    SPELL_ROGUE_DESTINY_DEFINED                                       = 454435,
    SPELL_ROGUE_DEATHSTALKERS_MARK                                    = 457052,
    SPELL_ROGUE_HUNT_THEM_DOWN                                        = 457054,
    SPELL_ROGUE_SINGULAR_FOCUS                                        = 457055,
    SPELL_ROGUE_LINGERING_DARKNESS                                    = 457056,
    SPELL_ROGUE_SHADEWALKER                                           = 457057,
    SPELL_ROGUE_DARKEST_NIGHT                                         = 457058,
    SPELL_ROGUE_FOLLOW_THE_BLOOD                                      = 457068,
    SPELL_ROGUE_SANGUINE_STRATAGEM                                    = 457512,
    SPELL_ROGUE_THISTLE_TEA                                           = 469779,
    SPELL_ROGUE_SUPERCHARGER                                          = 470347,
    SPELL_ROGUE_FORCED_INDUCTION                                      = 470668,
    SPELL_ROGUE_ECHOING_REPRIMAND                                     = 470669,
    SPELL_ROGUE_ROLL_THE_BONES                                        = 1214909,
    SPELL_ROGUE_UNSHAKEABLE_DRIVE                                     = 1248774,
    SPELL_ROGUE_LUCKY_COIN                                            = 1248970,
    SPELL_ROGUE_OVERFLOWING_PURSE                                     = 1249190,
    SPELL_ROGUE_DELIVERED_DOOM                                        = 1249194,
    SPELL_ROGUE_CHOSENS_REVELRY                                       = 1249201,
    SPELL_ROGUE_RUSH_TO_THE_INEVITABLE                                = 1249204,
    SPELL_ROGUE_FINISH_THE_JOB                                        = 1249809,
    SPELL_ROGUE_INSPIRING_STRIKE                                      = 1250036,
    SPELL_ROGUE_SECONDARY_POISONING                                   = 1250141,
    SPELL_ROGUE_REGICIDES_REWARD                                      = 1250325,
    SPELL_ROGUE_DEADLY_PURSUIT                                        = 1259612,
    SPELL_ROGUE_SHURIKEN_TORNADO                                      = 1264764,
    SPELL_ROGUE_IMPLACABLE                                            = 1265385,
    SPELL_ROGUE_IMPLACABLE_1265387                                    = 1265387,
    SPELL_ROGUE_GRAVEDIGGER                                           = 1265861,
    SPELL_ROGUE_GRAVEDIGGER_1265863                                   = 1265863,
    SPELL_ROGUE_POTENT_POWDER                                         = 1265952,
    SPELL_ROGUE_DANGER_SENSE                                          = 1267220,
    SPELL_ROGUE_ANCIENT_ARTS                                          = 1268932,
    SPELL_ROGUE_ANCIENT_ARTS_1268936                                  = 1268936,
    SPELL_ROGUE_ANCIENT_ARTS_1268939                                  = 1268939,
    SPELL_ROGUE_DEEPENING_SHADOWS                                     = 1271702,
    SPELL_ROGUE_PRECISE_KILLER                                        = 1272989,
    SPELL_ROGUE_QUIETUS_CELERIS                                       = 1273017,
    SPELL_ROGUE_MASS_CASUALTY                                         = 1273035,
    SPELL_ROGUE_FLASHING_STEEL                                        = 1276630,
    SPELL_ROGUE_RAVENHOLDT_MINT                                       = 1276809,
    SPELL_ROGUE_CONTROLLED_CHAOS                                      = 1276816,
    SPELL_ROGUE_SHURIKEN_STORM                                        = 1279401,
    SPELL_ROGUE_UMBRAL_EDGE                                           = 1281468,
};

// =====================================================================
// Passive DUMMY — Modifier Buffs (8 spells)
// These passives store modifier values in DUMMY aura effects.
// The values need to be applied to affected spells via HandleProc
// or by modifying spell amounts in CalcAmount handlers.
// =====================================================================

// 108208 - Subterfuge
// Tooltip: "Abilities requiring Stealth can be used for $?a137035[${$s4/1000}][${$s2/1000}] sec after Stealth breaks. Combat benefit"
class spell_rogue_subterfuge : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff3=2000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_subterfuge::HandleApply, EFFECT_3, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_subterfuge::HandleRemove, EFFECT_3, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 193531 - Deeper Stratagem
// Tooltip: "Gain $s1 additional max combo point. Your finishing moves that consume more than $s3 combo points have increased effects"
class spell_rogue_deeper_stratagem : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff2=5.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_deeper_stratagem::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_deeper_stratagem::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 319473 - Mastery: Potent Assassin
// Tooltip: "Mastery: Potent Assassin also increases damage of your bleeds."
class spell_rogue_mastery_potent_assassin : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=0.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_mastery_potent_assassin::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_mastery_potent_assassin::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 319949 - Improved Backstab
// Tooltip: "$?s200758[Gloomblade][Backstab] has $s2% increased critical strike chance. While behind your target, Backstab critical s"
class spell_rogue_improved_backstab : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=10.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_improved_backstab::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_improved_backstab::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 319951 - Improved Shuriken Storm
// Tooltip: "Shuriken Storm has $s2% increased critical strike chance. Shuriken Storm critical strikes grant Find Weakness for $s1 se"
class spell_rogue_improved_shuriken_storm : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=10.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_improved_shuriken_storm::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_improved_shuriken_storm::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 395422 - Improved Adrenaline Rush
// Tooltip: "Generate full combo points when you gain Adrenaline Rush."
// SimC: Buff interaction: adrenaline_rush, blade_flurry, loaded_dice, roll_the_bones; Affects cooldown/recha
class spell_rogue_improved_adrenaline_rush : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=0.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_improved_adrenaline_rush::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_improved_adrenaline_rush::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 441146 - Unseen Blade
// Tooltip: "$?a137036[Sinister Strike]?s200758[Gloomblade][Backstab] and $?a137036[Ambush][Shadowstrike] now also strike with an Uns"
// SimC: Buff interaction: ancient_arts, darkest_night, shadow_blades, shadow_dance, shadow_techniques; Affec
class spell_rogue_unseen_blade : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=10000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_unseen_blade::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_unseen_blade::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 457057 - Shadewalker
// Tooltip: "Each time you consume a stack of Deathstalker's Mark, reduce the cooldown of Shadowstep by ${$s1/-1000} sec."
// SimC: Spell initialization/registration only
class spell_rogue_shadewalker : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleApply(AuraEffect const* aurEff, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Apply modifier from aurEff->GetAmount()
        // Effect stores: bp=eff0=-3000.0
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Remove modifier
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_shadewalker::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_shadewalker::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// =====================================================================
// Passive DUMMY — Proc Handlers (4 spells)
// These passives proc on combat events and apply effects.
// =====================================================================

// 14190 - Seal Fate
// Tooltip: "Critical strikes with attacks that generate combo points grant an additional combo point per critical strike."
// ProcMask: 87376
class spell_rogue_seal_fate : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_rogue_seal_fate::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// 385722 - Silent Storm
// Tooltip: "Gaining Stealth, Vanish, or Shadow Dance causes your next Shuriken Storm to have $385727s1% increased chance to critical"
// ProcMask: 0
// SimC: Has proc/trigger behavior; Has duration or tick-time behavior; Participates in stat scaling; Referen
class spell_rogue_silent_storm : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_rogue_silent_storm::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// 423136 - Sudden Demise
// Tooltip: "Bleed damage increased by $s1%. Targets below $s3% health instantly bleed out and take fatal damage when the remaining B"
// ProcMask: 262144
class spell_rogue_sudden_demise : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff1=150.0, eff2=35.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_rogue_sudden_demise::HandleProc, EFFECT_1, SPELL_AURA_DUMMY);
        OnEffectProc += AuraEffectProcFn(spell_rogue_sudden_demise::HandleProc, EFFECT_2, SPELL_AURA_DUMMY);
    }
};

// 1279401 - Shuriken Storm
// Tooltip: "Shuriken Storm damage is increased by $s1% while Stealthed."
// ProcMask: 0
// SimC: Involves resource gain/cost; Referenced in SimC (context needs manual review)
class spell_rogue_shuriken_storm : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Implement proc behavior
        // DUMMY bp=eff0=100.0
        // Chance/amount from aurEff->GetAmount()
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_rogue_shuriken_storm::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// =====================================================================
// Passive DUMMY — Trigger Effects (2 spells)
// =====================================================================

// 58423 - Relentless Strikes
// Tooltip: "Your finishing moves generate $98440s2 Energy per combo point spent."
class spell_rogue_relentless_strikes : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Trigger spell on proc event
        // bp=eff0=0.0
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_rogue_relentless_strikes::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// 152152 - Venom Rush
// Tooltip: "Ambush and Mutilate refund $256522s1 Energy when used against a poisoned target."
class spell_rogue_venom_rush : public AuraScript
{
    bool Validate(SpellInfo const* /*spellInfo*/) override
    {
        return true;
    }

    void HandleProc(AuraEffect* aurEff, ProcEventInfo& eventInfo)
    {
        // TODO: Trigger spell on proc event
        // bp=eff0=0.0
    }

    void Register() override
    {
        OnEffectProc += AuraEffectProcFn(spell_rogue_venom_rush::HandleProc, EFFECT_0, SPELL_AURA_DUMMY);
    }
};

// =====================================================================
// Passive DUMMY — Other (97 spells)
// These need individual research to determine handler type.
// =====================================================================

// 14161 - Ruthlessness — bp=eff0=0.0
// "Your finishing moves have a $b1% chance per combo point spent to grant a combo p"
// SimC: Participates in stat scaling; Referenced in SimC (context needs manual review)
class spell_rogue_ruthlessness : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 51667 - Cut to the Chase — bp=eff0=3.0
// "$?a137037[Envenom]?a137036[Dispatch][Eviscerate] grants $s1 sec of Slice and Dic"
// SimC: Referenced in SimC (context needs manual review)
class spell_rogue_cut_to_the_chase : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 91023 - Find Weakness — bp=eff0=30.0
// "Your Stealth abilities allow you to see the flaws in enemies' defenses, causing "
// SimC: Has proc/trigger behavior; Uses effect(s) 2, 3; Reads percentage value from effe
class spell_rogue_find_weakness : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 193537 - Weaponmaster — bp=eff0=15.0, eff1=50.0
// "$?s200758[Gloomblade][Backstab] and Shadowstrike have a $s1% chance to create a "
// SimC: Involves resource gain/cost; Affects cooldown/recharge timing; Has duration or t
class spell_rogue_weaponmaster : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 193539 - Alacrity — bp=eff1=5.0
// "Haste increased by ${$s1/10}.1%."
class spell_rogue_alacrity : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 193640 - Elaborate Planning — bp=eff0=5.0
// "Your finishing moves grant $s1% increased damage done for $193641d."
class spell_rogue_elaborate_planning : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 196922 - Hit and Run — bp=eff1=0.0
// "Movement speed increased by $s1%."
// SimC: Spell initialization/registration only
class spell_rogue_hit_and_run : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 196976 - Master of Shadows — bp=eff0=0.0
// "Gain ${$196980s1*$196980d/$196980t1+$196980s2} Energy over $196980d when you ent"
// SimC: Has proc/trigger behavior; Involves resource gain/cost; Has duration or tick-tim
class spell_rogue_master_of_shadows : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 238104 - Enveloping Shadows — bp=eff2=2.0
// "Deepening Shadows reduces the remaining cooldown of Shadow Dance by an additiona"
class spell_rogue_enveloping_shadows : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 255544 - Poison Bomb — bp=eff0=50.0, eff1=4.0
// "Envenom has a $<chance>% chance per combo point spent to smash a vial of poison "
// SimC: Uses effect(s) 2; Has duration or tick-time behavior; AoE or multi-target behavi
class spell_rogue_poison_bomb : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 255989 - Master Assassin — bp=eff0=3.0
// "Critical strike chance increased by $256735s1% while Stealthed and for $470676d "
class spell_rogue_master_assassin : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 272026 - Dancing Steel — bp=eff2=3.0
// "Blade Flurry strikes $s3 additional enemies and its duration is increased by ${$"
class spell_rogue_dancing_steel : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 279876 - Opportunity — bp=eff0=30.0
// "Sinister Strike has a $s1% chance to hit an additional time and grant Opportunit"
// SimC: Has proc/trigger behavior; Modifies damage output; Uses effect(s) 1; Reads perce
class spell_rogue_opportunity : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 328085 - Blindside — bp=eff0=15.0, eff1=30.0, eff2=35.0
// "Ambush and Mutilate have a $s1% chance to make your next Ambush free and usable "
// SimC: Has proc/trigger behavior; Buff interaction: darkest_night, implacable_tracker; 
class spell_rogue_blindside : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 381627 - Internal Bleeding — bp=eff0=0.0
// "Kidney Shot and Rupture also apply Internal Bleeding, dealing up to ${5*$381628o"
// SimC: Referenced in SimC (context needs manual review)
class spell_rogue_internal_bleeding : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 381630 - Intent to Kill — bp=eff0=33.333332
// "Shadowstep's cooldown is reduced by $s1% when used on a target afflicted by your"
// SimC: Spell initialization/registration only
class spell_rogue_intent_to_kill : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 381631 - Flying Daggers — bp=eff0=10.0, eff1=5.0
// "Fan of Knives has its radius increased to $?a196924[${$196924s1+$s4}][$s4] yds, "
class spell_rogue_flying_daggers : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 381640 - Lethal Dose — bp=eff0=1.0
// "Your weapon poisons and Nature or Bleed damage over time abilities deal $s1% inc"
// SimC: Spell initialization/registration only
class spell_rogue_lethal_dose : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 381652 - Systemic Failure — bp=eff0=30.0
// "Garrote increases the damage of Ambush and Mutilate on the target by $s1%."
// SimC: Spell initialization/registration only
class spell_rogue_systemic_failure : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 381673 - Doomblade — bp=eff0=25.0
// "Mutilate deals an additional $s1% Bleed damage over ${$381672d+2} sec."
// SimC: Uses effect(s) 1; Reads percentage value from effect; Referenced in SimC (contex
class spell_rogue_doomblade : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 381798 - Zoldyck Recipe — bp=eff0=15.0, eff1=35.0
// "Your Bleed, weapon poison, and other Nature damage is increased by $s1% against "
// SimC: Spell initialization/registration only
class spell_rogue_zoldyck_recipe : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 381799 - Scent of Blood — bp=eff0=2.0, eff1=20.0
// "Each enemy afflicted by your Rupture increases your Agility by $S1%, up to a max"
// SimC: Uses effect(s) 1; Has duration or tick-time behavior; Referenced in SimC (contex
class spell_rogue_scent_of_blood : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 381801 - Dragon-Tempered Blades — bp=eff0=1.0
// "You may apply $s1 additional Lethal and Non-Lethal Poison to your weapons, but t"
class spell_rogue_dragontempered_blades : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 381828 - Ace Up Your Sleeve — bp=eff0=5.0
// "Between the Eyes has a $s1% chance per combo point spent to grant $s2 combo poin"
class spell_rogue_ace_up_your_sleeve : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 381839 - Sleight of Hand — bp=eff0=20.0
// "Roll the Bones has a $s1% increased chance of granting more powerful results."
// SimC: Participates in stat scaling
class spell_rogue_sleight_of_hand : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 381845 - Audacity — bp=eff0=0.0
// "Using Pistol Shot with Opportunity has a $279876s1% chance to make your next Amb"
// SimC: Has proc/trigger behavior; Buff interaction: adrenaline_rush, audacity, bloodlus
class spell_rogue_audacity : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 381846 - Fan the Hammer — bp=eff0=1.0, eff2=20.0
// "When you gain Opportunity, gain $m1 additional $Lcharge:charges;. Max ${$s2+1} c"
class spell_rogue_fan_the_hammer : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 381878 - Deft Maneuvers — bp=eff1=1.0
// "Blade Flurry's initial damage is increased by $s1% and generates $m2 $Lcombo poi"
class spell_rogue_deft_maneuvers : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 381990 - Summarily Dispatched — bp=eff0=10.0
// "Dispatch deals $s1% increased damage and costs $s3 less Energy. This damage bonu"
class spell_rogue_summarily_dispatched : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 382505 - The First Dance — bp=eff0=4.0
// "Remaining out of combat for $470677d increases the duration of your next Shadow "
// SimC: Has proc/trigger behavior; Affects cooldown/recharge timing; Has duration or tic
class spell_rogue_the_first_dance : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 382508 - Planned Execution — bp=eff0=10.0
// "Shadow Dance increases the critical strike damage bonus of your abilities by $18"
// SimC: Spell initialization/registration only
class spell_rogue_planned_execution : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 382511 - Shadowed Finishers — bp=eff0=30.0
// "Eviscerate and Black Powder deal an additional $s1% damage as Shadow while Find "
// SimC: Spell initialization/registration only
class spell_rogue_shadowed_finishers : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 382514 - Fade to Nothing — bp=eff0=0.0
// "Movement speed increased by $386237s1% and damage taken reduced by $386237s2% fo"
// SimC: Spell initialization/registration only
class spell_rogue_fade_to_nothing : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 382518 - Perforated Veins — bp=eff0=10.0, eff1=10.0
// "$?s200758[Gloomblade][Backstab], Shuriken Storm, and Shadowstrike have $1264521s"
// SimC: Spell initialization/registration only
class spell_rogue_perforated_veins : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 382524 - Lingering Shadow — bp=eff0=50.0, eff2=18.0
// "After Shadow Dance ends, $?s200758[Gloomblade][Backstab] deals an additional $s1"
class spell_rogue_lingering_shadow : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 382525 - Finality — bp=eff1=15.0
// "Eviscerate and Black Powder have $s1% increased critical strike damage bonus."
class spell_rogue_finality : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 382528 - Danse Macabre — bp=eff0=10.0
// "While Shadow Dance is active, each different attack that generates or spends com"
// SimC: Buff interaction: darkest_night, deathstalkers_mark, premeditation; Debuff inter
class spell_rogue_danse_macabre : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 383281 - Hidden Opportunity — bp=eff0=80.0
// "Ambush has a chance to grant Opportunity. Chance to trigger this effect is $s1% "
// SimC: Has proc/trigger behavior; Buff interaction: adrenaline_rush, audacity, blade_fl
class spell_rogue_hidden_opportunity : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 394320 - Secret Stratagem — bp=eff2=5.0
// "Gain $s1 additional max combo point. Your finishing moves that consume more than"
class spell_rogue_secret_stratagem : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 394321 - Devious Stratagem — bp=eff2=5.0
// "Gain $s1 additional max combo point. Your finishing moves that consume more than"
class spell_rogue_devious_stratagem : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 426555 - Warning Signs — bp=eff0=25.0
// "Shadow Dance increases attack speed by $185313s8%."
// SimC: Spell initialization/registration only
class spell_rogue_warning_signs : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 426594 - Shadowcraft — bp=eff0=2.0, eff1=1.0, eff2=40.0
// "While Shadow Dance is active, your Shadow Techniques triggers $s3% more frequent"
// SimC: Spell initialization/registration only
class spell_rogue_shadowcraft : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 428387 - Terrifying Pace — bp=eff0=3.0
// "Shuriken Storm increases your movement speed by $428389s1% for $428389d when str"
// SimC: Spell initialization/registration only
class spell_rogue_terrifying_pace : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 441263 - Devious Distractions — bp=eff0=5.0
// "$?a137036[Killing Spree][Secret Technique] applies Fazed to any targets struck."
// SimC: Spell initialization/registration only
class spell_rogue_devious_distractions : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 441274 - Disorienting Strikes — bp=eff1=2.0
// "$?a137036[Killing Spree][Secret Technique] has $s1% reduced cooldown and allows "
class spell_rogue_disorienting_strikes : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 441321 - Flawless Form — bp=eff0=0.0
// "Unseen Blade and $?a137036[Killing Spree][Secret Technique] increase the damage "
// SimC: Modifies damage output; Uses effect(s) 2, 3; Reads percentage value from effect;
class spell_rogue_flawless_form : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 441359 - Flickerstrike — bp=eff0=1.0
// "Taking damage from an area-of-effect attack while Feint is active or dodging whi"
// SimC: Spell initialization/registration only
class spell_rogue_flickerstrike : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 441367 - Nimble Flurry — bp=eff1=7.0, eff2=65.0
// "$?a137036[Blade Flurry damage is increased by $s1%][Your auto-attacks, Unseen Bl"
class spell_rogue_nimble_flurry : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 441403 - So Tricky — bp=eff0=1.0
// "Tricks of the Trade's threat redirect duration is increased to $m1 $Lhour:min;."
class spell_rogue_so_tricky : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 441423 - Coup de Grace — bp=eff0=40.0, eff1=5.0, eff2=5.0
// "After $441786s1 strikes with Unseen Blade, your next $?a137036[Dispatch][Eviscer"
// SimC: Buff interaction: adrenaline_rush, darkest_night, shadow_dance; Affects cooldown
class spell_rogue_coup_de_grace : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 441429 - Cloud Cover — bp=eff1=90.0
// "Distract now also creates a cloud of smoke for $441587d. Cooldown increased to $"
class spell_rogue_cloud_cover : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 452536 - Hand of Fate — bp=eff0=5.0, eff1=3.0, eff2=15.0, eff3=1.0
// "Flip a Fatebound Coin each time a finishing move consumes $s1 or more combo poin"
class spell_rogue_hand_of_fate : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
        // TODO: Determine handler type for DUMMY effect 3
    }
};

// 453428 - Mean Streak — bp=eff0=33.0
// "Fatebound Coins flipped by $?a137036[Dispatch][Envenom] are $s1% more likely to "
// SimC: Spell initialization/registration only
class spell_rogue_mean_streak : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 453457 - Edge Case — bp=eff0=5.0
// "Activating $?a137036[Adrenaline Rush][Deathmark] flips a Fatebound Coin and caus"
// SimC: Spell initialization/registration only
class spell_rogue_edge_case : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 454419 - Deal Fate — bp=eff0=1.0
// "$?a383281[Sinister Strike and Ambush generate]?a137036[Sinister Strike generates"
// SimC: Has proc/trigger behavior; Buff interaction: audacity, disorienting_strikes, opp
class spell_rogue_deal_fate : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 454432 - Inexorable March — bp=eff0=70.0, eff1=2.0
// "You cannot be slowed below $s1% of normal movement speed while your Fatebound Co"
// SimC: Spell initialization/registration only
class spell_rogue_inexorable_march : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 454433 - Death's Arrival — bp=eff0=3.0
// "$?a137037[Shadowstep][Grappling Hook] may be used a second time within $457333d "
class spell_rogue_deaths_arrival : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 454435 - Destiny Defined — bp=eff2=5.0
// "$?a137037[Weapon poisons have $s1% increased application chance][Sinister Strike"
class spell_rogue_destiny_defined : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 457052 - Deathstalker's Mark — bp=eff0=3.0, eff1=5.0
// "$?c1[Garrote][Shadowstrike] applies $s1 stacks of Deathstalker's Mark to your ta"
// SimC: Has proc/trigger behavior; Uses effect(s) 1, 2, 3; Buff interaction: bloodlust, 
class spell_rogue_deathstalkers_mark : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 457054 - Hunt Them Down — bp=eff0=0.0
// "Auto-attacks against Marked targets deal an additional $457193s1 Plague damage."
// SimC: Referenced in SimC (context needs manual review)
class spell_rogue_hunt_them_down : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 457055 - Singular Focus — bp=eff0=5.0
// "Damage dealt to targets other than your Marked target deals $s1% Plague damage t"
// SimC: Referenced in SimC (context needs manual review)
class spell_rogue_singular_focus : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 457056 - Lingering Darkness — bp=eff0=0.0
// "After $?c1[Deathmark][Shadow Blades] expires, gain $?c1[$457273s1][$457273s2]% i"
// SimC: Has proc/trigger behavior; Buff interaction: cryptic_instructions, deathmark, er
class spell_rogue_lingering_darkness : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 457058 - Darkest Night — bp=eff0=0.0
// "When you consume the final Deathstalker's Mark from a target or your target dies"
// SimC: Has proc/trigger behavior; Uses effect(s) 1, 2, 5; Reads percentage value from e
class spell_rogue_darkest_night : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 457068 - Follow the Blood — bp=eff0=30.0, eff1=2.0, eff2=15.0
// "$?c1[Fan of Knives][Shuriken Storm] and $?c1[Crimson Tempest][Black Powder] deal"
// SimC: Spell initialization/registration only
class spell_rogue_follow_the_blood : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 457512 - Sanguine Stratagem — bp=eff2=5.0
// "Gain $s1 additional max combo point. Your finishing moves that consume more than"
class spell_rogue_sanguine_stratagem : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 469779 - Thistle Tea — bp=eff1=30.0
// "$@spelldesc381623"
class spell_rogue_thistle_tea : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 470347 - Supercharger — bp=eff0=1.0, eff1=2.0
// "$?a137035[Shadow Dance]?a137036[Adrenaline Rush][Kingsbane] supercharges $m1 com"
// SimC: Has proc/trigger behavior; Uses effect(s) 1, 2; Buff interaction: adrenaline_rus
class spell_rogue_supercharger : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 470668 - Forced Induction — bp=eff0=1.0
// "Increase the bonus granted when a damaging finishing move consumes a supercharge"
// SimC: Spell initialization/registration only
class spell_rogue_forced_induction : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 470669 - Echoing Reprimand — bp=eff0=5.0
// "After consuming a supercharged combo point, your next $?s200758[Gloomblade]?a137"
// SimC: Has proc/trigger behavior; Affects cooldown/recharge timing; Aura override or tr
class spell_rogue_echoing_reprimand : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1248774 - Unshakeable Drive — bp=eff0=0.0
// "When you consume an application of Deathstalker's Mark, the damage of your next "
// SimC: Has proc/trigger behavior; Uses effect(s) 2; Participates in stat scaling; Refer
class spell_rogue_unshakeable_drive : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1248970 - Lucky Coin — bp=eff0=7.0
// "Every $s1 coin flips, keep a lucky coin that bends you towards your fate for $12"
// SimC: Spell initialization/registration only
class spell_rogue_lucky_coin : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1249190 - Overflowing Purse — bp=eff0=3.0, eff1=4.0, eff2=15.0
// "$?c2[Dispatch][Envenom] has a $?c2[$s2][$s3]% chance to flip $s1 Fatebound Coins"
// SimC: Spell initialization/registration only
class spell_rogue_overflowing_purse : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 1249194 - Delivered Doom — bp=eff0=5.0, eff1=5.0
// "$?c1[Envenom deals][Dispatch and Between the Eyes deal] $s1% more damage when $?"
// SimC: Spell initialization/registration only
class spell_rogue_delivered_doom : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1249201 - Chosen's Revelry — bp=eff0=0.0
// "Flipping a Fatebound Coin restores $1249202s1 health."
// SimC: Spell initialization/registration only
class spell_rogue_chosens_revelry : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1249204 - Rush to the Inevitable — bp=eff0=5.0, eff1=2.0, eff2=15.0, eff3=10.0
// "Gain $?c1[$s1][$s2] Energy every time you flip a Fatebound Coin. Gain $?c1[$s3]["
// SimC: Referenced in SimC (context needs manual review)
class spell_rogue_rush_to_the_inevitable : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
        // TODO: Determine handler type for DUMMY effect 3
    }
};

// 1249809 - Finish the Job — bp=eff0=0.0
// "All damage you deal is increased by $1249810s1% while Deathmark is active."
// SimC: Has proc/trigger behavior; Participates in stat scaling; Referenced in SimC (con
class spell_rogue_finish_the_job : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1250036 - Inspiring Strike — bp=eff0=5.0
// "Applying Envenom while Envenom is already active causes it to increase all damag"
class spell_rogue_inspiring_strike : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1250141 - Secondary Poisoning — bp=eff0=50.0
// "When you apply a Weapon Poison with a single-target attack, you have a $s1% chan"
// SimC: Referenced in SimC (context needs manual review)
class spell_rogue_secondary_poisoning : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1250325 - Regicide's Reward — bp=eff0=5.0
// "When Kingsbane ends, gain $1250331s1% haste for every $s1 stacks of increased Ki"
// SimC: Has proc/trigger behavior
class spell_rogue_regicides_reward : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1259612 - Deadly Pursuit — bp=eff0=15.0
// "After spending $s1 combo points, if you spend no combo points for $1259613d, abi"
// SimC: Has proc/trigger behavior; Resource: ENERGY
class spell_rogue_deadly_pursuit : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1264764 - Shuriken Tornado — bp=eff0=15.0, eff1=50.0
// "Shuriken Storm has a $s1% chance to create a Shadow Clone that repeats the attac"
// SimC: Spell initialization/registration only
class spell_rogue_shuriken_tornado : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1265385 - Implacable — bp=eff0=20.0, eff1=15.0
// "Nothing will save your target from you. Envenom damage increased by $s3%. When y"
class spell_rogue_implacable_1265385 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1265387 - Implacable — bp=eff0=0.0
// "After striking with Kingsbane, rapidly strike that target $1265787s1 times over "
// SimC: Has proc/trigger behavior; Uses effect(s) 1, 2; Reads percentage value from effe
class spell_rogue_implacable_1265387 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1265861 - Gravedigger — bp=eff0=45.0
// "Between the Eyes has a $s1% chance to apply 2 stacks of its bonus to your damage"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Resource: COST_1; Aura override or 
class spell_rogue_gravedigger_1265861 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1265863 - Gravedigger — bp=eff0=12.0, eff1=6.0
// "When you Dispatch you have a $s1% chance per combo point spent to hide a bullet "
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Resource: COST_1; Aura override or 
class spell_rogue_gravedigger_1265863 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1265952 - Potent Powder — bp=eff0=30.0, eff1=5.0
// "Black Powder deals increased damage equal to $s1% of your Mastery when it spends"
// SimC: Spell initialization/registration only
class spell_rogue_potent_powder : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1267220 - Danger Sense — bp=eff1=20.0, eff2=20.0
// "You have a $s2% chance to partially evade any damage dealt to you, reducing the "
class spell_rogue_danger_sense : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
        // TODO: Determine handler type for DUMMY effect 2
    }
};

// 1268932 - Ancient Arts — bp=eff0=15.0, eff1=50.0
// "Damaging attacks that expend Shadow Techniques to generate combo points have a $"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Buff interaction: ancient_arts, dar
class spell_rogue_ancient_arts_1268932 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1268936 - Ancient Arts — bp=eff0=50.0
// "Shadow damage increased by $s2%. Shadow Clones have a $s1% chance to trigger Sha"
class spell_rogue_ancient_arts_1268936 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1268939 - Ancient Arts — bp=eff0=5.0
// "After attacks that generate combo points, if $s1 or more stacks of Shadow Techni"
// SimC: Has proc/trigger behavior; Uses effect(s) 1; Buff interaction: ancient_arts, dar
class spell_rogue_ancient_arts_1268939 : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1272989 - Precise Killer — bp=eff1=20.0
// "Critical strike damage bonus increased by $s2%."
class spell_rogue_precise_killer : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1273017 - Quietus Celeris — bp=eff0=6.0, eff1=20.0
// "Deathstalker's Mark has a ${$s1/$s2*100}% chance to immediately consume a stack "
// SimC: Spell initialization/registration only
class spell_rogue_quietus_celeris : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1273035 - Mass Casualty — bp=eff0=40.0, eff1=75.0
// "Deathstalker's Mark deals $?c1[$s1][$s2]% of its normal damage to all other enem"
// SimC: AoE or multi-target behavior; Referenced in SimC (context needs manual review)
class spell_rogue_mass_casualty : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1276630 - Flashing Steel — bp=eff1=25.0
// "Unseen Blade may now occur once every ${20-($s1/-1000)} sec and has $s2% chance "
class spell_rogue_flashing_steel : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// 1276809 - Ravenholdt Mint — bp=eff0=4.0
// "Flipping Heads increases damage by an additional $s1%. Damage dealt by flipping "
class spell_rogue_ravenholdt_mint : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1276816 - Controlled Chaos — bp=eff0=4.0
// "After flipping a Fatebound Coin that ends a streak of $s1 or more, flip another "
// SimC: Spell initialization/registration only
class spell_rogue_controlled_chaos : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 0
    }
};

// 1281468 - Umbral Edge — bp=eff1=50.0
// "Shadow Clones deal $s1% increased damage. Cheap Shot creates a Shadow Clone to S"
class spell_rogue_umbral_edge : public AuraScript
{
    void Register() override
    {
        // TODO: Determine handler type for DUMMY effect 1
    }
};

// =====================================================================
// PERIODIC_DUMMY — Tick Handlers (7 spells)
// =====================================================================

// 1943 - Rupture
// "Finishing move that tears open the target, dealing Bleed damage over time. Lasts longer per combo point.    1 point  : $"
class spell_rogue_rupture : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_rogue_rupture::HandlePeriodic, EFFECT_1, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 140149 - Marked for Death
// "Designer Note: The only purpose of this aura is to mark a player who just cast Marked for Death."
class spell_rogue_marked_for_death : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_rogue_marked_for_death::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 270061 - Hidden Blades
// "Every $t1 sec, gain $270070s1% increased damage for your next Fan of Knives, stacking up to $270070u times."
class spell_rogue_hidden_blades : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_rogue_hidden_blades::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 381988 - Swift Slasher
// "Slice and Dice grants additional attack speed equal to $s2% of your Haste."
class spell_rogue_swift_slasher : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_rogue_swift_slasher::HandlePeriodic, EFFECT_1, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 428486 - Exhilarating Execution
// "Your finishing moves heal you for $s1% of damage done. At full health gain shielding instead, absorbing up to $s2% of yo"
class spell_rogue_exhilarating_execution : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=eff1=10.0
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_rogue_exhilarating_execution::HandlePeriodic, EFFECT_0, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 454286 - Tempted Fate
// "You have a $s2% chance to absorb $s1% of any damage taken."
class spell_rogue_tempted_fate : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=eff0=10.0, eff1=30.0, eff2=0.0
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_rogue_tempted_fate::HandlePeriodic, EFFECT_3, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// 1271702 - Deepening Shadows
// "$@spelldesc185314"
class spell_rogue_deepening_shadows : public AuraScript
{
    void HandlePeriodic(AuraEffect const* aurEff)
    {
        // TODO: Implement periodic tick behavior
        // bp=none
    }

    void Register() override
    {
        OnEffectPeriodic += AuraEffectPeriodicFn(spell_rogue_deepening_shadows::HandlePeriodic, EFFECT_2, SPELL_AURA_PERIODIC_DUMMY);
    }
};

// =====================================================================
// Active DUMMY — HandleDummy (7 spells)
// =====================================================================

// 703 - Garrote
// "Garrote the enemy, causing $o1 Bleed damage over $d.$?a196861[ Silences the target for $1330d when used from Stealth.][]"
class spell_rogue_garrote : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_garrote::HandleApply, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_garrote::HandleRemove, EFFECT_1, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 32645 - Envenom
// "Finishing move that drives your poisoned blades in deep, dealing instant Nature damage and increasing your poison applic"
class spell_rogue_envenom : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_envenom::HandleApply, EFFECT_5, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_envenom::HandleRemove, EFFECT_5, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 121471 - Shadow Blades
// "Draws upon surrounding shadows to empower your weapons, causing your attacks to deal $s1% additional damage as Shadow an"
class spell_rogue_shadow_blades : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_shadow_blades::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_shadow_blades::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 256171 - Loaded Dice
// "$@spelldesc256170"
class spell_rogue_loaded_dice : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_loaded_dice::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_loaded_dice::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 360194 - Deathmark
// "Carve a deathmark into an enemy, dealing $o1 Bleed damage and restoring ${$s3*8} Energy to you over $d. Damage dealt to "
class spell_rogue_deathmark : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_deathmark::HandleApply, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_deathmark::HandleRemove, EFFECT_2, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 385627 - Kingsbane
// "Release a powerful poison from your weapons and inject it into your target, dealing $s2 Nature damage instantly and an a"
class spell_rogue_kingsbane : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_kingsbane::HandleApply, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_kingsbane::HandleRemove, EFFECT_4, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// 1214909 - Roll the Bones
// "Roll the dice of fate, providing a combat enhancement of random power for $d. 1 set or better: Add $1214937s1% increased"
class spell_rogue_roll_the_bones : public AuraScript
{
    void HandleApply(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura apply behavior
    }

    void HandleRemove(AuraEffect const* /*aurEff*/, AuraEffectHandleModes /*mode*/)
    {
        // TODO: Implement active DUMMY aura remove behavior
    }

    void Register() override
    {
        AfterEffectApply += AuraEffectApplyFn(spell_rogue_roll_the_bones::HandleApply, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
        AfterEffectRemove += AuraEffectRemoveFn(spell_rogue_roll_the_bones::HandleRemove, EFFECT_0, SPELL_AURA_DUMMY, AURA_EFFECT_HANDLE_REAL);
    }
};

// =====================================================================
// Script Registration
// =====================================================================

void AddSC_rogue_spell_audit()
{
    RegisterSpellScript(spell_rogue_subterfuge);
    RegisterSpellScript(spell_rogue_deeper_stratagem);
    RegisterSpellScript(spell_rogue_mastery_potent_assassin);
    RegisterSpellScript(spell_rogue_improved_backstab);
    RegisterSpellScript(spell_rogue_improved_shuriken_storm);
    RegisterSpellScript(spell_rogue_improved_adrenaline_rush);
    RegisterSpellScript(spell_rogue_unseen_blade);
    RegisterSpellScript(spell_rogue_shadewalker);
    RegisterSpellScript(spell_rogue_seal_fate);
    RegisterSpellScript(spell_rogue_silent_storm);
    RegisterSpellScript(spell_rogue_sudden_demise);
    RegisterSpellScript(spell_rogue_shuriken_storm);
    RegisterSpellScript(spell_rogue_relentless_strikes);
    RegisterSpellScript(spell_rogue_venom_rush);
    RegisterSpellScript(spell_rogue_ruthlessness);
    RegisterSpellScript(spell_rogue_cut_to_the_chase);
    RegisterSpellScript(spell_rogue_find_weakness);
    RegisterSpellScript(spell_rogue_weaponmaster);
    RegisterSpellScript(spell_rogue_alacrity);
    RegisterSpellScript(spell_rogue_elaborate_planning);
    RegisterSpellScript(spell_rogue_hit_and_run);
    RegisterSpellScript(spell_rogue_master_of_shadows);
    RegisterSpellScript(spell_rogue_enveloping_shadows);
    RegisterSpellScript(spell_rogue_poison_bomb);
    RegisterSpellScript(spell_rogue_master_assassin);
    RegisterSpellScript(spell_rogue_dancing_steel);
    RegisterSpellScript(spell_rogue_opportunity);
    RegisterSpellScript(spell_rogue_blindside);
    RegisterSpellScript(spell_rogue_internal_bleeding);
    RegisterSpellScript(spell_rogue_intent_to_kill);
    RegisterSpellScript(spell_rogue_flying_daggers);
    RegisterSpellScript(spell_rogue_lethal_dose);
    RegisterSpellScript(spell_rogue_systemic_failure);
    RegisterSpellScript(spell_rogue_doomblade);
    RegisterSpellScript(spell_rogue_zoldyck_recipe);
    RegisterSpellScript(spell_rogue_scent_of_blood);
    RegisterSpellScript(spell_rogue_dragontempered_blades);
    RegisterSpellScript(spell_rogue_ace_up_your_sleeve);
    RegisterSpellScript(spell_rogue_sleight_of_hand);
    RegisterSpellScript(spell_rogue_audacity);
    RegisterSpellScript(spell_rogue_fan_the_hammer);
    RegisterSpellScript(spell_rogue_deft_maneuvers);
    RegisterSpellScript(spell_rogue_summarily_dispatched);
    RegisterSpellScript(spell_rogue_the_first_dance);
    RegisterSpellScript(spell_rogue_planned_execution);
    RegisterSpellScript(spell_rogue_shadowed_finishers);
    RegisterSpellScript(spell_rogue_fade_to_nothing);
    RegisterSpellScript(spell_rogue_perforated_veins);
    RegisterSpellScript(spell_rogue_lingering_shadow);
    RegisterSpellScript(spell_rogue_finality);
    RegisterSpellScript(spell_rogue_danse_macabre);
    RegisterSpellScript(spell_rogue_hidden_opportunity);
    RegisterSpellScript(spell_rogue_secret_stratagem);
    RegisterSpellScript(spell_rogue_devious_stratagem);
    RegisterSpellScript(spell_rogue_warning_signs);
    RegisterSpellScript(spell_rogue_shadowcraft);
    RegisterSpellScript(spell_rogue_terrifying_pace);
    RegisterSpellScript(spell_rogue_devious_distractions);
    RegisterSpellScript(spell_rogue_disorienting_strikes);
    RegisterSpellScript(spell_rogue_flawless_form);
    RegisterSpellScript(spell_rogue_flickerstrike);
    RegisterSpellScript(spell_rogue_nimble_flurry);
    RegisterSpellScript(spell_rogue_so_tricky);
    RegisterSpellScript(spell_rogue_coup_de_grace);
    RegisterSpellScript(spell_rogue_cloud_cover);
    RegisterSpellScript(spell_rogue_hand_of_fate);
    RegisterSpellScript(spell_rogue_mean_streak);
    RegisterSpellScript(spell_rogue_edge_case);
    RegisterSpellScript(spell_rogue_deal_fate);
    RegisterSpellScript(spell_rogue_inexorable_march);
    RegisterSpellScript(spell_rogue_deaths_arrival);
    RegisterSpellScript(spell_rogue_destiny_defined);
    RegisterSpellScript(spell_rogue_deathstalkers_mark);
    RegisterSpellScript(spell_rogue_hunt_them_down);
    RegisterSpellScript(spell_rogue_singular_focus);
    RegisterSpellScript(spell_rogue_lingering_darkness);
    RegisterSpellScript(spell_rogue_darkest_night);
    RegisterSpellScript(spell_rogue_follow_the_blood);
    RegisterSpellScript(spell_rogue_sanguine_stratagem);
    RegisterSpellScript(spell_rogue_thistle_tea);
    RegisterSpellScript(spell_rogue_supercharger);
    RegisterSpellScript(spell_rogue_forced_induction);
    RegisterSpellScript(spell_rogue_echoing_reprimand);
    RegisterSpellScript(spell_rogue_unshakeable_drive);
    RegisterSpellScript(spell_rogue_lucky_coin);
    RegisterSpellScript(spell_rogue_overflowing_purse);
    RegisterSpellScript(spell_rogue_delivered_doom);
    RegisterSpellScript(spell_rogue_chosens_revelry);
    RegisterSpellScript(spell_rogue_rush_to_the_inevitable);
    RegisterSpellScript(spell_rogue_finish_the_job);
    RegisterSpellScript(spell_rogue_inspiring_strike);
    RegisterSpellScript(spell_rogue_secondary_poisoning);
    RegisterSpellScript(spell_rogue_regicides_reward);
    RegisterSpellScript(spell_rogue_deadly_pursuit);
    RegisterSpellScript(spell_rogue_shuriken_tornado);
    RegisterSpellScript(spell_rogue_implacable_1265385);
    RegisterSpellScript(spell_rogue_implacable_1265387);
    RegisterSpellScript(spell_rogue_gravedigger_1265861);
    RegisterSpellScript(spell_rogue_gravedigger_1265863);
    RegisterSpellScript(spell_rogue_potent_powder);
    RegisterSpellScript(spell_rogue_danger_sense);
    RegisterSpellScript(spell_rogue_ancient_arts_1268932);
    RegisterSpellScript(spell_rogue_ancient_arts_1268936);
    RegisterSpellScript(spell_rogue_ancient_arts_1268939);
    RegisterSpellScript(spell_rogue_precise_killer);
    RegisterSpellScript(spell_rogue_quietus_celeris);
    RegisterSpellScript(spell_rogue_mass_casualty);
    RegisterSpellScript(spell_rogue_flashing_steel);
    RegisterSpellScript(spell_rogue_ravenholdt_mint);
    RegisterSpellScript(spell_rogue_controlled_chaos);
    RegisterSpellScript(spell_rogue_umbral_edge);
    RegisterSpellScript(spell_rogue_rupture);
    RegisterSpellScript(spell_rogue_marked_for_death);
    RegisterSpellScript(spell_rogue_hidden_blades);
    RegisterSpellScript(spell_rogue_swift_slasher);
    RegisterSpellScript(spell_rogue_exhilarating_execution);
    RegisterSpellScript(spell_rogue_tempted_fate);
    RegisterSpellScript(spell_rogue_deepening_shadows);
    RegisterSpellScript(spell_rogue_garrote);
    RegisterSpellScript(spell_rogue_envenom);
    RegisterSpellScript(spell_rogue_shadow_blades);
    RegisterSpellScript(spell_rogue_loaded_dice);
    RegisterSpellScript(spell_rogue_deathmark);
    RegisterSpellScript(spell_rogue_kingsbane);
    RegisterSpellScript(spell_rogue_roll_the_bones);
}
