-- Fix: Remove TransmogSetItem hotfix DELETE records that cause client Lua errors.
--
-- The hotfix_data table contains 107 TransmogSetItem entries with Status=2
-- (RecordRemoved). When the client connects, the server instructs it to delete
-- these TransmogSetItem records from its local DB2 cache. This creates partially
-- orphaned TransmogSets — the parent set still exists but some slot-item mappings
-- are gone.
--
-- The client's C_TransmogOutfitInfo.GetSourceIDsForSlot() then returns nil for
-- slots with no remaining items, crashing Blizzard_Transmog.lua:2488 with:
--   "attempt to get length of local 'sourceIDs' (a nil value)"
-- This error fires 40+ times per session (once per affected set × slot).
--
-- Affected sets (20 total, all partially orphaned — Legion tier sets):
--   309 "Vestments of the Purifier", 316 "Legacy of Azj'Aqir",
--   322, 936, 938, 940, 943, 945, 979, 981, 983, 985, 991, 993,
--   995, 997, 999, 1001, 1003, 1005
--
-- Fix: Delete the Status=2 hotfix_data entries so the server stops telling
-- the client to remove these records. The client keeps its base DB2 data intact.
--
-- TableHash 0x1E21AFB4 = TransmogSetItem.db2

DELETE FROM `hotfix_data` WHERE `TableHash` = 0x1E21AFB4 AND `Status` = 2;
