#!/usr/bin/env python3
"""
fix_level1_npcs.py — Fix NPCs stuck at level 1 due to missing/zero ContentTuningID.

Cross-references Wowhead NPC data with creature_template_difficulty to find NPCs
that should have a proper ContentTuningID but currently have 0 or no CTD row at all.

Generates three SQL files by priority:
  - npc_level_fixes_high.sql   (level 70+)
  - npc_level_fixes_medium.sql (level 31-69)
  - npc_level_fixes_low.sql    (level 1-30)

ContentTuningID assignments:
  Level 70-80+  -> CT 2677 (TWW, 70-80)
  Level 60-69   -> CT 2151 (Dragonflight, 10-70)
  Level 31-59   -> CT 1227 (BfA chromie, 10-60)
  Level 10-30   -> CT 2 (Classic, 5-30)
  Level 1-9     -> CT 864 (universal scaling, 1-80)
"""

import csv
import subprocess
import sys
import os
from collections import defaultdict

# Paths
WOWHEAD_CSV = r"C:\Users\atayl\VoxCore\wago\wowhead_data\npc\npc_export.csv"
OUTPUT_DIR = r"C:\Users\atayl\VoxCore\sql\exports\cleanup"
MYSQL_BIN = r"C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe"

# ContentTuningID assignments by level range
CT_ASSIGNMENTS = {
    # (min_level, max_level): ContentTuningID
    (70, 999): 2677,   # TWW content (70-80) — also covers Midnight 81+
    (60, 69):  2151,   # Dragonflight (10-70)
    (31, 59):  1227,   # BfA chromie (10-60)
    (10, 30):  2,      # Classic (5-30)
    (1, 9):    864,     # Universal scaling (1-80)
}

CT_NAMES = {
    2677: "TWW (70-80)",
    2151: "Dragonflight (10-70)",
    1227: "BfA Chromie (10-60)",
    2:    "Classic (5-30)",
    864:  "Universal Scaling (1-80)",
}

def get_content_tuning_id(level):
    """Return the appropriate ContentTuningID for a given level."""
    for (lo, hi), ct_id in CT_ASSIGNMENTS.items():
        if lo <= level <= hi:
            return ct_id
    return None

def run_mysql_query(query):
    """Execute a MySQL query and return rows as list of dicts."""
    cmd = [MYSQL_BIN, "-u", "root", "-padmin", "--batch", "--skip-column-names", "-e", query]
    result = subprocess.run(cmd, capture_output=True, text=True, encoding='utf-8', errors='replace')
    if result.returncode != 0:
        print(f"MySQL error: {result.stderr}", file=sys.stderr)
        sys.exit(1)
    rows = []
    for line in result.stdout.strip().split('\n'):
        if line:
            rows.append(line.split('\t'))
    return rows

def load_wowhead_data():
    """Load NPC data from Wowhead CSV. Returns dict of entry -> {level, zone_id, name}."""
    npcs = {}
    with open(WOWHEAD_CSV, 'r', encoding='utf-8', errors='replace') as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                entry = int(row['id'])
            except (ValueError, KeyError):
                continue

            # Parse level — skip if empty or non-numeric
            level_str = row.get('level', '').strip()
            if not level_str:
                continue
            try:
                level = int(level_str)
            except ValueError:
                # Handle range like "70-80" — take the max
                if '-' in level_str:
                    try:
                        parts = level_str.split('-')
                        level = int(parts[-1].strip())
                    except ValueError:
                        continue
                else:
                    continue

            if level < 1:
                continue

            npcs[entry] = {
                'level': level,
                'zone_id': row.get('zone_id', ''),
                'name': row.get('name', ''),
            }
    return npcs

def get_existing_ctd_entries():
    """Get all entries that have a CTD row with DifficultyID=0, and their ContentTuningID."""
    rows = run_mysql_query(
        "SELECT Entry, ContentTuningID FROM world.creature_template_difficulty "
        "WHERE DifficultyID = 0;"
    )
    result = {}
    for row in rows:
        entry = int(row[0])
        ct_id = int(row[1])
        result[entry] = ct_id
    return result

def get_all_creature_template_entries():
    """Get all entries from creature_template."""
    rows = run_mysql_query("SELECT entry FROM world.creature_template;")
    return set(int(row[0]) for row in rows)

def generate_sql_header(priority_label, description):
    """Generate SQL file header."""
    return f"""-- =============================================================================
-- NPC Level Fixes: {priority_label}
-- {description}
-- Generated by fix_level1_npcs.py
-- =============================================================================
-- Cross-references Wowhead NPC levels against creature_template_difficulty.
-- Fixes NPCs stuck at level 1 due to ContentTuningID=0 or missing CTD row.
-- Idempotent: UPDATEs only touch CT=0 rows; INSERTs use INSERT IGNORE.
-- =============================================================================

"""

def generate_update_sql(entries_by_ct, npc_data):
    """Generate UPDATE statements for entries with CTD row but ContentTuningID=0."""
    lines = []
    for ct_id in sorted(entries_by_ct.keys()):
        entries = sorted(entries_by_ct[ct_id])
        if not entries:
            continue

        lines.append(f"-- ContentTuningID {ct_id} ({CT_NAMES.get(ct_id, 'unknown')}) — {len(entries)} NPCs")

        # Batch into groups for readability
        BATCH = 100
        for i in range(0, len(entries), BATCH):
            batch = entries[i:i+BATCH]
            entry_list = ', '.join(str(e) for e in batch)
            lines.append(
                f"UPDATE `creature_template_difficulty` "
                f"SET `ContentTuningID` = {ct_id} "
                f"WHERE `Entry` IN ({entry_list}) "
                f"AND `DifficultyID` = 0 AND `ContentTuningID` = 0;"
            )
        lines.append("")

    return '\n'.join(lines)

def generate_insert_sql(entries_by_ct, npc_data):
    """Generate INSERT IGNORE statements for entries missing CTD row entirely."""
    lines = []
    for ct_id in sorted(entries_by_ct.keys()):
        entries = sorted(entries_by_ct[ct_id])
        if not entries:
            continue

        lines.append(f"-- ContentTuningID {ct_id} ({CT_NAMES.get(ct_id, 'unknown')}) — {len(entries)} NPCs")

        # INSERT IGNORE with sensible defaults
        # Columns: Entry, DifficultyID, LevelScalingDeltaMin, LevelScalingDeltaMax,
        #          ContentTuningID, HealthScalingExpansion, HealthModifier, ManaModifier,
        #          ArmorModifier, DamageModifier, CreatureDifficultyID, TypeFlags, TypeFlags2,
        #          TypeFlags3, LootID, PickPocketLootID, SkinLootID, GoldMin, GoldMax,
        #          StaticFlags1-8, VerifiedBuild
        BATCH = 50
        for i in range(0, len(entries), BATCH):
            batch = entries[i:i+BATCH]
            values = []
            for entry in batch:
                # Default values matching typical rows in the table
                values.append(
                    f"({entry}, 0, 0, 0, {ct_id}, 0, 1, 1, 1, 1, 0, 0, 0, 0, "
                    f"0, 0, 0, 0, 0, 268435456, 0, 0, 0, 0, 0, 0, 0, 0)"
                )

            lines.append(
                "INSERT IGNORE INTO `creature_template_difficulty` "
                "(`Entry`, `DifficultyID`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, "
                "`ContentTuningID`, `HealthScalingExpansion`, `HealthModifier`, `ManaModifier`, "
                "`ArmorModifier`, `DamageModifier`, `CreatureDifficultyID`, `TypeFlags`, "
                "`TypeFlags2`, `TypeFlags3`, `LootID`, `PickPocketLootID`, `SkinLootID`, "
                "`GoldMin`, `GoldMax`, `StaticFlags1`, `StaticFlags2`, `StaticFlags3`, "
                "`StaticFlags4`, `StaticFlags5`, `StaticFlags6`, `StaticFlags7`, "
                "`StaticFlags8`, `VerifiedBuild`) VALUES"
            )
            lines.append(',\n'.join(values) + ';')
        lines.append("")

    return '\n'.join(lines)

def main():
    print("Loading Wowhead NPC data...")
    wowhead_npcs = load_wowhead_data()
    print(f"  Loaded {len(wowhead_npcs)} NPCs with level data from Wowhead CSV")

    print("Querying existing creature_template_difficulty rows...")
    existing_ctd = get_existing_ctd_entries()
    print(f"  Found {len(existing_ctd)} entries with DifficultyID=0 CTD rows")

    print("Querying all creature_template entries...")
    all_ct_entries = get_all_creature_template_entries()
    print(f"  Found {len(all_ct_entries)} creature_template entries")

    # Categorize NPCs that need fixing
    # Only consider NPCs that exist in creature_template (they're in our DB)
    updates_by_ct = defaultdict(list)  # CT ID -> [entries needing UPDATE]
    inserts_by_ct = defaultdict(list)  # CT ID -> [entries needing INSERT]

    # Track stats
    stats = {
        'high': {'update': 0, 'insert': 0, 'entries': []},
        'medium': {'update': 0, 'insert': 0, 'entries': []},
        'low': {'update': 0, 'insert': 0, 'entries': []},
    }

    # Per-priority buckets
    high_updates = defaultdict(list)
    high_inserts = defaultdict(list)
    med_updates = defaultdict(list)
    med_inserts = defaultdict(list)
    low_updates = defaultdict(list)
    low_inserts = defaultdict(list)

    skipped_not_in_db = 0
    skipped_already_has_ct = 0

    for entry, npc_info in wowhead_npcs.items():
        # Only process NPCs that exist in our creature_template
        if entry not in all_ct_entries:
            skipped_not_in_db += 1
            continue

        level = npc_info['level']
        ct_id = get_content_tuning_id(level)
        if ct_id is None:
            continue

        # Check current state
        if entry in existing_ctd:
            current_ct = existing_ctd[entry]
            if current_ct != 0:
                # Already has a non-zero ContentTuningID, skip
                skipped_already_has_ct += 1
                continue
            # Needs UPDATE (has CTD row but CT=0)
            fix_type = 'update'
        else:
            # Needs INSERT (no CTD row at all)
            fix_type = 'insert'

        # Determine priority
        if level >= 70:
            priority = 'high'
            if fix_type == 'update':
                high_updates[ct_id].append(entry)
                stats['high']['update'] += 1
            else:
                high_inserts[ct_id].append(entry)
                stats['high']['insert'] += 1
        elif level >= 31:
            priority = 'medium'
            if fix_type == 'update':
                med_updates[ct_id].append(entry)
                stats['medium']['update'] += 1
            else:
                med_inserts[ct_id].append(entry)
                stats['medium']['insert'] += 1
        else:
            priority = 'low'
            if fix_type == 'update':
                low_updates[ct_id].append(entry)
                stats['low']['update'] += 1
            else:
                low_inserts[ct_id].append(entry)
                stats['low']['insert'] += 1

    # Print summary
    print(f"\n{'='*70}")
    print("SUMMARY")
    print(f"{'='*70}")
    print(f"Wowhead NPCs with level data:  {len(wowhead_npcs)}")
    print(f"NPCs not in our DB (skipped):   {skipped_not_in_db}")
    print(f"NPCs already with non-zero CT:  {skipped_already_has_ct}")
    print()

    for priority, label, updates, inserts in [
        ('high', 'HIGH (level 70+)', high_updates, high_inserts),
        ('medium', 'MEDIUM (level 31-69)', med_updates, med_inserts),
        ('low', 'LOW (level 1-30)', low_updates, low_inserts),
    ]:
        total_u = sum(len(v) for v in updates.values())
        total_i = sum(len(v) for v in inserts.values())
        total = total_u + total_i
        print(f"{label}:")
        print(f"  Total NPCs to fix:   {total}")
        print(f"    UPDATEs (CT=0):    {total_u}")
        print(f"    INSERTs (no CTD):  {total_i}")
        for ct_id in sorted(set(list(updates.keys()) + list(inserts.keys()))):
            u = len(updates.get(ct_id, []))
            i = len(inserts.get(ct_id, []))
            print(f"    CT {ct_id} ({CT_NAMES.get(ct_id, '?')}): {u} updates, {i} inserts")
        print()

    # Generate SQL files
    # HIGH priority
    high_path = os.path.join(OUTPUT_DIR, "npc_level_fixes_high.sql")
    with open(high_path, 'w', encoding='utf-8') as f:
        f.write(generate_sql_header("HIGH PRIORITY", "Level 70+ NPCs stuck at level 1"))

        total_u = sum(len(v) for v in high_updates.values())
        total_i = sum(len(v) for v in high_inserts.values())

        if total_u > 0:
            f.write(f"-- ===== UPDATEs: {total_u} NPCs with CTD row but ContentTuningID=0 =====\n\n")
            f.write(generate_update_sql(high_updates, wowhead_npcs))
            f.write("\n")

        if total_i > 0:
            f.write(f"-- ===== INSERTs: {total_i} NPCs missing CTD row entirely =====\n\n")
            f.write(generate_insert_sql(high_inserts, wowhead_npcs))
            f.write("\n")

        if total_u == 0 and total_i == 0:
            f.write("-- No NPCs to fix in this priority level.\n")

    print(f"Wrote {high_path}")

    # MEDIUM priority
    med_path = os.path.join(OUTPUT_DIR, "npc_level_fixes_medium.sql")
    with open(med_path, 'w', encoding='utf-8') as f:
        f.write(generate_sql_header("MEDIUM PRIORITY", "Level 31-69 NPCs stuck at level 1"))

        total_u = sum(len(v) for v in med_updates.values())
        total_i = sum(len(v) for v in med_inserts.values())

        if total_u > 0:
            f.write(f"-- ===== UPDATEs: {total_u} NPCs with CTD row but ContentTuningID=0 =====\n\n")
            f.write(generate_update_sql(med_updates, wowhead_npcs))
            f.write("\n")

        if total_i > 0:
            f.write(f"-- ===== INSERTs: {total_i} NPCs missing CTD row entirely =====\n\n")
            f.write(generate_insert_sql(med_inserts, wowhead_npcs))
            f.write("\n")

        if total_u == 0 and total_i == 0:
            f.write("-- No NPCs to fix in this priority level.\n")

    print(f"Wrote {med_path}")

    # LOW priority
    low_path = os.path.join(OUTPUT_DIR, "npc_level_fixes_low.sql")
    with open(low_path, 'w', encoding='utf-8') as f:
        f.write(generate_sql_header("LOW PRIORITY", "Level 1-30 NPCs stuck at level 1"))

        total_u = sum(len(v) for v in low_updates.values())
        total_i = sum(len(v) for v in low_inserts.values())

        if total_u > 0:
            f.write(f"-- ===== UPDATEs: {total_u} NPCs with CTD row but ContentTuningID=0 =====\n\n")
            f.write(generate_update_sql(low_updates, wowhead_npcs))
            f.write("\n")

        if total_i > 0:
            f.write(f"-- ===== INSERTs: {total_i} NPCs missing CTD row entirely =====\n\n")
            f.write(generate_insert_sql(low_inserts, wowhead_npcs))
            f.write("\n")

        if total_u == 0 and total_i == 0:
            f.write("-- No NPCs to fix in this priority level.\n")

    print(f"Wrote {low_path}")

    grand_total = (
        sum(len(v) for v in high_updates.values()) +
        sum(len(v) for v in high_inserts.values()) +
        sum(len(v) for v in med_updates.values()) +
        sum(len(v) for v in med_inserts.values()) +
        sum(len(v) for v in low_updates.values()) +
        sum(len(v) for v in low_inserts.values())
    )
    print(f"\nGrand total NPCs to fix: {grand_total}")

if __name__ == '__main__':
    main()
